# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
# SPDX-License-Identifier: MPL-2.0
"""Build a host-native FMI 3 Co-Simulation test FMU."""

from __future__ import annotations

import hashlib
from enum import Enum
from importlib.machinery import ModuleSpec
from importlib.util import find_spec
import os
from pathlib import Path
import shutil
import sys
import xml.etree.ElementTree as ET

import fmpy
from fmpy.build import create_cmake_settings
from fmpy.model_description import (
    CoSimulation,
    ModelDescription,
    ModelExchange,
    ModelVariable,
    Unknown,
)
from fmpy.template import create_fmu

from VeraGridEngine.IO.fmu.exporter.packager import package_fmu
from VeraGridEngine.IO.fmu.importer.native_binary import resolve_fmi_three_host_binary
from tests.FMI.cmake_process import (
    FmiThreeCmakeCommandResult,
    run_fmi_three_cmake_command,
)


class FmiThreeCompiledFixtureProfile(Enum):
    """Select deterministic native behavior generated by the shared builder."""

    SCALAR = 1
    CONSTANT_ARRAY = 2
    CONFIGURABLE_ARRAY = 3
    SCALAR_OBSERVABLE_STATE_LEAK = 4


def _create_fmi_three_scalar_model_description() -> ModelDescription:
    """Create deterministic dual-interface metadata for FMPy's C template.

    FMPy owns the reference FMI 3 ABI surface. VeraGrid supplies fixed identity
    and scalar variables so every generated archive has the same declared
    semantics without copying the upstream implementation into this repository.

    :return: Deterministic scalar Co-Simulation and Model Exchange description.
    """

    # Keep value references aligned with the reference template's generated
    # enumeration so the native getters and setters exercise exact variables.
    time_variable: ModelVariable = ModelVariable(
        name="time",
        valueReference=0,
        type="Float64",
        causality="independent",
        variability="continuous",
        description="Independent time observed by the host-native test FMU.",
    )
    input_variable: ModelVariable = ModelVariable(
        name="control_input",
        valueReference=1,
        type="Float64",
        causality="input",
        variability="continuous",
        start="0.0",
        description="Scalar input used to verify FMI 3 Float64 access.",
    )
    output_variable: ModelVariable = ModelVariable(
        name="observed_output",
        valueReference=2,
        type="Float64",
        causality="output",
        variability="continuous",
        description=(
            "Control input plus completed communication time produced by the "
            "synthetic scalar fixture."
        ),
    )
    structural_gain_variable: ModelVariable = ModelVariable(
        name="structural_gain",
        valueReference=3,
        type="Float64",
        causality="structuralParameter",
        variability="fixed",
        initial="exact",
        start="1.0",
        description="Configuration Mode gain applied to the scalar input.",
    )
    structural_size_variable: ModelVariable = ModelVariable(
        name="structural_size",
        valueReference=4,
        type="UInt64",
        causality="structuralParameter",
        variability="fixed",
        initial="exact",
        start="3",
        description="Scalar UInt64 value used to exercise Configuration Mode.",
    )
    continuous_state_variable: ModelVariable = ModelVariable(
        name="continuous_state",
        valueReference=5,
        type="Float64",
        causality="local",
        variability="continuous",
        initial="exact",
        start="1.0",
        description="Single state owned by the synthetic Model Exchange fixture.",
    )
    state_derivative_variable: ModelVariable = ModelVariable(
        name="state_derivative",
        valueReference=6,
        type="Float64",
        causality="local",
        variability="continuous",
        initial="calculated",
        derivative=continuous_state_variable,
        description="Derivative equal to control_input minus continuous_state.",
    )

    # Build the final FMPy model directly. No parallel transfer object survives
    # beyond source generation, and all identity fields remain deterministic.
    fmi_three_description: ModelDescription = ModelDescription()
    fmi_three_description.fmiVersion = "3.0"
    fmi_three_description.modelName = "VeraGridFmiThreeScalarCoSimulationTest"
    fmi_three_description.description = (
        "Repository-generated FMI 3 Co-Simulation host fixture."
    )
    fmi_three_description.generationTool = "VeraGrid FMI test harness with FMPy"
    fmi_three_description.instantiationToken = (
        "b51b3650-6e5f-4f68-9462-6d230981aec0"
    )
    fmi_three_description.coSimulation = CoSimulation(
        modelIdentifier="VeraGridFmiThreeScalarCoSimulationTest",
    )
    # The reference C template exports both FMI 3 instantiation entrypoints.
    # Sharing the identifier lets one compiled artifact prove that worker
    # construction selects the authenticated interface without duplicating a
    # second native build fixture. Its single state exercises the real ME vector
    # lifecycle while all numerical integration remains owned by the caller.
    fmi_three_description.modelExchange = ModelExchange(
        modelIdentifier="VeraGridFmiThreeScalarCoSimulationTest",
    )
    fmi_three_description.modelVariables = list(
        (
            time_variable,
            input_variable,
            output_variable,
            structural_gain_variable,
            structural_size_variable,
            continuous_state_variable,
            state_derivative_variable,
        )
    )
    fmi_three_description.outputs = list((Unknown(variable=output_variable),))
    fmi_three_description.derivatives = list(
        (Unknown(variable=state_derivative_variable),)
    )
    fmi_three_description.initialUnknowns = list(
        (
            Unknown(variable=output_variable),
            Unknown(variable=state_derivative_variable),
        )
    )
    return fmi_three_description


def _create_fmi_three_constant_array_model_description() -> ModelDescription:
    """Create dual-interface metadata for one six-value Float64 array pair.

    :return: Constant-array FMI 3 model description for native testing.
    """

    time_variable: ModelVariable = ModelVariable(
        name="time",
        valueReference=0,
        type="Float64",
        causality="independent",
        variability="continuous",
        description="Independent time observed by the array fixture.",
    )
    input_variable: ModelVariable = ModelVariable(
        name="array_input",
        valueReference=1,
        type="Float64",
        causality="input",
        variability="continuous",
        start="0.0",
        description="Three-by-two input flattened in FMI row-major order.",
    )
    output_variable: ModelVariable = ModelVariable(
        name="array_output",
        valueReference=2,
        type="Float64",
        causality="output",
        variability="continuous",
        description="Input plus completed time for each flattened element.",
    )
    fmi_three_description: ModelDescription = ModelDescription()
    fmi_three_description.fmiVersion = "3.0"
    fmi_three_description.modelName = "VeraGridFmiThreeArrayCoSimulationTest"
    fmi_three_description.description = (
        "Repository-generated FMI 3 constant-array dual-interface fixture."
    )
    fmi_three_description.generationTool = "VeraGrid FMI test harness with FMPy"
    fmi_three_description.instantiationToken = (
        "7291fe63-7174-413f-a6e4-5265a91e7a20"
    )
    fmi_three_description.coSimulation = CoSimulation(
        modelIdentifier="VeraGridFmiThreeArrayCoSimulationTest",
    )
    fmi_three_description.modelExchange = ModelExchange(
        modelIdentifier="VeraGridFmiThreeArrayCoSimulationTest",
    )
    fmi_three_description.modelVariables = list(
        (time_variable, input_variable, output_variable)
    )
    fmi_three_description.outputs = list((Unknown(variable=output_variable),))
    fmi_three_description.initialUnknowns = list(
        (Unknown(variable=output_variable),)
    )
    return fmi_three_description


def _create_fmi_three_configurable_array_model_description() -> ModelDescription:
    """Create dual-interface metadata for one structurally sized array pair.

    :return: Configurable-array FMI 3 model description for native testing.
    """

    time_variable: ModelVariable = ModelVariable(
        name="time",
        valueReference=0,
        type="Float64",
        causality="independent",
        variability="continuous",
        description="Independent time observed by the configurable fixture.",
    )
    input_variable: ModelVariable = ModelVariable(
        name="array_input",
        valueReference=1,
        type="Float64",
        causality="input",
        variability="continuous",
        start="0.0",
        description="Input whose active prefix follows structural_size.",
    )
    output_variable: ModelVariable = ModelVariable(
        name="array_output",
        valueReference=2,
        type="Float64",
        causality="output",
        variability="continuous",
        description="Configured input plus completed communication time.",
    )
    structural_size_variable: ModelVariable = ModelVariable(
        name="structural_size",
        valueReference=3,
        type="UInt64",
        causality="structuralParameter",
        variability="fixed",
        initial="exact",
        start="3",
        description="Active array cardinality bounded by the native fixture.",
    )
    fmi_three_description: ModelDescription = ModelDescription()
    fmi_three_description.fmiVersion = "3.0"
    fmi_three_description.modelName = "VeraGridFmiThreeConfigurableArrayTest"
    fmi_three_description.description = (
        "Repository-generated FMI 3 configurable-array dual-interface fixture."
    )
    fmi_three_description.generationTool = "VeraGrid FMI test harness with FMPy"
    fmi_three_description.instantiationToken = (
        "b96e6dbf-aaad-47ef-ae46-a544356be651"
    )
    fmi_three_description.coSimulation = CoSimulation(
        modelIdentifier="VeraGridFmiThreeConfigurableArrayTest",
    )
    fmi_three_description.modelExchange = ModelExchange(
        modelIdentifier="VeraGridFmiThreeConfigurableArrayTest",
    )
    fmi_three_description.modelVariables = list(
        (
            time_variable,
            input_variable,
            output_variable,
            structural_size_variable,
        )
    )
    fmi_three_description.outputs = list((Unknown(variable=output_variable),))
    fmi_three_description.initialUnknowns = list(
        (Unknown(variable=output_variable),)
    )
    return fmi_three_description


def _install_fmi_three_constant_array_dimensions(
    staging_directory: Path,
) -> None:
    """Declare two 3-by-2 arrays in FMPy's generated model description.

    FMPy's C template does not currently render ``Dimension`` elements. The
    fixture adds only those declarative children and the full input start value
    before VeraGrid and FMPy independently parse the resulting FMU.

    :param staging_directory: Extracted source FMU to update declaratively.
    :return: None.
    """

    model_description_path: Path = staging_directory / "modelDescription.xml"
    model_description_tree: ET.ElementTree = ET.parse(model_description_path)
    model_description_root: ET.Element = model_description_tree.getroot()
    model_variables: ET.Element | None = model_description_root.find(
        "ModelVariables"
    )
    if model_variables is not None:
        pass
    else:
        raise AssertionError("Generated FMI 3 array fixture has no ModelVariables")
    array_variable_names: tuple[str, str] = ("array_input", "array_output")
    declared_array_count: int = 0
    variable_element: ET.Element
    for variable_element in model_variables:
        variable_name: str | None = variable_element.attrib.get("name", None)
        if variable_name in array_variable_names:
            first_dimension: ET.Element = ET.SubElement(
                variable_element,
                "Dimension",
            )
            first_dimension.set("start", "3")
            second_dimension: ET.Element = ET.SubElement(
                variable_element,
                "Dimension",
            )
            second_dimension.set("start", "2")
            if variable_name == "array_input":
                variable_element.set("start", "0.0 0.1 1.0 1.1 2.0 2.1")
            else:
                pass
            declared_array_count += 1
        else:
            pass
    if declared_array_count == len(array_variable_names):
        pass
    else:
        raise AssertionError("Generated FMI 3 array variables are incomplete")
    model_exchange: ET.Element | None = model_description_root.find(
        "ModelExchange"
    )
    if model_exchange is not None:
        model_exchange.set("canGetAndSetFMUState", "true")
        model_exchange.set("canSerializeFMUState", "false")
    else:
        raise AssertionError("Generated FMI 3 array fixture has no ModelExchange")
    model_description_tree.write(
        model_description_path,
        encoding="utf-8",
        xml_declaration=True,
    )


def _install_fmi_three_configurable_array_metadata(
    staging_directory: Path,
) -> None:
    """Declare referenced dimensions and the UInt64 controller in generated XML.

    :param staging_directory: Extracted source FMU to update declaratively.
    :return: None.
    """

    model_description_path: Path = staging_directory / "modelDescription.xml"
    model_description_tree: ET.ElementTree = ET.parse(model_description_path)
    model_description_root: ET.Element = model_description_tree.getroot()
    model_variables: ET.Element | None = model_description_root.find(
        "ModelVariables"
    )
    if model_variables is not None:
        pass
    else:
        raise AssertionError(
            "Generated configurable-array fixture has no ModelVariables"
        )
    array_variable_names: tuple[str, str] = ("array_input", "array_output")
    configured_array_count: int = 0
    structural_size_count: int = 0
    variable_element: ET.Element
    for variable_element in model_variables:
        variable_name: str | None = variable_element.attrib.get("name", None)
        if variable_name in array_variable_names:
            dimension: ET.Element = ET.SubElement(variable_element, "Dimension")
            dimension.set("valueReference", "3")
            if variable_name == "array_input":
                variable_element.set("start", "0.0 0.1 0.2")
            else:
                pass
            configured_array_count += 1
        else:
            if variable_name == "structural_size":
                if variable_element.tag == "Float64":
                    variable_element.tag = "UInt64"
                    structural_size_count += 1
                else:
                    raise AssertionError(
                        "Generated configurable size has an unexpected type"
                    )
            else:
                pass
    if configured_array_count == 2 and structural_size_count == 1:
        pass
    else:
        raise AssertionError(
            "Generated configurable-array declarations are incomplete"
        )
    model_exchange: ET.Element | None = model_description_root.find(
        "ModelExchange"
    )
    if model_exchange is not None:
        model_exchange.set("canGetAndSetFMUState", "true")
        model_exchange.set("canSerializeFMUState", "false")
    else:
        raise AssertionError(
            "Generated configurable-array fixture has no ModelExchange"
        )
    model_description_tree.write(
        model_description_path,
        encoding="utf-8",
        xml_declaration=True,
    )


def _install_fmi_three_scalar_metadata(
    staging_directory: Path,
) -> None:
    """Complete scalar metadata omitted by FMPy's compact source-FMU template.

    FMPy's C template respects ``ModelVariable.type`` but its XML template
    currently renders every variable as Float64 and omits FMI 3 derivative
    metadata. The fixture corrects the UInt64 tag and declares the exact
    state-derivative relationship represented by its native implementation.

    :param staging_directory: Extracted scalar source FMU to update.
    :return: None.
    """

    model_description_path: Path = staging_directory / "modelDescription.xml"
    model_description_tree: ET.ElementTree = ET.parse(model_description_path)
    model_description_root: ET.Element = model_description_tree.getroot()
    model_variables: ET.Element | None = model_description_root.find(
        "ModelVariables"
    )
    if model_variables is not None:
        pass
    else:
        raise AssertionError("Generated FMI 3 scalar fixture has no ModelVariables")

    # FMPy's compact XML template renders only the model identifier for
    # Co-Simulation. Advertise optional capabilities in the final declarative
    # artifact so the native worker proves that declining them remains valid.
    co_simulation: ET.Element | None = model_description_root.find("CoSimulation")
    if co_simulation is not None:
        pass
    else:
        raise AssertionError("Generated FMI 3 scalar fixture has no CoSimulation")
    co_simulation.set("providesIntermediateUpdate", "true")
    co_simulation.set("mightReturnEarlyFromDoStep", "true")
    co_simulation.set("canReturnEarlyAfterIntermediateUpdate", "true")
    co_simulation.set("hasEventMode", "true")
    co_simulation.set("canGetAndSetFMUState", "true")
    co_simulation.set("canSerializeFMUState", "false")
    model_exchange: ET.Element | None = model_description_root.find(
        "ModelExchange"
    )
    if model_exchange is not None:
        model_exchange.set("canGetAndSetFMUState", "true")
        model_exchange.set("canSerializeFMUState", "false")
        model_exchange.set("needsCompletedIntegratorStep", "true")
    else:
        raise AssertionError("Generated FMI 3 scalar fixture has no ModelExchange")

    structural_size_count: int = 0
    continuous_state_count: int = 0
    state_derivative_count: int = 0
    variable_element: ET.Element
    for variable_element in model_variables:
        variable_name: str | None = variable_element.attrib.get("name", None)
        if variable_name == "structural_size":
            if variable_element.tag == "Float64":
                variable_element.tag = "UInt64"
                structural_size_count += 1
            else:
                raise AssertionError(
                    "Generated structural-size variable has an unexpected type"
                )
        else:
            if variable_name == "continuous_state":
                variable_element.set("initial", "exact")
                continuous_state_count += 1
            else:
                if variable_name == "state_derivative":
                    variable_element.set("initial", "calculated")
                    variable_element.set("derivative", "5")
                    state_derivative_count += 1
                else:
                    pass
    if (
        structural_size_count == 1
        and continuous_state_count == 1
        and state_derivative_count == 1
    ):
        pass
    else:
        raise AssertionError("Generated scalar FMI 3 declarations are incomplete")

    # FMPy's compact XML template emits outputs and initial unknowns but omits
    # ContinuousStateDerivative. Insert the sole derivative in schema order,
    # immediately after the output and before both initial unknowns.
    model_structure: ET.Element | None = model_description_root.find(
        "ModelStructure"
    )
    if model_structure is not None:
        pass
    else:
        raise AssertionError("Generated FMI 3 scalar fixture has no ModelStructure")
    output_count: int = 0
    model_structure_element: ET.Element
    for model_structure_element in model_structure:
        if model_structure_element.tag == "Output":
            output_count += 1
        else:
            pass
    if output_count == 1:
        continuous_state_derivative: ET.Element = ET.Element(
            "ContinuousStateDerivative"
        )
        continuous_state_derivative.set("valueReference", "6")
        model_structure.insert(output_count, continuous_state_derivative)
        event_indicator: ET.Element = ET.Element("EventIndicator")
        event_indicator.set("valueReference", "5")
        model_structure.append(event_indicator)
    else:
        raise AssertionError("Generated scalar FMI 3 output structure is incomplete")
    model_description_tree.write(
        model_description_path,
        encoding="utf-8",
        xml_declaration=True,
    )


def _remove_unrepresented_generation_timestamp(staging_directory: Path) -> None:
    """Remove FMPy's optional timestamp from the bounded importer fixture.

    The current VeraGrid FMI 3 metadata contract deliberately rejects root
    attributes it does not represent. FMPy's generator always emits its
    optional generation timestamp, so the test harness removes that single
    attribute before compilation instead of weakening the importer gate.

    :param staging_directory: Extracted source FMU containing modelDescription.xml.
    :return: None.
    """

    model_description_path: Path = staging_directory / "modelDescription.xml"
    model_description_tree: ET.ElementTree = ET.parse(model_description_path)
    model_description_root: ET.Element = model_description_tree.getroot()
    if "generationDateAndTime" in model_description_root.attrib:
        del model_description_root.attrib["generationDateAndTime"]
    else:
        pass
    model_description_tree.write(
        model_description_path,
        encoding="utf-8",
        xml_declaration=True,
    )


def _render_fmi_three_build_description(model_identifier: str) -> str:
    """Render the source-build declaration for the exact native identifier.

    FMPy's source-FMU template currently emits ``model`` as a fixed build
    identifier. Replacing only that declarative file keeps the generated ABI
    reference intact while making the build description agree with the model
    description and the strict VeraGrid binary preflight.

    :param model_identifier: Exact Co-Simulation native model identifier.
    :return: FMI 3 build-description XML text.
    """

    build_description_xml: str = f"""<?xml version="1.0" encoding="UTF-8"?>
<fmiBuildDescription fmiVersion="3.0">
  <BuildConfiguration modelIdentifier="{model_identifier}">
    <SourceFileSet language="C99">
      <SourceFile name="model.c"/>
    </SourceFileSet>
  </BuildConfiguration>
</fmiBuildDescription>
"""
    return build_description_xml


def resolve_fmi_three_test_cmake_executable() -> Path | None:
    """Return the native executable owned by the importable CMake package.

    The FMI workflow installs the public ``cmake`` package into the selected
    Python environment. Resolving the active package's native binary avoids its
    Python launcher, PATH lookup, and private machine locations.

    :return: Environment-owned CMake executable, or ``None`` when unavailable.
    """

    cmake_module_spec: ModuleSpec | None = find_spec("cmake")
    cmake_candidate: Path | None
    if cmake_module_spec is not None:
        cmake_package_locations: tuple[str, ...]
        if cmake_module_spec.submodule_search_locations is not None:
            cmake_package_locations = tuple(
                cmake_module_spec.submodule_search_locations
            )
        else:
            cmake_package_locations = tuple()
    else:
        cmake_package_locations = tuple()
    if len(cmake_package_locations) == 1:
        if sys.platform.startswith("win"):
            cmake_relative_path: str = "data/bin/cmake.exe"
        else:
            cmake_relative_path = "data/bin/cmake"
        cmake_candidate = (
            Path(cmake_package_locations[0]) / cmake_relative_path
        ).resolve()
    else:
        cmake_candidate = None
    if cmake_candidate is not None:
        if sys.platform.startswith("win"):
            cmake_is_executable: bool = cmake_candidate.is_file()
        else:
            cmake_is_executable = (
                cmake_candidate.is_file() and os.access(cmake_candidate, os.X_OK)
            )
        if cmake_is_executable:
            cmake_executable: Path | None = cmake_candidate
        else:
            cmake_executable = None
    else:
        cmake_executable = None
    return cmake_executable


def _copy_fmi_three_reference_headers(staging_directory: Path) -> None:
    """Copy public FMI 3 headers into the generated source-bearing FMU.

    The final temporary FMU therefore contains the headers required to compile
    its included C source. They come from the already-declared FMPy dependency
    and retain their embedded BSD-2-Clause notices.

    :param staging_directory: Extracted source FMU receiving the headers.
    :return: None.
    :raises FileNotFoundError: If the installed FMPy package lacks a header.
    """

    fmpy_source_directory: Path = Path(fmpy.__file__).resolve().parent / "c-code"
    header_names: tuple[str, str, str] = (
        "fmi3PlatformTypes.h",
        "fmi3FunctionTypes.h",
        "fmi3Functions.h",
    )
    header_name: str
    for header_name in header_names:
        source_header: Path = fmpy_source_directory / header_name
        if source_header.is_file():
            shutil.copy2(source_header, staging_directory / "sources" / header_name)
        else:
            raise FileNotFoundError(
                f"The installed FMPy package does not provide {source_header}"
            )


def _replace_verified_fmi_three_source_block(
    source_text: str,
    start_marker: str,
    end_marker: str,
    expected_sha256: str,
    replacement: str,
    block_name: str,
) -> str:
    """Replace one uniquely delimited FMPy source block after digest validation.

    :param source_text: LF-normalized generated C source.
    :param start_marker: Exact first text owned by the upstream block.
    :param end_marker: Exact first text following the upstream block.
    :param expected_sha256: Approved SHA-256 for FMPy 0.3.26 and 0.3.31.
    :param replacement: VeraGrid-owned deterministic C implementation.
    :param block_name: Block identity used in drift diagnostics.
    :return: Source text containing the verified replacement.
    """

    if source_text.count(start_marker) == 1 and source_text.count(end_marker) == 1:
        pass
    else:
        raise AssertionError(
            f"FMPy {fmpy.__version__} changed the FMI 3 {block_name} source boundaries"
        )
    block_start: int = source_text.index(start_marker)
    block_end: int = source_text.index(end_marker, block_start)
    if block_end > block_start:
        pass
    else:
        raise AssertionError(
            f"FMPy {fmpy.__version__} reordered the FMI 3 {block_name} source block"
        )
    upstream_block: str = source_text[block_start:block_end]
    observed_sha256: str = hashlib.sha256(upstream_block.encode("utf-8")).hexdigest().upper()
    if observed_sha256 == expected_sha256:
        pass
    else:
        raise AssertionError(
            f"FMPy {fmpy.__version__} changed the FMI 3 {block_name} source block "
            f"to SHA-256 {observed_sha256}"
        )
    replaced_source: str = "".join(
        (source_text[:block_start], replacement, source_text[block_end:])
    )
    return replaced_source


def _install_fmi_three_array_model_exchange_support(
    source_text: str,
    fixture_profile: FmiThreeCompiledFixtureProfile,
) -> str:
    """Install a zero-state Model Exchange ABI for one array fixture.

    The array fixtures expose algebraic outputs only. Their selected output
    values are refreshed by ``fmi3SetTime`` while the external solver owns an
    explicitly empty continuous-state vector.

    :param source_text: Verified FMPy reference source with array storage.
    :param fixture_profile: Constant or configurable array behavior.
    :return: Source with the required Model Exchange constructor and lifecycle.
    """

    model_exchange_constructor: str = """fmi3Instance fmi3InstantiateModelExchange(
    fmi3String                 instanceName,
    fmi3String                 instantiationToken,
    fmi3String                 resourcePath,
    fmi3Boolean                visible,
    fmi3Boolean                loggingOn,
    fmi3InstanceEnvironment    instanceEnvironment,
    fmi3LogMessageCallback     logMessage) {

    UNUSED(instanceName);
    UNUSED(resourcePath);
    UNUSED(visible);
    UNUSED(loggingOn);

    if (!logMessage) {
        return NULL;
    }

    if (!instantiationToken) {
        logMessage(instanceEnvironment, fmi3Error, LOG_CATEGORY_ERROR, "Argument instantiationToken must not be NULL.");
        return NULL;
    } else if (strcmp(instantiationToken, INSTANTIATION_TOKEN)) {
        logMessage(instanceEnvironment, fmi3Error, LOG_CATEGORY_ERROR, "Wrong instantiationToken.");
        return NULL;
    }

    Model* model = (Model*)calloc(1, sizeof(Model));

    if (!model) {
        return NULL;
    }

    model->instanceEnvironment = instanceEnvironment;
    model->logMessage = logMessage;

    reset(model);

    return model;
}

"""
    updated_source: str = _replace_verified_fmi_three_source_block(
        source_text=source_text,
        start_marker="fmi3Instance fmi3InstantiateModelExchange(",
        end_marker="fmi3Instance fmi3InstantiateCoSimulation(",
        expected_sha256=(
            "6300D09EE5CDBD38D8978038B1197244AED2A395169A8E234AE67F1E2C7B7942"
        ),
        replacement=model_exchange_constructor,
        block_name="array Model Exchange constructor",
    )

    initial_discrete_update: str = """fmi3Status fmi3UpdateDiscreteStates(fmi3Instance instance,
    fmi3Boolean* discreteStatesNeedUpdate,
    fmi3Boolean* terminateSimulation,
    fmi3Boolean* nominalsOfContinuousStatesChanged,
    fmi3Boolean* valuesOfContinuousStatesChanged,
    fmi3Boolean* nextEventTimeDefined,
    fmi3Float64* nextEventTime) {

    BEGIN_FUNCTION();

    if (!discreteStatesNeedUpdate || !terminateSimulation ||
        !nominalsOfContinuousStatesChanged || !valuesOfContinuousStatesChanged ||
        !nextEventTimeDefined || !nextEventTime) {
        ERROR("All discrete-state output pointers are required.");
    }

    *discreteStatesNeedUpdate = fmi3False;
    *terminateSimulation = fmi3False;
    *nominalsOfContinuousStatesChanged = fmi3False;
    *valuesOfContinuousStatesChanged = fmi3False;
    *nextEventTimeDefined = fmi3False;
    *nextEventTime = 0.0;
    END_FUNCTION();
}

"""
    updated_source = _replace_verified_fmi_three_source_block(
        source_text=updated_source,
        start_marker="fmi3Status fmi3UpdateDiscreteStates(",
        end_marker=(
            "/***************************************************\n"
            "Types for Functions for Model Exchange"
        ),
        expected_sha256=(
            "C8C8A7CB013135DAA5AE6DFCD7B8FECE661646C1DE5EBEF8FB34097C0E54BC06"
        ),
        replacement=initial_discrete_update,
        block_name="array initial discrete-state update",
    )

    model_exchange_lifecycle: str = """/***************************************************
Types for Functions for Model Exchange
****************************************************/

fmi3Status fmi3EnterContinuousTimeMode(fmi3Instance instance) {
    BEGIN_FUNCTION();
    END_FUNCTION();
}

fmi3Status fmi3CompletedIntegratorStep(fmi3Instance instance,
    fmi3Boolean  noSetFMUStatePriorToCurrentPoint,
    fmi3Boolean* enterEventMode,
    fmi3Boolean* terminateSimulation) {

    UNUSED(noSetFMUStatePriorToCurrentPoint);
    BEGIN_FUNCTION();

    if (!enterEventMode || !terminateSimulation) {
        ERROR("Completed-integrator-step output pointers are required.");
    } else {
        *enterEventMode = fmi3False;
        *terminateSimulation = fmi3False;
    }

    END_FUNCTION();
}

fmi3Status fmi3SetTime(fmi3Instance instance, fmi3Float64 time) {
    BEGIN_FUNCTION();

    if (isfinite(time)) {
        model->time = time;
        for (size_t arrayIndex = 0; arrayIndex < ARRAY_VALUE_COUNT; arrayIndex++) {
            model->array_output[arrayIndex] = model->array_input[arrayIndex] + time;
        }
    } else {
        ERROR("Model Exchange time must be finite.");
    }

    END_FUNCTION();
}

fmi3Status fmi3SetContinuousStates(fmi3Instance instance,
    const fmi3Float64 continuousStates[],
    size_t nContinuousStates) {

    UNUSED(continuousStates);
    BEGIN_FUNCTION();

    if (nContinuousStates == 0) {
        /* This algebraic array fixture has no continuous state. */
    } else {
        ERROR("The array Model Exchange fixture has zero continuous states.");
    }

    END_FUNCTION();
}

fmi3Status fmi3GetContinuousStateDerivatives(fmi3Instance instance,
    fmi3Float64 derivatives[],
    size_t nContinuousStates) {

    UNUSED(derivatives);
    BEGIN_FUNCTION();

    if (nContinuousStates == 0) {
        /* This algebraic array fixture has no derivatives. */
    } else {
        ERROR("The array Model Exchange fixture has zero derivatives.");
    }

    END_FUNCTION();
}

fmi3Status fmi3GetEventIndicators(fmi3Instance instance,
    fmi3Float64 eventIndicators[],
    size_t nEventIndicators) {

    UNUSED(eventIndicators);
    BEGIN_FUNCTION();

    if (nEventIndicators == 0) {
        /* This algebraic array fixture has no event indicators. */
    } else {
        ERROR("The array Model Exchange fixture has zero event indicators.");
    }

    END_FUNCTION();
}

fmi3Status fmi3GetContinuousStates(fmi3Instance instance,
    fmi3Float64 continuousStates[],
    size_t nContinuousStates) {

    UNUSED(continuousStates);
    BEGIN_FUNCTION();

    if (nContinuousStates == 0) {
        /* The external solver owns an explicitly empty state vector. */
    } else {
        ERROR("The array Model Exchange fixture has zero continuous states.");
    }

    END_FUNCTION();
}

fmi3Status fmi3GetNominalsOfContinuousStates(fmi3Instance instance,
    fmi3Float64 nominals[],
    size_t nContinuousStates) {

    UNUSED(nominals);
    BEGIN_FUNCTION();

    if (nContinuousStates == 0) {
        /* An empty state vector has no nominals. */
    } else {
        ERROR("The array Model Exchange fixture has zero state nominals.");
    }

    END_FUNCTION();
}

fmi3Status fmi3GetNumberOfEventIndicators(fmi3Instance instance,
    size_t* nEventIndicators) {

    BEGIN_FUNCTION();

    if (nEventIndicators) {
        *nEventIndicators = 0;
    } else {
        ERROR("The event-indicator count pointer is required.");
    }

    END_FUNCTION();
}

fmi3Status fmi3GetNumberOfContinuousStates(fmi3Instance instance,
    size_t* nContinuousStates) {

    BEGIN_FUNCTION();

    if (nContinuousStates) {
        *nContinuousStates = 0;
    } else {
        ERROR("The continuous-state count pointer is required.");
    }

    END_FUNCTION();
}

"""
    if fixture_profile == FmiThreeCompiledFixtureProfile.CONSTANT_ARRAY:
        pass
    else:
        if fixture_profile == FmiThreeCompiledFixtureProfile.CONFIGURABLE_ARRAY:
            model_exchange_lifecycle = model_exchange_lifecycle.replace(
                "ARRAY_VALUE_COUNT",
                "model->structural_size",
            )
        else:
            raise ValueError("Model Exchange array support requires an array fixture")
    return _replace_verified_fmi_three_source_block(
        source_text=updated_source,
        start_marker=(
            "/***************************************************\n"
            "Types for Functions for Model Exchange"
        ),
        end_marker=(
            "/***************************************************\n"
            "Types for Functions for Co-Simulation"
        ),
        expected_sha256=(
            "95BB64609C543F9B1D30F2F5692A11F71116498F041A4E9D4E3AD0FFE59937C2"
        ),
        replacement=model_exchange_lifecycle,
        block_name="array Model Exchange lifecycle",
    )


def _install_fmi_three_behavior(
    staging_directory: Path,
    fixture_profile: FmiThreeCompiledFixtureProfile,
) -> None:
    """Install deterministic scalar or constant-array native behavior.

    FMPy owns the broad FMI 3 ABI template. VeraGrid replaces only bounded
    blocks required by this synthetic fixture, after exact digest checks against
    the identical FMPy 0.3.26 and 0.3.31 template blocks. A complete step
    advances the independent time and reports
    ``structural_gain * control_input + end_time`` as a deliberately
    non-electrical scalar observation.

    :param staging_directory: Extracted source FMU containing ``sources/model.c``.
    :param fixture_profile: Exact behavior selected by the shared builder.
    :return: None.
    """

    model_source_path: Path = staging_directory / "sources" / "model.c"
    generated_source: str = model_source_path.read_bytes().decode("utf-8")
    normalized_source: str = generated_source.replace("\r\n", "\n")

    # Add the sole standard header needed by the finite-value checks.
    include_replacement: str = """#include <math.h>
#include <string.h>
#include "fmi3Functions.h"


"""
    normalized_source = _replace_verified_fmi_three_source_block(
        source_text=normalized_source,
        start_marker="#include <string.h>",
        end_marker="#define INSTANTIATION_TOKEN",
        expected_sha256="01B498351CA0B17CF114FA366C603344FB99E404B5F8922A10672F5D7EFEDC3C",
        replacement=include_replacement,
        block_name="include",
    )

    if fixture_profile in (
        FmiThreeCompiledFixtureProfile.SCALAR,
        FmiThreeCompiledFixtureProfile.SCALAR_OBSERVABLE_STATE_LEAK,
    ):
        # Retain the importer permission in native fixture state so the same
        # compiled FMU can prove both the strict default and negotiated path.
        scalar_storage_replacement: str = """typedef struct {

    fmi3Float64 time;
    fmi3Float64 control_input;
    fmi3Float64 observed_output;
    fmi3Float64 structural_gain;
    fmi3UInt64 structural_size;
    fmi3Float64 continuous_state;
    fmi3Float64 state_derivative;
    size_t discrete_state_iteration;

    fmi3InstanceEnvironment instanceEnvironment;
    fmi3LogMessageCallback logMessage;
    fmi3Boolean early_return_allowed;

} Model;

"""
        normalized_source = _replace_verified_fmi_three_source_block(
            source_text=normalized_source,
            start_marker="typedef struct {\n\n    fmi3Float64 time;",
            end_marker="static void reset(Model* instance)",
            expected_sha256=(
                "B5F6A594A1B69B4C72AD0B41808F976B3C325384CBF3FBFE13C9C61D9A76B4B6"
            ),
            replacement=scalar_storage_replacement,
            block_name="scalar storage",
        )

        # FMPy's reference template deliberately rejects Model Exchange. The
        # scalar fixture declares both interfaces, so install the second native
        # constructor with the same validated ownership rules as Co-Simulation.
        model_exchange_constructor_replacement: str = """fmi3Instance fmi3InstantiateModelExchange(
    fmi3String                 instanceName,
    fmi3String                 instantiationToken,
    fmi3String                 resourcePath,
    fmi3Boolean                visible,
    fmi3Boolean                loggingOn,
    fmi3InstanceEnvironment    instanceEnvironment,
    fmi3LogMessageCallback     logMessage) {

    UNUSED(instanceName);
    UNUSED(resourcePath);
    UNUSED(visible);
    UNUSED(loggingOn);

    if (!logMessage) {
        return NULL;
    }

    if (!instantiationToken) {
        logMessage(instanceEnvironment, fmi3Error, LOG_CATEGORY_ERROR, "Argument instantiationToken must not be NULL.");
        return NULL;
    } else if (strcmp(instantiationToken, INSTANTIATION_TOKEN)) {
        logMessage(instanceEnvironment, fmi3Error, LOG_CATEGORY_ERROR, "Wrong instantiationToken.");
        return NULL;
    }

    Model* model = (Model*)calloc(1, sizeof(Model));

    if (!model) {
        return NULL;
    }

    model->instanceEnvironment = instanceEnvironment;
    model->logMessage = logMessage;

    reset(model);

    return model;
}

"""
        normalized_source = _replace_verified_fmi_three_source_block(
            source_text=normalized_source,
            start_marker="fmi3Instance fmi3InstantiateModelExchange(",
            end_marker="fmi3Instance fmi3InstantiateCoSimulation(",
            expected_sha256=(
                "6300D09EE5CDBD38D8978038B1197244AED2A395169A8E234AE67F1E2C7B7942"
            ),
            replacement=model_exchange_constructor_replacement,
            block_name="Model Exchange constructor",
        )

        co_simulation_constructor_replacement: str = """fmi3Instance fmi3InstantiateCoSimulation(
    fmi3String                     instanceName,
    fmi3String                     instantiationToken,
    fmi3String                     resourcePath,
    fmi3Boolean                    visible,
    fmi3Boolean                    loggingOn,
    fmi3Boolean                    eventModeUsed,
    fmi3Boolean                    earlyReturnAllowed,
    const fmi3ValueReference       requiredIntermediateVariables[],
    size_t                         nRequiredIntermediateVariables,
    fmi3InstanceEnvironment        instanceEnvironment,
    fmi3LogMessageCallback         logMessage,
    fmi3IntermediateUpdateCallback intermediateUpdate) {

    UNUSED(instanceName);
    UNUSED(resourcePath);
    UNUSED(visible);
    UNUSED(loggingOn);
    UNUSED(eventModeUsed);
    UNUSED(requiredIntermediateVariables);
    UNUSED(nRequiredIntermediateVariables);
    UNUSED(intermediateUpdate);

    if (!logMessage) {
        return NULL;
    }

    if (!instantiationToken) {
        logMessage(instanceEnvironment, fmi3Error, LOG_CATEGORY_ERROR, "Argument instantiationToken must not be NULL.");
        return NULL;
    } else if (strcmp(instantiationToken, INSTANTIATION_TOKEN)) {
        logMessage(instanceEnvironment, fmi3Error, LOG_CATEGORY_ERROR, "Wrong instantiationToken.");
        return NULL;
    }

    Model* model = (Model*)calloc(1, sizeof(Model));

    if (!model) {
        return NULL;
    }

    model->instanceEnvironment = instanceEnvironment;
    model->logMessage = logMessage;

    reset(model);
    model->early_return_allowed = earlyReturnAllowed;

    return model;
}

"""
        normalized_source = _replace_verified_fmi_three_source_block(
            source_text=normalized_source,
            start_marker="fmi3Instance fmi3InstantiateCoSimulation(",
            end_marker="fmi3Instance fmi3InstantiateScheduledExecution(",
            expected_sha256=(
                "11CA1B8C40AE687D142592E448E755FBEC26C43450FDF9C00971287F3C88E554"
            ),
            replacement=co_simulation_constructor_replacement,
            block_name="Co-Simulation constructor",
        )

        enter_event_mode_replacement: str = """fmi3Status fmi3EnterEventMode(fmi3Instance instance) {
    BEGIN_FUNCTION();
    END_FUNCTION();
}

"""
        normalized_source = _replace_verified_fmi_three_source_block(
            source_text=normalized_source,
            start_marker="fmi3Status fmi3EnterEventMode(",
            end_marker="fmi3Status fmi3Terminate(",
            expected_sha256=(
                "0ACE320787B845B2894DBA213026F812640B571012948F0E15FBC765F5C8E898"
            ),
            replacement=enter_event_mode_replacement,
            block_name="Model Exchange Event Mode transition",
        )

        initial_discrete_update_replacement: str = """fmi3Status fmi3UpdateDiscreteStates(fmi3Instance instance,
    fmi3Boolean* discreteStatesNeedUpdate,
    fmi3Boolean* terminateSimulation,
    fmi3Boolean* nominalsOfContinuousStatesChanged,
    fmi3Boolean* valuesOfContinuousStatesChanged,
    fmi3Boolean* nextEventTimeDefined,
    fmi3Float64* nextEventTime) {

    BEGIN_FUNCTION();

    if (!discreteStatesNeedUpdate || !terminateSimulation ||
        !nominalsOfContinuousStatesChanged || !valuesOfContinuousStatesChanged ||
        !nextEventTimeDefined || !nextEventTime) {
        ERROR("All discrete-state output pointers are required.");
    }

    *terminateSimulation = fmi3False;
    *nominalsOfContinuousStatesChanged = fmi3False;
    *nextEventTimeDefined = fmi3False;
    *nextEventTime = 0.0;
    if (model->control_input == 7.0 && model->time < 0.25) {
        *nextEventTimeDefined = fmi3True;
        *nextEventTime = 0.25;
    }
    if (model->control_input == 9.0 && model->discrete_state_iteration == 0) {
        model->discrete_state_iteration = 1;
        *discreteStatesNeedUpdate = fmi3True;
        *valuesOfContinuousStatesChanged = fmi3False;
    } else if (model->control_input == 9.0 && model->discrete_state_iteration == 1) {
        model->discrete_state_iteration = 2;
        model->continuous_state += 1.0;
        *discreteStatesNeedUpdate = fmi3False;
        *valuesOfContinuousStatesChanged = fmi3True;
    } else {
        *discreteStatesNeedUpdate = fmi3False;
        *valuesOfContinuousStatesChanged = fmi3False;
    }
    END_FUNCTION();
}

"""
        normalized_source = _replace_verified_fmi_three_source_block(
            source_text=normalized_source,
            start_marker="fmi3Status fmi3UpdateDiscreteStates(",
            end_marker=(
                "/***************************************************\n"
                "Types for Functions for Model Exchange"
            ),
            expected_sha256=(
                "C8C8A7CB013135DAA5AE6DFCD7B8FECE661646C1DE5EBEF8FB34097C0E54BC06"
            ),
            replacement=initial_discrete_update_replacement,
            block_name="initial discrete-state update",
        )

        # The native model owns one deterministic state and evaluates its
        # derivative without advancing it. Solver and event semantics remain
        # outside the fixture so the external integrator boundary stays exact.
        model_exchange_lifecycle_replacement: str = """/***************************************************
Types for Functions for Model Exchange
****************************************************/

fmi3Status fmi3EnterContinuousTimeMode(fmi3Instance instance) {
    BEGIN_FUNCTION();
    END_FUNCTION();
}

fmi3Status fmi3CompletedIntegratorStep(fmi3Instance instance,
    fmi3Boolean  noSetFMUStatePriorToCurrentPoint,
    fmi3Boolean* enterEventMode,
    fmi3Boolean* terminateSimulation) {

    UNUSED(noSetFMUStatePriorToCurrentPoint);
    BEGIN_FUNCTION();

    if (!enterEventMode || !terminateSimulation) {
        ERROR("Completed-integrator-step output pointers are required.");
    } else {
        if (model->control_input == 9.0) {
            model->discrete_state_iteration = 0;
            *enterEventMode = fmi3True;
        } else {
            *enterEventMode = fmi3False;
        }
        *terminateSimulation = fmi3False;
    }

    END_FUNCTION();
}

/* Providing independent variables and re-initialization of caching */

fmi3Status fmi3SetTime(fmi3Instance instance, fmi3Float64 time) {
    BEGIN_FUNCTION();

    if (isfinite(time)) {
        model->time = time;
    } else {
        ERROR("Model Exchange time must be finite.");
    }

    END_FUNCTION();
}

fmi3Status fmi3SetContinuousStates(fmi3Instance instance,
    const fmi3Float64 continuousStates[],
    size_t nContinuousStates) {

    BEGIN_FUNCTION();

    if (nContinuousStates == 1 && continuousStates) {
        if (isfinite(continuousStates[0])) {
            model->continuous_state = continuousStates[0];
        } else {
            ERROR("The continuous state must be finite.");
        }
    } else {
        ERROR("The scalar Model Exchange fixture requires one continuous state.");
    }

    END_FUNCTION();
}

/* Evaluation of the model equations */

fmi3Status fmi3GetContinuousStateDerivatives(fmi3Instance instance,
    fmi3Float64 derivatives[],
    size_t nContinuousStates) {

    BEGIN_FUNCTION();

    if (nContinuousStates == 1 && derivatives) {
        model->state_derivative = model->control_input - model->continuous_state;
        derivatives[0] = model->state_derivative;
    } else {
        ERROR("The scalar Model Exchange fixture requires one derivative.");
    }

    END_FUNCTION();
}

fmi3Status fmi3GetEventIndicators(fmi3Instance instance,
    fmi3Float64 eventIndicators[],
    size_t nEventIndicators) {

    BEGIN_FUNCTION();

    if (nEventIndicators == 1 && eventIndicators) {
        eventIndicators[0] = model->continuous_state - 2.5;
    } else {
        ERROR("The scalar Model Exchange fixture requires one event indicator.");
    }

    END_FUNCTION();
}

fmi3Status fmi3GetContinuousStates(fmi3Instance instance,
    fmi3Float64 continuousStates[],
    size_t nContinuousStates) {

    BEGIN_FUNCTION();

    if (nContinuousStates == 1 && continuousStates) {
        continuousStates[0] = model->continuous_state;
    } else {
        ERROR("The scalar Model Exchange fixture requires one continuous state.");
    }

    END_FUNCTION();
}

fmi3Status fmi3GetNominalsOfContinuousStates(fmi3Instance instance,
    fmi3Float64 nominals[],
    size_t nContinuousStates) {

    BEGIN_FUNCTION();

    if (nContinuousStates == 1 && nominals) {
        nominals[0] = 1.0;
    } else {
        ERROR("The scalar Model Exchange fixture requires one state nominal.");
    }

    END_FUNCTION();
}

fmi3Status fmi3GetNumberOfEventIndicators(fmi3Instance instance,
    size_t* nEventIndicators) {

    BEGIN_FUNCTION();

    if (nEventIndicators) {
        *nEventIndicators = 1;
    } else {
        ERROR("The event-indicator count pointer is required.");
    }

    END_FUNCTION();
}

fmi3Status fmi3GetNumberOfContinuousStates(fmi3Instance instance,
    size_t* nContinuousStates) {

    BEGIN_FUNCTION();

    if (nContinuousStates) {
        *nContinuousStates = 1;
    } else {
        ERROR("The continuous-state count pointer is required.");
    }

    END_FUNCTION();
}

"""
        # The adversarial profile intentionally changes a later derivative
        # getter without changing the visible time, state, or input tuple. This
        # models hidden vendor state that cannot be reconstructed safely when
        # the FMU does not provide optional Get/Set FMU State checkpoints.
        if (
            fixture_profile
            == FmiThreeCompiledFixtureProfile.SCALAR_OBSERVABLE_STATE_LEAK
        ):
            conforming_derivative_block: str = """        model->state_derivative = model->control_input - model->continuous_state;
        derivatives[0] = model->state_derivative;
"""
            leaking_derivative_block: str = """        model->state_derivative = model->control_input - model->continuous_state
            + (fmi3Float64)model->discrete_state_iteration;
        model->discrete_state_iteration += 1u;
        derivatives[0] = model->state_derivative;
"""
            if model_exchange_lifecycle_replacement.count(
                conforming_derivative_block
            ) == 1:
                model_exchange_lifecycle_replacement = (
                    model_exchange_lifecycle_replacement.replace(
                        conforming_derivative_block,
                        leaking_derivative_block,
                        1,
                    )
                )
            else:
                raise AssertionError(
                    "The scalar Model Exchange derivative block changed unexpectedly"
                )
        else:
            pass
        normalized_source = _replace_verified_fmi_three_source_block(
            source_text=normalized_source,
            start_marker=(
                "/***************************************************\n"
                "Types for Functions for Model Exchange"
            ),
            end_marker=(
                "/***************************************************\n"
                "Types for Functions for Co-Simulation"
            ),
            expected_sha256=(
                "95BB64609C543F9B1D30F2F5692A11F71116498F041A4E9D4E3AD0FFE59937C2"
            ),
            replacement=model_exchange_lifecycle_replacement,
            block_name="Model Exchange lifecycle",
        )
    else:
        normalized_source = _install_fmi_three_array_model_exchange_support(
            source_text=normalized_source,
            fixture_profile=fixture_profile,
        )

    if fixture_profile == FmiThreeCompiledFixtureProfile.CONSTANT_ARRAY:
        storage_replacement: str = """#define ARRAY_VALUE_COUNT 6

typedef struct {

    fmi3Float64 time;
    fmi3Float64 array_input[ARRAY_VALUE_COUNT];
    fmi3Float64 array_output[ARRAY_VALUE_COUNT];

    fmi3InstanceEnvironment instanceEnvironment;
    fmi3LogMessageCallback logMessage;

} Model;

static void reset(Model* instance) {

    const fmi3Float64 initialValues[ARRAY_VALUE_COUNT] = {0.0, 0.1, 1.0, 1.1, 2.0, 2.1};
    instance->time = 0.0;
    for (size_t i = 0; i < ARRAY_VALUE_COUNT; i++) {
        instance->array_input[i] = initialValues[i];
        instance->array_output[i] = 0.0;
    }

}

"""
        normalized_source = _replace_verified_fmi_three_source_block(
            source_text=normalized_source,
            start_marker="typedef struct {",
            end_marker="#define BEGIN_FUNCTION()",
            expected_sha256=(
                "55B608D8A26CB424B31A46563E893CA95FE125A9E94637C9233D7B4336440093"
            ),
            replacement=storage_replacement,
            block_name="constant-array storage",
        )
    else:
        if fixture_profile == FmiThreeCompiledFixtureProfile.CONFIGURABLE_ARRAY:
            storage_replacement = """#define MAX_ARRAY_VALUE_COUNT 6

typedef struct {

    fmi3Float64 time;
    fmi3Float64 array_input[MAX_ARRAY_VALUE_COUNT];
    fmi3Float64 array_output[MAX_ARRAY_VALUE_COUNT];
    fmi3UInt64 structural_size;

    fmi3InstanceEnvironment instanceEnvironment;
    fmi3LogMessageCallback logMessage;

} Model;

static void reset(Model* instance) {

    const fmi3Float64 initialValues[3] = {0.0, 0.1, 0.2};
    instance->time = 0.0;
    instance->structural_size = 3;
    for (size_t i = 0; i < MAX_ARRAY_VALUE_COUNT; i++) {
        instance->array_input[i] = i < 3 ? initialValues[i] : 0.0;
        instance->array_output[i] = 0.0;
    }

}

"""
            normalized_source = _replace_verified_fmi_three_source_block(
                source_text=normalized_source,
                start_marker="typedef struct {",
                end_marker="#define BEGIN_FUNCTION()",
                expected_sha256=(
                    "3B85EE779BA19D3D3E382CCD9E65270F072842C4D05DB714720D963BF4D1A69F"
                ),
                replacement=storage_replacement,
                block_name="configurable-array storage",
            )
        else:
            if fixture_profile in (
                FmiThreeCompiledFixtureProfile.SCALAR,
                FmiThreeCompiledFixtureProfile.SCALAR_OBSERVABLE_STATE_LEAK,
            ):
                pass
            else:
                raise ValueError("Unsupported compiled FMI 3 fixture profile")

    # Every checkpoint-capable fixture uses the same complete native Model
    # snapshot.  The separately derived no-checkpoint fixture changes only the
    # declarative capability so the importer can prove fail-closed preparation.
    checkpoint_replacement: str = """/* Getting and setting the internal FMU state */

fmi3Status fmi3GetFMUState(fmi3Instance instance, fmi3FMUState* FMUState) {

    BEGIN_FUNCTION();

    if (!FMUState) {
        ERROR("The FMU state pointer is required.");
    }

    Model* savedState = (Model*)*FMUState;

    if (!savedState) {
        savedState = (Model*)calloc(1, sizeof(Model));
    }

    if (!savedState) {
        ERROR("The FMU state could not be allocated.");
    }

    *savedState = *model;
    *FMUState = savedState;

    END_FUNCTION();
}

fmi3Status fmi3SetFMUState(fmi3Instance instance, fmi3FMUState FMUState) {

    BEGIN_FUNCTION();

    if (!FMUState) {
        ERROR("The FMU state is required.");
    }

    Model* savedState = (Model*)FMUState;
    *model = *savedState;

    END_FUNCTION();
}

fmi3Status fmi3FreeFMUState(fmi3Instance instance, fmi3FMUState* FMUState) {

    BEGIN_FUNCTION();

    if (!FMUState) {
        ERROR("The FMU state pointer is required.");
    }

    free(*FMUState);
    *FMUState = NULL;

    END_FUNCTION();
}

"""
    normalized_source = _replace_verified_fmi_three_source_block(
        source_text=normalized_source,
        start_marker="/* Getting and setting the internal FMU state */",
        end_marker="fmi3Status fmi3SerializedFMUStateSize",
        expected_sha256=(
            "A2E98B409F6C5A4692A240B9814D5D09E49B7EE3FD5708EC8662B439869A55AD"
        ),
        replacement=checkpoint_replacement,
        block_name="checkpoint lifecycle",
    )

    # Initialization binds the synthetic independent time to the caller's
    # explicit start value without introducing another lifecycle state machine.
    initialization_replacement: str = """fmi3Status fmi3EnterInitializationMode(fmi3Instance instance,
    fmi3Boolean toleranceDefined,
    fmi3Float64 tolerance,
    fmi3Float64 startTime,
    fmi3Boolean stopTimeDefined,
    fmi3Float64 stopTime) {

    BEGIN_FUNCTION();

    if (!isfinite(startTime)) {
        ERROR("Start time must be finite.");
    }

    if (toleranceDefined && (!isfinite(tolerance) || tolerance <= 0.0)) {
        ERROR("Defined tolerance must be finite and positive.");
    }

    if (stopTimeDefined && (!isfinite(stopTime) || stopTime <= startTime)) {
        ERROR("Defined stop time must be finite and greater than start time.");
    }

    model->time = startTime;

    END_FUNCTION();
}
"""
    normalized_source = _replace_verified_fmi_three_source_block(
        source_text=normalized_source,
        start_marker="fmi3Status fmi3EnterInitializationMode(",
        end_marker="fmi3Status fmi3ExitInitializationMode(",
        expected_sha256="157D2A14F6EB972AC7499C8121297ADEA0571B0F274F257D18D9DF4F59F19E6D",
        replacement=initialization_replacement,
        block_name="initialization",
    )

    # FMPy's reference template deliberately leaves Configuration Mode as a
    # stub. Both fixtures with structural parameters implement the exact
    # enter/exit ABI surface so the worker exercises a real native write.
    if fixture_profile in (
        FmiThreeCompiledFixtureProfile.SCALAR,
        FmiThreeCompiledFixtureProfile.SCALAR_OBSERVABLE_STATE_LEAK,
        FmiThreeCompiledFixtureProfile.CONFIGURABLE_ARRAY,
    ):
        configuration_replacement: str = """fmi3Status fmi3EnterConfigurationMode(fmi3Instance instance) {
    BEGIN_FUNCTION();
    END_FUNCTION();
}

fmi3Status fmi3ExitConfigurationMode(fmi3Instance instance) {
    BEGIN_FUNCTION();
    END_FUNCTION();
}

"""
        normalized_source = _replace_verified_fmi_three_source_block(
            source_text=normalized_source,
            start_marker="fmi3Status fmi3EnterConfigurationMode(",
            end_marker="fmi3Status fmi3GetIntervalDecimal(",
            expected_sha256=(
                "C47E2782A4B4BBE54FDF1A3261B7F6F84B7129A2A8D5B37965D5440F4EC0B7A9"
            ),
            replacement=configuration_replacement,
            block_name="configuration mode",
        )
        set_uint64_replacement: str = """fmi3Status fmi3SetUInt64(fmi3Instance instance,
    const fmi3ValueReference valueReferences[],
    size_t nValueReferences,
    const fmi3UInt64 values[],
    size_t nValues) {

    BEGIN_FUNCTION();

    if (!valueReferences || !values) {
        ERROR("UInt64 SET pointers are required.");
    }

    if (nValueReferences != nValues) {
        ERROR("UInt64 SET references and values must align.");
    }

    for (size_t valueIndex = 0; valueIndex < nValues; valueIndex++) {
        const ValueReference valueReference = valueReferences[valueIndex];
        switch (valueReference) {
        case vr_structural_size:
            model->structural_size = values[valueIndex];
            break;
        default:
            ERROR("Unknown writable value reference for variable type UInt64.");
        }
    }

    END_FUNCTION();
}

"""
        if fixture_profile == FmiThreeCompiledFixtureProfile.CONFIGURABLE_ARRAY:
            set_uint64_replacement = set_uint64_replacement.replace(
                "case vr_structural_size:\n"
                "            model->structural_size = values[valueIndex];",
                "case vr_structural_size:\n"
                "            if (values[valueIndex] > MAX_ARRAY_VALUE_COUNT) {\n"
                "                ERROR(\"Configured array size exceeds capacity.\");\n"
                "            }\n"
                "            model->structural_size = values[valueIndex];",
                1,
            )
            uint64_block_name: str = "configurable-array setUInt64"
        else:
            uint64_block_name = "scalar setUInt64"
        normalized_source = _replace_verified_fmi_three_source_block(
            source_text=normalized_source,
            start_marker="fmi3Status fmi3SetUInt64(",
            end_marker="fmi3Status fmi3SetBoolean(",
            expected_sha256=(
                "879449CB99C67E76E75C1FBA0AE2EE3E55D0BA35A48A3F170D6029D55D15197B"
            ),
            replacement=set_uint64_replacement,
            block_name=uint64_block_name,
        )
    else:
        pass

    if fixture_profile in (
        FmiThreeCompiledFixtureProfile.CONSTANT_ARRAY,
        FmiThreeCompiledFixtureProfile.CONFIGURABLE_ARRAY,
    ):
        get_float64_replacement: str = """fmi3Status fmi3GetFloat64(fmi3Instance instance,
    const fmi3ValueReference valueReferences[],
    size_t nValueReferences,
    fmi3Float64 values[],
    size_t nValues) {

    BEGIN_FUNCTION();

    if (!valueReferences || !values) {
        ERROR("Float64 GET pointers are required.");
    }

    size_t valueIndex = 0;
    for (size_t referenceIndex = 0; referenceIndex < nValueReferences; referenceIndex++) {
        const ValueReference valueReference = valueReferences[referenceIndex];
        switch (valueReference) {
        case vr_time:
            if (valueIndex >= nValues) {
                ERROR("Float64 GET scalar capacity is insufficient.");
            }
            values[valueIndex] = model->time;
            valueIndex++;
            break;
        case vr_array_input:
            if (valueIndex > nValues || nValues - valueIndex < ARRAY_VALUE_COUNT) {
                ERROR("Float64 GET input-array capacity is insufficient.");
            }
            for (size_t arrayIndex = 0; arrayIndex < ARRAY_VALUE_COUNT; arrayIndex++) {
                values[valueIndex + arrayIndex] = model->array_input[arrayIndex];
            }
            valueIndex += ARRAY_VALUE_COUNT;
            break;
        case vr_array_output:
            if (valueIndex > nValues || nValues - valueIndex < ARRAY_VALUE_COUNT) {
                ERROR("Float64 GET output-array capacity is insufficient.");
            }
            for (size_t arrayIndex = 0; arrayIndex < ARRAY_VALUE_COUNT; arrayIndex++) {
                values[valueIndex + arrayIndex] = model->array_output[arrayIndex];
            }
            valueIndex += ARRAY_VALUE_COUNT;
            break;
        default:
            ERROR("Unknown value reference for variable type Float64.");
        }
    }

    if (valueIndex != nValues) {
        ERROR("Float64 GET serialized cardinality is inconsistent.");
    }

    END_FUNCTION();
}

"""
        if fixture_profile == FmiThreeCompiledFixtureProfile.CONFIGURABLE_ARRAY:
            get_float64_replacement = get_float64_replacement.replace(
                "ARRAY_VALUE_COUNT",
                "model->structural_size",
            ).replace(
                "if (!valueReferences || !values)",
                "if (!valueReferences || (nValues > 0 && !values))",
            )
            get_float64_block_name: str = "configurable-array getFloat64"
            get_float64_expected_sha256: str = (
                "BB08B2B1AD5893FBD91CF3B998D791BFFA544419A7B9EB657EE281EDA2CEA55F"
            )
        else:
            get_float64_block_name = "constant-array getFloat64"
            get_float64_expected_sha256 = (
                "24500597CDCED4D8A84578A0CC380AA090443C9D58005BD745203B52718B9B01"
            )
        normalized_source = _replace_verified_fmi_three_source_block(
            source_text=normalized_source,
            start_marker="fmi3Status fmi3GetFloat64(",
            end_marker="fmi3Status fmi3GetInt8(",
            expected_sha256=get_float64_expected_sha256,
            replacement=get_float64_replacement,
            block_name=get_float64_block_name,
        )
        set_float64_replacement: str = """fmi3Status fmi3SetFloat64(fmi3Instance instance,
    const fmi3ValueReference valueReferences[],
    size_t nValueReferences,
    const fmi3Float64 values[],
    size_t nValues) {

    BEGIN_FUNCTION();

    if (!valueReferences || !values) {
        ERROR("Float64 SET pointers are required.");
    }

    size_t valueIndex = 0;
    for (size_t referenceIndex = 0; referenceIndex < nValueReferences; referenceIndex++) {
        const ValueReference valueReference = valueReferences[referenceIndex];
        switch (valueReference) {
        case vr_array_input:
            if (valueIndex > nValues || nValues - valueIndex < ARRAY_VALUE_COUNT) {
                ERROR("Float64 SET input-array cardinality is insufficient.");
            }
            for (size_t arrayIndex = 0; arrayIndex < ARRAY_VALUE_COUNT; arrayIndex++) {
                const fmi3Float64 value = values[valueIndex + arrayIndex];
                if (!isfinite(value)) {
                    ERROR("Float64 SET array values must be finite.");
                }
                model->array_input[arrayIndex] = value;
            }
            valueIndex += ARRAY_VALUE_COUNT;
            break;
        default:
            ERROR("Unknown writable value reference for variable type Float64.");
        }
    }

    if (valueIndex != nValues) {
        ERROR("Float64 SET serialized cardinality is inconsistent.");
    }

    END_FUNCTION();
}

"""
        if fixture_profile == FmiThreeCompiledFixtureProfile.CONFIGURABLE_ARRAY:
            set_float64_replacement = set_float64_replacement.replace(
                "ARRAY_VALUE_COUNT",
                "model->structural_size",
            ).replace(
                "if (!valueReferences || !values)",
                "if (!valueReferences || (nValues > 0 && !values))",
            )
            set_float64_block_name: str = "configurable-array setFloat64"
            set_float64_expected_sha256: str = (
                "82B011F22144E5933FBBCA404630DF7E6242CCA4A93CE8480993A214576C082D"
            )
        else:
            set_float64_block_name = "constant-array setFloat64"
            set_float64_expected_sha256 = (
                "D1E415C3C79A0969E29885478FA4F6074D6F2D45AFA3F90EA82963568B9DE50C"
            )
        normalized_source = _replace_verified_fmi_three_source_block(
            source_text=normalized_source,
            start_marker="fmi3Status fmi3SetFloat64(",
            end_marker="fmi3Status fmi3SetInt8(",
            expected_sha256=set_float64_expected_sha256,
            replacement=set_float64_replacement,
            block_name=set_float64_block_name,
        )
    else:
        pass

    # One successful step advances time and writes every outcome explicitly.
    # Validation precedes all model mutation in both deterministic profiles.
    if fixture_profile in (
        FmiThreeCompiledFixtureProfile.CONSTANT_ARRAY,
        FmiThreeCompiledFixtureProfile.CONFIGURABLE_ARRAY,
    ):
        do_step_replacement: str = """fmi3Status fmi3DoStep(fmi3Instance instance,
    fmi3Float64 currentCommunicationPoint,
    fmi3Float64 communicationStepSize,
    fmi3Boolean noSetFMUStatePriorToCurrentPoint,
    fmi3Boolean* eventHandlingNeeded,
    fmi3Boolean* terminateSimulation,
    fmi3Boolean* earlyReturn,
    fmi3Float64* lastSuccessfulTime) {

    UNUSED(noSetFMUStatePriorToCurrentPoint);
    BEGIN_FUNCTION();

    if (!eventHandlingNeeded || !terminateSimulation || !earlyReturn || !lastSuccessfulTime) {
        ERROR("All doStep output pointers are required.");
    }

    if (!isfinite(currentCommunicationPoint) || currentCommunicationPoint != model->time) {
        ERROR("Current communication point must equal the finite model time.");
    }

    if (!isfinite(communicationStepSize) || communicationStepSize <= 0.0) {
        ERROR("Communication step size must be finite and positive.");
    }

    const fmi3Float64 completedTime = currentCommunicationPoint + communicationStepSize;
    if (!isfinite(completedTime)) {
        ERROR("Completed array fixture time must be finite.");
    }
    for (size_t arrayIndex = 0; arrayIndex < ARRAY_VALUE_COUNT; arrayIndex++) {
        const fmi3Float64 completedValue = model->array_input[arrayIndex] + completedTime;
        if (!isfinite(completedValue)) {
            ERROR("Completed array fixture values must be finite.");
        }
        model->array_output[arrayIndex] = completedValue;
    }

    model->time = completedTime;
    *eventHandlingNeeded = fmi3False;
    *terminateSimulation = model->array_input[0] == 9.0 ? fmi3True : fmi3False;
    *earlyReturn = fmi3False;
    *lastSuccessfulTime = completedTime;

    END_FUNCTION();
}

"""
        if fixture_profile == FmiThreeCompiledFixtureProfile.CONFIGURABLE_ARRAY:
            do_step_replacement = do_step_replacement.replace(
                "ARRAY_VALUE_COUNT",
                "model->structural_size",
            ).replace(
                "*terminateSimulation = model->array_input[0] == 9.0 ? fmi3True : fmi3False;",
                "*terminateSimulation = model->structural_size > 0 && "
                "model->array_input[0] == 9.0 ? fmi3True : fmi3False;",
            )
        else:
            pass
    else:
        do_step_replacement = """fmi3Status fmi3DoStep(fmi3Instance instance,
    fmi3Float64 currentCommunicationPoint,
    fmi3Float64 communicationStepSize,
    fmi3Boolean noSetFMUStatePriorToCurrentPoint,
    fmi3Boolean* eventHandlingNeeded,
    fmi3Boolean* terminateSimulation,
    fmi3Boolean* earlyReturn,
    fmi3Float64* lastSuccessfulTime) {

    UNUSED(noSetFMUStatePriorToCurrentPoint);
    BEGIN_FUNCTION();

    if (!eventHandlingNeeded || !terminateSimulation || !earlyReturn || !lastSuccessfulTime) {
        ERROR("All doStep output pointers are required.");
    }

    if (!isfinite(currentCommunicationPoint) || currentCommunicationPoint != model->time) {
        ERROR("Current communication point must equal the finite model time.");
    }

    if (!isfinite(communicationStepSize) || communicationStepSize <= 0.0) {
        ERROR("Communication step size must be finite and positive.");
    }

    if (!isfinite(model->control_input)) {
        ERROR("Control input must be finite.");
    }

    /* Input 8.0 triggers a legal zero-progress return only when authorized. */
    const fmi3Boolean returnEarly =
        model->early_return_allowed && model->control_input == 8.0;
    const fmi3Float64 completedTime = returnEarly ? currentCommunicationPoint :
        currentCommunicationPoint + communicationStepSize;
    const fmi3Float64 completedObservation =
        model->structural_gain * model->control_input + completedTime;

    if (!isfinite(model->structural_gain) ||
        !isfinite(completedTime) || !isfinite(completedObservation)) {
        ERROR("Completed scalar fixture values must be finite.");
    }

    model->time = completedTime;
    model->observed_output = completedObservation;
    *eventHandlingNeeded = fmi3False;
    /* The input value 9.0 deterministically exercises final-output handling. */
    *terminateSimulation = model->control_input == 9.0 ? fmi3True : fmi3False;
    *earlyReturn = returnEarly;
    *lastSuccessfulTime = completedTime;

    END_FUNCTION();
}

"""
    normalized_source = _replace_verified_fmi_three_source_block(
        source_text=normalized_source,
        start_marker="fmi3Status fmi3DoStep(",
        end_marker=(
            "/***************************************************\n"
            "Types for Functions for Scheduled Execution"
        ),
        expected_sha256="7A77B378ADD06F365C1E644A71A7B46C21A28FC1674B52C133C9335560CEB550",
        replacement=do_step_replacement,
        block_name="doStep",
    )
    model_source_path.write_bytes(normalized_source.encode("utf-8"))


def build_fmi_three_co_simulation_fmu(
    work_directory: Path,
    cmake_executable: Path,
    cmake_command_timeout_seconds: float,
    termination_grace_seconds: float,
    fixture_profile: FmiThreeCompiledFixtureProfile,
) -> tuple[Path | None, str | None]:
    """Generate, compile, and package one host-native FMI 3 fixture.

    Every source input is either declared in this function or supplied by the
    public FMPy dependency in ``requirements.txt``. CMake output and the native
    library remain below ``work_directory`` and only the resulting temporary
    FMU is returned. No binary is copied into the repository.

    :param work_directory: Fresh pytest-owned directory for all build artifacts.
    :param cmake_executable: Exact environment-owned CMake executable to invoke.
    :param cmake_command_timeout_seconds: Positive limit for each CMake command.
    :param termination_grace_seconds: Positive bound for timeout tree teardown.
    :param fixture_profile: Deterministic scalar or array behavior.
    :return: FMU and no diagnostic, or no FMU and the configure diagnostic.
    :raises AssertionError: If compilation or packaging fails after configuration.
    :raises FileNotFoundError: If the explicit CMake executable is unavailable.
    """

    # Require the caller's environment-owned CMake path before generating any
    # source. Toolchain policy stays outside the deterministic build operation.
    if cmake_executable.is_file():
        pass
    else:
        raise FileNotFoundError(
            f"The explicit FMI 3 CMake executable does not exist: {cmake_executable}"
        )

    # Generate FMPy's required FMI 3 symbol surface from fixed VeraGrid
    # metadata, then expand it into isolated staging for host compilation.
    if fixture_profile in (
        FmiThreeCompiledFixtureProfile.SCALAR,
        FmiThreeCompiledFixtureProfile.SCALAR_OBSERVABLE_STATE_LEAK,
    ):
        fmi_three_description: ModelDescription = (
            _create_fmi_three_scalar_model_description()
        )
    else:
        if fixture_profile == FmiThreeCompiledFixtureProfile.CONSTANT_ARRAY:
            fmi_three_description = (
                _create_fmi_three_constant_array_model_description()
            )
        else:
            if fixture_profile == FmiThreeCompiledFixtureProfile.CONFIGURABLE_ARRAY:
                fmi_three_description = (
                    _create_fmi_three_configurable_array_model_description()
                )
            else:
                raise ValueError("Unsupported compiled FMI 3 fixture profile")
    source_fmu_path: Path = work_directory / "fmi-three-source.fmu"
    staging_directory: Path = work_directory / "fmi-three-staging"
    build_directory: Path = work_directory / "fmi-three-build"
    staging_directory.mkdir(parents=True)
    build_directory.mkdir(parents=True)
    create_fmu(fmi_three_description, source_fmu_path)
    fmpy.extract(source_fmu_path, unzipdir=staging_directory)
    _install_fmi_three_behavior(
        staging_directory=staging_directory,
        fixture_profile=fixture_profile,
    )
    if fixture_profile == FmiThreeCompiledFixtureProfile.CONSTANT_ARRAY:
        _install_fmi_three_constant_array_dimensions(staging_directory)
    else:
        if fixture_profile in (
            FmiThreeCompiledFixtureProfile.SCALAR,
            FmiThreeCompiledFixtureProfile.SCALAR_OBSERVABLE_STATE_LEAK,
        ):
            _install_fmi_three_scalar_metadata(staging_directory)
        else:
            if fixture_profile == FmiThreeCompiledFixtureProfile.CONFIGURABLE_ARRAY:
                _install_fmi_three_configurable_array_metadata(staging_directory)
            else:
                raise ValueError("Unsupported compiled FMI 3 fixture profile")
    _remove_unrepresented_generation_timestamp(staging_directory)

    model_identifier: str
    if fmi_three_description.coSimulation is not None:
        if fmi_three_description.coSimulation.modelIdentifier is not None:
            model_identifier = fmi_three_description.coSimulation.modelIdentifier
        else:
            raise AssertionError("The generated Co-Simulation model identifier is missing")
    else:
        raise AssertionError("The generated model description has no Co-Simulation interface")
    build_description_path: Path = staging_directory / "sources" / "buildDescription.xml"
    build_description_path.write_text(
        _render_fmi_three_build_description(model_identifier),
        encoding="utf-8",
    )
    _copy_fmi_three_reference_headers(staging_directory)
    (staging_directory / "resources").mkdir()

    # Ask FMPy to produce its exact CMake cache contract, while invoking the
    # environment-owned executable ourselves so no PATH lookup is required.
    create_cmake_settings(
        unzipdir=staging_directory,
        build_dir=build_directory,
        configuration="Release",
        all_warnings=True,
    )
    fmpy_cmake_directory: Path = Path(fmpy.__file__).resolve().parent / "c-code"
    configure_command: tuple[str, ...] = (
        str(cmake_executable),
        "-S",
        str(fmpy_cmake_directory),
        "-B",
        str(build_directory),
    )
    configure_result: FmiThreeCmakeCommandResult = run_fmi_three_cmake_command(
        command=configure_command,
        log_path=work_directory / "cmake-configure.log",
        command_timeout_seconds=cmake_command_timeout_seconds,
        termination_grace_seconds=termination_grace_seconds,
    )
    if configure_result.timed_out:
        configure_timeout_message: str = (
            f"CMake configure exceeded {cmake_command_timeout_seconds:g} seconds"
        )
        if len(configure_result.diagnostic) > 0:
            configure_timeout_message = (
                f"{configure_timeout_message}:\n{configure_result.diagnostic}"
            )
        else:
            pass
        return None, configure_timeout_message
    else:
        pass
    if configure_result.return_code == 0:
        pass
    else:
        return None, configure_result.diagnostic

    # A configured toolchain exists now. Any build error is a fixture defect and
    # must fail locally and in CI rather than being reclassified as unavailable.
    build_command: tuple[str, ...] = (
        str(cmake_executable),
        "--build",
        str(build_directory),
        "--target",
        "install",
        "--config",
        "Release",
    )
    build_result: FmiThreeCmakeCommandResult = run_fmi_three_cmake_command(
        command=build_command,
        log_path=work_directory / "cmake-build.log",
        command_timeout_seconds=cmake_command_timeout_seconds,
        termination_grace_seconds=termination_grace_seconds,
    )
    if build_result.timed_out:
        build_timeout_message: str = (
            f"The FMI 3 fixture compilation exceeded "
            f"{cmake_command_timeout_seconds:g} seconds"
        )
        if len(build_result.diagnostic) > 0:
            build_timeout_message = (
                f"{build_timeout_message}:\n{build_result.diagnostic}"
            )
        else:
            pass
        raise AssertionError(build_timeout_message)
    else:
        pass
    if build_result.return_code == 0:
        pass
    else:
        raise AssertionError(
            f"The FMI 3 fixture compilation failed:\n{build_result.diagnostic}"
        )

    # Prove the build installed exactly the binary that the importer will seek,
    # then package source and binary together as the sole test artifact.
    platform_tuple: str
    library_suffix: str
    platform_tuple, library_suffix = resolve_fmi_three_host_binary()
    native_binary_path: Path = (
        staging_directory
        / "binaries"
        / platform_tuple
        / f"{model_identifier}{library_suffix}"
    )
    if native_binary_path.is_file():
        pass
    else:
        raise AssertionError(
            f"The FMI 3 build did not install the required binary {native_binary_path}"
        )

    # MSVC generators may also install their known import/debug artifacts. They
    # are not runtime dependencies; every other sibling remains an error so a
    # newly introduced dependency cannot be silently removed from the FMU.
    if sys.platform.startswith("win"):
        removable_build_artifact_names: set[str] = set(
            (f"{model_identifier}.lib", f"{model_identifier}.pdb")
        )
    else:
        removable_build_artifact_names = set()
    installed_binary_entry: Path
    for installed_binary_entry in native_binary_path.parent.iterdir():
        if installed_binary_entry == native_binary_path:
            pass
        else:
            if (
                installed_binary_entry.is_file()
                and installed_binary_entry.name in removable_build_artifact_names
            ):
                installed_binary_entry.unlink()
            else:
                raise AssertionError(
                    "The FMI 3 fixture build installed an unexpected binary entry "
                    f"{installed_binary_entry}"
                )
    compiled_fmu_path: Path = work_directory / (
        fmi_three_description.modelName + ".fmu"
    )
    packaged_fmu_path: Path = package_fmu(staging_directory, compiled_fmu_path)
    return packaged_fmu_path, None


def derive_fmi_three_model_exchange_fmu_without_checkpoint(
    source_fmu_path: Path,
    work_directory: Path,
) -> Path:
    """Derive a scalar fixture that declines optional ME checkpoint support.

    The compiled binary is unchanged because checkpoint capability is an FMI
    interface declaration.  Only the Model Exchange metadata is narrowed, so
    the test exercises the exact same state equations without a second native
    build.

    :param source_fmu_path: Trusted compiled scalar dual-interface fixture.
    :param work_directory: Fresh pytest-owned directory for the derived FMU.
    :return: Repackaged FMU declaring no Model Exchange state checkpoint.
    """

    staging_directory: Path = work_directory / "fmi-three-no-checkpoint-staging"
    staging_directory.mkdir(parents=True)
    fmpy.extract(source_fmu_path, unzipdir=staging_directory)
    model_description_path: Path = staging_directory / "modelDescription.xml"
    model_description_tree: ET.ElementTree = ET.parse(model_description_path)
    model_description_root: ET.Element = model_description_tree.getroot()
    model_exchange: ET.Element | None = model_description_root.find(
        "ModelExchange"
    )
    if model_exchange is not None:
        model_exchange.set("canGetAndSetFMUState", "false")
        model_exchange.set("canSerializeFMUState", "false")
    else:
        raise AssertionError("Derived FMI 3 fixture has no ModelExchange")
    model_description_tree.write(
        model_description_path,
        encoding="utf-8",
        xml_declaration=True,
    )
    derived_fmu_path: Path = work_directory / (
        "VeraGridFmiThreeScalarModelExchangeNoCheckpoint.fmu"
    )
    return package_fmu(staging_directory, derived_fmu_path)
