# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
# SPDX-License-Identifier: MPL-2.0
"""Static public entry points for the FMU importer package."""

from VeraGridEngine.IO.fmu.importer.errors import (
    FmuArchiveError,
    FmuBindingError,
    FmuDependencyError,
    FmuImportError,
    FmuModeError,
)
from VeraGridEngine.IO.fmu.importer.bindings import (
    FmuBindingDirection,
    FmuImportConfig,
    FmuVariableBinding,
    validate_bindings,
)
from VeraGridEngine.IO.fmu.importer.model_description import (
    FmuInterfaceMode,
    FmuModelDescription,
    FmuVariableDescription,
    FmuVariableType,
    choose_fmu_mode,
    list_fmu_variable_names,
    read_fmu_model_description,
)
from VeraGridEngine.IO.fmu.importer.runtime_host import FmuRuntimeHost, open_fmu_runtime_host
from VeraGridEngine.IO.fmu.importer.device_config import (
    FmuCsDeviceConfigRecord,
    FmuMeDeviceConfigRecord,
    dump_fmu_cs_device_config,
    dump_fmu_me_device_config,
    load_fmu_cs_device_config,
    load_fmu_me_device_config,
)
from VeraGridEngine.IO.fmu.importer.experimental_cs import (
    FmuCsDeviceAdapter,
    FmuCsDeviceSpec,
    FmuCsDomain,
    FmuRefBinding,
    build_emt_fmu_cs_injection_template,
    build_rms_fmu_cs_injection_template,
    advance_rms_fmu_cs_devices,
    close_rms_fmu_cs_devices,
    finalize_emt_fmu_cs_devices,
    initialize_rms_fmu_cs_devices,
    queue_emt_fmu_cs_device,
    register_emt_fmu_cs_device,
    register_rms_fmu_cs_device,
)
from VeraGridEngine.IO.fmu.importer.experimental_me import (
    FmuMeDeviceAdapter,
    FmuMeDeviceSpec,
    FmuMeDomain,
    FmuMeIntegrationMethod,
    build_fmu_me_device_spec,
    build_emt_fmu_me_injection_template,
    build_rms_fmu_me_injection_template,
    advance_rms_fmu_me_devices,
    close_rms_fmu_me_devices,
    finalize_emt_fmu_me_devices,
    initialize_rms_fmu_me_devices,
    queue_emt_fmu_me_device,
    register_emt_fmu_me_device,
    register_rms_fmu_me_device,
)
from VeraGridEngine.IO.fmu.importer.emt_boundary import CompositeEmtBoundaryUpdater, build_emt_boundary_updater
from VeraGridEngine.IO.fmu.importer.device_api import (
    attach_emt_fmu_cs_device,
    attach_emt_fmu_me_device,
    attach_rms_fmu_cs_device,
    attach_rms_fmu_me_device,
)
from VeraGridEngine.IO.fmu.importer.template_api import configure_fmu_template
from VeraGridEngine.IO.fmu.importer.user_api import (
    FmuDeviceAttachmentRequest,
    FmuDeviceDomain,
    FmuReferenceValue,
    attach_fmu_to_device,
)

__all__ = [
    "FmuArchiveError",
    "FmuBindingError",
    "FmuDependencyError",
    "FmuImportError",
    "FmuModeError",
    "FmuBindingDirection",
    "FmuImportConfig",
    "FmuVariableBinding",
    "validate_bindings",
    "FmuInterfaceMode",
    "FmuModelDescription",
    "FmuVariableDescription",
    "FmuVariableType",
    "choose_fmu_mode",
    "list_fmu_variable_names",
    "read_fmu_model_description",
    "FmuRuntimeHost",
    "open_fmu_runtime_host",
    "FmuCsDeviceConfigRecord",
    "FmuMeDeviceConfigRecord",
    "dump_fmu_cs_device_config",
    "dump_fmu_me_device_config",
    "load_fmu_cs_device_config",
    "load_fmu_me_device_config",
    "FmuCsDeviceAdapter",
    "FmuCsDeviceSpec",
    "FmuCsDomain",
    "FmuRefBinding",
    "build_emt_fmu_cs_injection_template",
    "build_rms_fmu_cs_injection_template",
    "advance_rms_fmu_cs_devices",
    "close_rms_fmu_cs_devices",
    "finalize_emt_fmu_cs_devices",
    "initialize_rms_fmu_cs_devices",
    "queue_emt_fmu_cs_device",
    "register_emt_fmu_cs_device",
    "register_rms_fmu_cs_device",
    "FmuMeDeviceAdapter",
    "FmuMeDeviceSpec",
    "FmuMeDomain",
    "FmuMeIntegrationMethod",
    "build_fmu_me_device_spec",
    "build_emt_fmu_me_injection_template",
    "build_rms_fmu_me_injection_template",
    "advance_rms_fmu_me_devices",
    "close_rms_fmu_me_devices",
    "finalize_emt_fmu_me_devices",
    "initialize_rms_fmu_me_devices",
    "queue_emt_fmu_me_device",
    "register_emt_fmu_me_device",
    "register_rms_fmu_me_device",
    "CompositeEmtBoundaryUpdater",
    "build_emt_boundary_updater",
    "attach_emt_fmu_cs_device",
    "attach_emt_fmu_me_device",
    "attach_rms_fmu_cs_device",
    "attach_rms_fmu_me_device",
    "configure_fmu_template",
    "FmuDeviceAttachmentRequest",
    "FmuDeviceDomain",
    "FmuReferenceValue",
    "attach_fmu_to_device",
]
