# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
# SPDX-License-Identifier: MPL-2.0

from VeraGridEngine.Devices.Dynamic.emt_template import EmtModelTemplate
from VeraGridEngine.Devices.Dynamic.var_factory import VarFactory
from VeraGridEngine.enumerations import DeviceType, VarPowerFlowReferenceType
from VeraGridEngine.Utils.Symbolic.symbolic import Const, Var


def get_dc_line_with_vdc_control_emt_template(
        vf: VarFactory,
        name: str = "dc_line_vdc_control_emt",
) -> EmtModelTemplate:
    """
    Build a distributed DC EMT line whose internal power injection is controlled by DC voltage.

    This is intentionally separate from ``get_dc_line_with_power_input_emt_template``:
    the electrical corridor is the same three-section RL/C model, but the internal
    power order is generated by a PI loop instead of being a direct event parameter.
    """
    templ = EmtModelTemplate()
    templ.tpe = DeviceType.DCLineDevice
    templ.name = name
    templ.block.name = name

    c0 = Const(0.0)
    eps = Const(1.0e-9)
    g_damp = Const(1.0e-8)

    v_f_dc: Var = vf.add_var(name="v_f_dc", reference=VarPowerFlowReferenceType.Vf_dc)
    v_t_dc: Var = vf.add_var(name="v_t_dc", reference=VarPowerFlowReferenceType.Vt_dc)

    r1 = vf.add_var(name="R1")
    l1 = vf.add_var(name="L1")
    r2 = vf.add_var(name="R2")
    l2 = vf.add_var(name="L2")
    r3 = vf.add_var(name="R3")
    l3 = vf.add_var(name="L3")
    c_end_f = vf.add_var(name="C_end_f")
    c_mid_1 = vf.add_var(name="C_mid_1")
    c_mid_2 = vf.add_var(name="C_mid_2")
    c_end_t = vf.add_var(name="C_end_t")
    p0 = vf.add_var(name="P0")
    vdc_ref = vf.add_var(name="Vdc_ref")
    kp_vdc = vf.add_var(name="Kp_vdc")
    ki_vdc = vf.add_var(name="Ki_vdc")

    v_n1 = vf.add_var(name="v_n1")
    v_n2 = vf.add_var(name="v_n2")
    q_end_f = vf.add_var(name="q_end_f")
    q_mid_1 = vf.add_var(name="q_mid_1")
    q_mid_2 = vf.add_var(name="q_mid_2")
    q_end_t = vf.add_var(name="q_end_t")
    i_r1 = vf.add_var(name="i_r1")
    i_r2 = vf.add_var(name="i_r2")
    i_r3 = vf.add_var(name="i_r3")
    xi_vdc = vf.add_var(name="xi_vdc")

    d_q_end_f = vf.add_diff_var(name="d_q_end_f", base_var=q_end_f)
    d_q_mid_1 = vf.add_diff_var(name="d_q_mid_1", base_var=q_mid_1)
    d_q_mid_2 = vf.add_diff_var(name="d_q_mid_2", base_var=q_mid_2)
    d_q_end_t = vf.add_diff_var(name="d_q_end_t", base_var=q_end_t)
    d_i_r1 = vf.add_diff_var(name="d_i_r1", base_var=i_r1)
    d_i_r2 = vf.add_diff_var(name="d_i_r2", base_var=i_r2)
    d_i_r3 = vf.add_diff_var(name="d_i_r3", base_var=i_r3)
    d_xi_vdc = vf.add_diff_var(name="d_xi_vdc", base_var=xi_vdc)

    i_cap_end_f = vf.add_var(name="i_cap_end_f")
    i_cap_mid_1 = vf.add_var(name="i_cap_mid_1")
    i_cap_mid_2 = vf.add_var(name="i_cap_mid_2")
    i_cap_end_t = vf.add_var(name="i_cap_end_t")
    i_f_dc = vf.add_var(name="i_f_dc", reference=VarPowerFlowReferenceType.If_dc)
    i_t_dc = vf.add_var(name="i_t_dc", reference=VarPowerFlowReferenceType.It_dc)
    p_f = vf.add_var(name="p_f_dc", reference=VarPowerFlowReferenceType.Pf)
    p_t = vf.add_var(name="p_t_dc", reference=VarPowerFlowReferenceType.Pt)
    i_n1 = vf.add_var(name="i_n1")
    i_n2 = vf.add_var(name="i_n2")
    p_ctrl = vf.add_var(name="Pctrl")

    vdc_error = vdc_ref - v_f_dc
    p_ctrl_expr = p0 + kp_vdc * vdc_error + xi_vdc
    i_n1_expr = p_ctrl / (v_n1 + eps)
    i_n2_expr = p_ctrl / (v_n2 + eps)

    templ.block.in_vars = [v_f_dc, v_t_dc]
    templ.block.state_vars = [q_end_f, q_mid_1, q_mid_2, q_end_t, i_r1, i_r2, i_r3, xi_vdc]
    templ.block.diff_vars = [d_q_end_f, d_q_mid_1, d_q_mid_2, d_q_end_t, d_i_r1, d_i_r2, d_i_r3, d_xi_vdc]
    templ.block.state_eqs = [
        i_cap_end_f,
        i_cap_mid_1,
        i_cap_mid_2,
        i_cap_end_t,
        (v_n2 - v_t_dc - r1 * i_r1) / (l1 + eps),
        (v_n1 - v_n2 - r2 * i_r2) / (l2 + eps),
        (v_f_dc - v_n1 - r3 * i_r3) / (l3 + eps),
        ki_vdc * vdc_error,
    ]

    templ.block.algebraic_vars = [
        i_cap_end_f,
        i_cap_mid_1,
        i_cap_mid_2,
        i_cap_end_t,
        v_n1,
        v_n2,
        i_n1,
        i_n2,
        i_f_dc,
        i_t_dc,
        p_f,
        p_t,
        p_ctrl,
    ]
    templ.block.algebraic_eqs = [
        q_end_f - c_end_f * v_f_dc,
        q_mid_1 - c_mid_1 * v_n1,
        q_mid_2 - c_mid_2 * v_n2,
        q_end_t - c_end_t * v_t_dc,
        i_n1 - i_n1_expr,
        i_n2 - i_n2_expr,
        i_f_dc - (i_r3 + i_cap_end_f + g_damp * v_f_dc),
        i_t_dc - (-i_r1 + i_cap_end_t + g_damp * v_t_dc),
        i_n1 - (-i_r3 + i_r2 + i_cap_mid_1),
        i_n2 - (-i_r2 + i_r1 + i_cap_mid_2),
        p_f - v_f_dc * i_f_dc,
        p_t - v_t_dc * i_t_dc,
        p_ctrl - p_ctrl_expr,
    ]

    templ.block.out_vars = [i_f_dc, i_t_dc]
    templ.block.external_mapping = {
        VarPowerFlowReferenceType.Vf_dc: v_f_dc,
        VarPowerFlowReferenceType.Vt_dc: v_t_dc,
        VarPowerFlowReferenceType.Vdc: v_f_dc,
        VarPowerFlowReferenceType.If_dc: i_f_dc,
        VarPowerFlowReferenceType.It_dc: i_t_dc,
        VarPowerFlowReferenceType.Idc: i_f_dc,
        VarPowerFlowReferenceType.Pf: p_f,
        VarPowerFlowReferenceType.Pt: p_t,
    }
    templ.block.event_dict = {
        r1: Const(0.5),
        l1: Const(0.005),
        r2: Const(0.25),
        l2: Const(0.0025),
        r3: Const(0.4),
        l3: Const(0.004),
        c_end_f: Const(150.0e-6),
        c_mid_1: Const(150.0e-6),
        c_mid_2: Const(150.0e-6),
        c_end_t: Const(150.0e-6),
        p0: Const(0.0),
        vdc_ref: Const(1.0),
        kp_vdc: Const(0.0),
        ki_vdc: Const(0.0),
    }
    templ.block.init_eqs = {
        q_end_f: c_end_f * v_f_dc,
        q_mid_1: c_mid_1 * v_f_dc,
        q_mid_2: c_mid_2 * v_t_dc,
        q_end_t: c_end_t * v_t_dc,
        i_r1: -i_t_dc,
        i_r2: i_r1 + i_n2,
        i_r3: i_f_dc,
        xi_vdc: c0,
        v_n1: v_f_dc,
        v_n2: v_t_dc,
        i_cap_end_f: c0,
        i_cap_mid_1: c0,
        i_cap_mid_2: c0,
        i_cap_end_t: c0,
        i_n1: i_n1_expr,
        i_n2: i_n2_expr,
        p_ctrl: p_ctrl_expr,
        p_f: v_f_dc * i_f_dc,
        p_t: v_t_dc * i_t_dc,
    }
    templ.block.diff_init_eqs = {
        d_q_end_f: i_cap_end_f,
        d_q_mid_1: i_cap_mid_1,
        d_q_mid_2: i_cap_mid_2,
        d_q_end_t: i_cap_end_t,
        d_i_r1: (v_n2 - v_t_dc - r1 * i_r1) / (l1 + eps),
        d_i_r2: (v_n1 - v_n2 - r2 * i_r2) / (l2 + eps),
        d_i_r3: (v_f_dc - v_n1 - r3 * i_r3) / (l3 + eps),
        d_xi_vdc: ki_vdc * vdc_error,
    }

    return templ
