# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
# SPDX-License-Identifier: MPL-2.0

"""
Maintainable international-standard module for 'GovHydro4'.

This is the runtime implementation shipped by VeraGrid.
It exposes the imported public interface, explicit symbolic equations, and
"""

from __future__ import annotations

from VeraGridEngine.Devices.Dynamic.rms_template import RmsModelTemplate
from VeraGridEngine.Devices.Dynamic.var_factory import VarFactory
from VeraGridEngine.Utils.Symbolic.block import Block
import VeraGridEngine.Utils.Symbolic.symbolic as sym
from VeraGridEngine.enumerations import DeviceType
from VeraGridEngine.Utils.Symbolic.symbolic import Var
from VeraGridEngine.Utils.Symbolic.symbolic import Expr
from VeraGridEngine.Utils.Symbolic.symbolic import Const
from VeraGridEngine.Utils.Symbolic.symbolic import BinOp

def build_govhydro4_template(vf: VarFactory, name: str | None = None) -> RmsModelTemplate:
    """
    Materialize the international-standard EMT template.

    :param vf: Variable factory used to allocate the symbolic surface.
    :param name: Optional explicit runtime template name.
    :returns: Materialized EMT template.
    """
    template_name: str
    if name is None:
        template_name: str = 'GovHydro4'
    else:
        template_name: str = name

    # Allocate the template container before building the symbolic surface.
    template: RmsModelTemplate = RmsModelTemplate()
    template.tpe = DeviceType.GeneratorDevice
    template.name = template_name

    # Declare every variable explicitly before the equations reference it.
    # Declare the runtime parameter variables used by the template.
    gov_ATurb: Var = vf.add_var('gov.ATurb_' + template_name)
    gov_CustomTable_1_1: Var = vf.add_var('gov.CustomTable[1,1]_' + template_name)
    gov_CustomTable_1_2: Var = vf.add_var('gov.CustomTable[1,2]_' + template_name)
    gov_CustomTable_2_1: Var = vf.add_var('gov.CustomTable[2,1]_' + template_name)
    gov_CustomTable_2_2: Var = vf.add_var('gov.CustomTable[2,2]_' + template_name)
    gov_CustomTable_3_1: Var = vf.add_var('gov.CustomTable[3,1]_' + template_name)
    gov_CustomTable_3_2: Var = vf.add_var('gov.CustomTable[3,2]_' + template_name)
    gov_CustomTable_4_1: Var = vf.add_var('gov.CustomTable[4,1]_' + template_name)
    gov_CustomTable_4_2: Var = vf.add_var('gov.CustomTable[4,2]_' + template_name)
    gov_CustomTable_5_1: Var = vf.add_var('gov.CustomTable[5,1]_' + template_name)
    gov_CustomTable_5_2: Var = vf.add_var('gov.CustomTable[5,2]_' + template_name)
    gov_CustomTable_6_1: Var = vf.add_var('gov.CustomTable[6,1]_' + template_name)
    gov_CustomTable_6_2: Var = vf.add_var('gov.CustomTable[6,2]_' + template_name)
    gov_CustomTable_7_1: Var = vf.add_var('gov.CustomTable[7,1]_' + template_name)
    gov_CustomTable_7_2: Var = vf.add_var('gov.CustomTable[7,2]_' + template_name)
    gov_DTurb: Var = vf.add_var('gov.DTurb_' + template_name)
    gov_DeltaOmegaDbPu: Var = vf.add_var('gov.DeltaOmegaDbPu_' + template_name)
    gov_DeltaOmegaEpsPu: Var = vf.add_var('gov.DeltaOmegaEpsPu_' + template_name)
    gov_DeltaPDbPu: Var = vf.add_var('gov.DeltaPDbPu_' + template_name)
    gov_FrancisPeltonTable_1_1: Var = vf.add_var('gov.FrancisPeltonTable[1,1]_' + template_name)
    gov_FrancisPeltonTable_1_2: Var = vf.add_var('gov.FrancisPeltonTable[1,2]_' + template_name)
    gov_FrancisPeltonTable_2_1: Var = vf.add_var('gov.FrancisPeltonTable[2,1]_' + template_name)
    gov_FrancisPeltonTable_2_2: Var = vf.add_var('gov.FrancisPeltonTable[2,2]_' + template_name)
    gov_FrancisPeltonTable_3_1: Var = vf.add_var('gov.FrancisPeltonTable[3,1]_' + template_name)
    gov_FrancisPeltonTable_3_2: Var = vf.add_var('gov.FrancisPeltonTable[3,2]_' + template_name)
    gov_FrancisPeltonTable_4_1: Var = vf.add_var('gov.FrancisPeltonTable[4,1]_' + template_name)
    gov_FrancisPeltonTable_4_2: Var = vf.add_var('gov.FrancisPeltonTable[4,2]_' + template_name)
    gov_FrancisPeltonTable_5_1: Var = vf.add_var('gov.FrancisPeltonTable[5,1]_' + template_name)
    gov_FrancisPeltonTable_5_2: Var = vf.add_var('gov.FrancisPeltonTable[5,2]_' + template_name)
    gov_FrancisPeltonTable_6_1: Var = vf.add_var('gov.FrancisPeltonTable[6,1]_' + template_name)
    gov_FrancisPeltonTable_6_2: Var = vf.add_var('gov.FrancisPeltonTable[6,2]_' + template_name)
    gov_FrancisPeltonTable_7_1: Var = vf.add_var('gov.FrancisPeltonTable[7,1]_' + template_name)
    gov_FrancisPeltonTable_7_2: Var = vf.add_var('gov.FrancisPeltonTable[7,2]_' + template_name)
    gov_GMax: Var = vf.add_var('gov.GMax_' + template_name)
    gov_GMin: Var = vf.add_var('gov.GMin_' + template_name)
    gov_HDam: Var = vf.add_var('gov.HDam_' + template_name)
    gov_InitSet: Var = vf.add_var('gov.InitSet_' + template_name)
    gov_KaplanTable_1_1: Var = vf.add_var('gov.KaplanTable[1,1]_' + template_name)
    gov_KaplanTable_1_2: Var = vf.add_var('gov.KaplanTable[1,2]_' + template_name)
    gov_KaplanTable_2_1: Var = vf.add_var('gov.KaplanTable[2,1]_' + template_name)
    gov_KaplanTable_2_2: Var = vf.add_var('gov.KaplanTable[2,2]_' + template_name)
    gov_KaplanTable_3_1: Var = vf.add_var('gov.KaplanTable[3,1]_' + template_name)
    gov_KaplanTable_3_2: Var = vf.add_var('gov.KaplanTable[3,2]_' + template_name)
    gov_KaplanTable_4_1: Var = vf.add_var('gov.KaplanTable[4,1]_' + template_name)
    gov_KaplanTable_4_2: Var = vf.add_var('gov.KaplanTable[4,2]_' + template_name)
    gov_KaplanTable_5_1: Var = vf.add_var('gov.KaplanTable[5,1]_' + template_name)
    gov_KaplanTable_5_2: Var = vf.add_var('gov.KaplanTable[5,2]_' + template_name)
    gov_KaplanTable_6_1: Var = vf.add_var('gov.KaplanTable[6,1]_' + template_name)
    gov_KaplanTable_6_2: Var = vf.add_var('gov.KaplanTable[6,2]_' + template_name)
    gov_KaplanTable_7_1: Var = vf.add_var('gov.KaplanTable[7,1]_' + template_name)
    gov_KaplanTable_7_2: Var = vf.add_var('gov.KaplanTable[7,2]_' + template_name)
    gov_Lookuptab_1_1: Var = vf.add_var('gov.Lookuptab[1,1]_' + template_name)
    gov_Lookuptab_1_2: Var = vf.add_var('gov.Lookuptab[1,2]_' + template_name)
    gov_Lookuptab_2_1: Var = vf.add_var('gov.Lookuptab[2,1]_' + template_name)
    gov_Lookuptab_2_2: Var = vf.add_var('gov.Lookuptab[2,2]_' + template_name)
    gov_Lookuptab_3_1: Var = vf.add_var('gov.Lookuptab[3,1]_' + template_name)
    gov_Lookuptab_3_2: Var = vf.add_var('gov.Lookuptab[3,2]_' + template_name)
    gov_Lookuptab_4_1: Var = vf.add_var('gov.Lookuptab[4,1]_' + template_name)
    gov_Lookuptab_4_2: Var = vf.add_var('gov.Lookuptab[4,2]_' + template_name)
    gov_Lookuptab_5_1: Var = vf.add_var('gov.Lookuptab[5,1]_' + template_name)
    gov_Lookuptab_5_2: Var = vf.add_var('gov.Lookuptab[5,2]_' + template_name)
    gov_Lookuptab_6_1: Var = vf.add_var('gov.Lookuptab[6,1]_' + template_name)
    gov_Lookuptab_6_2: Var = vf.add_var('gov.Lookuptab[6,2]_' + template_name)
    gov_Lookuptab_7_1: Var = vf.add_var('gov.Lookuptab[7,1]_' + template_name)
    gov_Lookuptab_7_2: Var = vf.add_var('gov.Lookuptab[7,2]_' + template_name)
    gov_ModelInt: Var = vf.add_var('gov.ModelInt_' + template_name)
    gov_PRef0Pu: Var = vf.add_var('gov.PRef0Pu_' + template_name)
    gov_Pm0Pu: Var = vf.add_var('gov.Pm0Pu_' + template_name)
    gov_QNl: Var = vf.add_var('gov.QNl_' + template_name)
    gov_RPerm: Var = vf.add_var('gov.RPerm_' + template_name)
    gov_RTemp: Var = vf.add_var('gov.RTemp_' + template_name)
    gov_Sel: Var = vf.add_var('gov.Sel_' + template_name)
    gov_SimpleTable_1_1: Var = vf.add_var('gov.SimpleTable[1,1]_' + template_name)
    gov_SimpleTable_1_2: Var = vf.add_var('gov.SimpleTable[1,2]_' + template_name)
    gov_SimpleTable_2_1: Var = vf.add_var('gov.SimpleTable[2,1]_' + template_name)
    gov_SimpleTable_2_2: Var = vf.add_var('gov.SimpleTable[2,2]_' + template_name)
    gov_UC: Var = vf.add_var('gov.UC_' + template_name)
    gov_UO: Var = vf.add_var('gov.UO_' + template_name)
    gov_addDeltaOmega_k1: Var = vf.add_var('gov.addDeltaOmega.k1_' + template_name)
    gov_addDeltaOmega_k2: Var = vf.add_var('gov.addDeltaOmega.k2_' + template_name)
    gov_addDeltaP_k1: Var = vf.add_var('gov.addDeltaP.k1_' + template_name)
    gov_addDeltaP_k2: Var = vf.add_var('gov.addDeltaP.k2_' + template_name)
    gov_addDeltaP_k3: Var = vf.add_var('gov.addDeltaP.k3_' + template_name)
    gov_addFeedback_k1: Var = vf.add_var('gov.addFeedback.k1_' + template_name)
    gov_addFeedback_k2: Var = vf.add_var('gov.addFeedback.k2_' + template_name)
    gov_addHDam_k1: Var = vf.add_var('gov.addHDam.k1_' + template_name)
    gov_addHDam_k2: Var = vf.add_var('gov.addHDam.k2_' + template_name)
    gov_addPm_k1: Var = vf.add_var('gov.addPm.k1_' + template_name)
    gov_addPm_k2: Var = vf.add_var('gov.addPm.k2_' + template_name)
    gov_addQnl_k1: Var = vf.add_var('gov.addQnl.k1_' + template_name)
    gov_addQnl_k2: Var = vf.add_var('gov.addQnl.k2_' + template_name)
    gov_const_k: Var = vf.add_var('gov.const.k_' + template_name)
    gov_constant1_k: Var = vf.add_var('gov.constant1.k_' + template_name)
    gov_dbOmega_EpsMax: Var = vf.add_var('gov.dbOmega.EpsMax_' + template_name)
    gov_dbOmega_EpsMin: Var = vf.add_var('gov.dbOmega.EpsMin_' + template_name)
    gov_dbOmega_UMax: Var = vf.add_var('gov.dbOmega.UMax_' + template_name)
    gov_dbOmega_UMin: Var = vf.add_var('gov.dbOmega.UMin_' + template_name)
    gov_dbPower_Aux0: Var = vf.add_var('gov.dbPower.Aux0_' + template_name)
    gov_dbPower_H0: Var = vf.add_var('gov.dbPower.H0_' + template_name)
    gov_dbPower_Tolerance: Var = vf.add_var('gov.dbPower.Tolerance_' + template_name)
    gov_dbPower_U0: Var = vf.add_var('gov.dbPower.U0_' + template_name)
    gov_dbPower_UHigh: Var = vf.add_var('gov.dbPower.UHigh_' + template_name)
    gov_dbPower_ULow: Var = vf.add_var('gov.dbPower.ULow_' + template_name)
    gov_gainATurb_k: Var = vf.add_var('gov.gainATurb.k_' + template_name)
    gov_gainDTurb_k: Var = vf.add_var('gov.gainDTurb.k_' + template_name)
    gov_gainRPerm_k: Var = vf.add_var('gov.gainRPerm.k_' + template_name)
    gov_gainTg_k: Var = vf.add_var('gov.gainTg.k_' + template_name)
    gov_intLimG_initType: Var = vf.add_var('gov.intLimG.initType_' + template_name)
    gov_intLimG_k: Var = vf.add_var('gov.intLimG.k_' + template_name)
    gov_intLimG_limitsAtInit: Var = vf.add_var('gov.intLimG.limitsAtInit_' + template_name)
    gov_intLimG_outMax: Var = vf.add_var('gov.intLimG.outMax_' + template_name)
    gov_intLimG_outMin: Var = vf.add_var('gov.intLimG.outMin_' + template_name)
    gov_intLimG_strict: Var = vf.add_var('gov.intLimG.strict_' + template_name)
    gov_intLimG_use_reset: Var = vf.add_var('gov.intLimG.use_reset_' + template_name)
    gov_intLimG_use_set: Var = vf.add_var('gov.intLimG.use_set_' + template_name)
    gov_intLimG_y_start: Var = vf.add_var('gov.intLimG.y_start_' + template_name)
    gov_intTw_initType: Var = vf.add_var('gov.intTw.initType_' + template_name)
    gov_intTw_k: Var = vf.add_var('gov.intTw.k_' + template_name)
    gov_intTw_use_reset: Var = vf.add_var('gov.intTw.use_reset_' + template_name)
    gov_intTw_use_set: Var = vf.add_var('gov.intTw.use_set_' + template_name)
    gov_intTw_y_start: Var = vf.add_var('gov.intTw.y_start_' + template_name)
    gov_lagTp_T: Var = vf.add_var('gov.lagTp.T_' + template_name)
    gov_lagTp_initType: Var = vf.add_var('gov.lagTp.initType_' + template_name)
    gov_lagTp_k: Var = vf.add_var('gov.lagTp.k_' + template_name)
    gov_lagTp_y_start: Var = vf.add_var('gov.lagTp.y_start_' + template_name)
    gov_limitU_homotopyType: Var = vf.add_var('gov.limitU.homotopyType_' + template_name)
    gov_limitU_limitsAtInit: Var = vf.add_var('gov.limitU.limitsAtInit_' + template_name)
    gov_limitU_strict: Var = vf.add_var('gov.limitU.strict_' + template_name)
    gov_limitU_uMax: Var = vf.add_var('gov.limitU.uMax_' + template_name)
    gov_limitU_uMin: Var = vf.add_var('gov.limitU.uMin_' + template_name)
    gov_tG: Var = vf.add_var('gov.tG_' + template_name)
    gov_tP: Var = vf.add_var('gov.tP_' + template_name)
    gov_tR: Var = vf.add_var('gov.tR_' + template_name)
    gov_tW: Var = vf.add_var('gov.tW_' + template_name)
    gov_tableGvPgv_columns_1: Var = vf.add_var('gov.tableGvPgv.columns[1]_' + template_name)
    gov_tableGvPgv_extrapolation: Var = vf.add_var('gov.tableGvPgv.extrapolation_' + template_name)
    gov_tableGvPgv_fileName: Var = vf.add_var('gov.tableGvPgv.fileName_' + template_name)
    gov_tableGvPgv_nout: Var = vf.add_var('gov.tableGvPgv.nout_' + template_name)
    gov_tableGvPgv_smoothness: Var = vf.add_var('gov.tableGvPgv.smoothness_' + template_name)
    gov_tableGvPgv_tableID: Var = vf.add_var('gov.tableGvPgv.tableID_' + template_name)
    gov_tableGvPgv_tableName: Var = vf.add_var('gov.tableGvPgv.tableName_' + template_name)
    gov_tableGvPgv_tableOnFile: Var = vf.add_var('gov.tableGvPgv.tableOnFile_' + template_name)
    gov_tableGvPgv_table_1_1: Var = vf.add_var('gov.tableGvPgv.table[1,1]_' + template_name)
    gov_tableGvPgv_table_1_2: Var = vf.add_var('gov.tableGvPgv.table[1,2]_' + template_name)
    gov_tableGvPgv_table_2_1: Var = vf.add_var('gov.tableGvPgv.table[2,1]_' + template_name)
    gov_tableGvPgv_table_2_2: Var = vf.add_var('gov.tableGvPgv.table[2,2]_' + template_name)
    gov_tableGvPgv_table_3_1: Var = vf.add_var('gov.tableGvPgv.table[3,1]_' + template_name)
    gov_tableGvPgv_table_3_2: Var = vf.add_var('gov.tableGvPgv.table[3,2]_' + template_name)
    gov_tableGvPgv_table_4_1: Var = vf.add_var('gov.tableGvPgv.table[4,1]_' + template_name)
    gov_tableGvPgv_table_4_2: Var = vf.add_var('gov.tableGvPgv.table[4,2]_' + template_name)
    gov_tableGvPgv_table_5_1: Var = vf.add_var('gov.tableGvPgv.table[5,1]_' + template_name)
    gov_tableGvPgv_table_5_2: Var = vf.add_var('gov.tableGvPgv.table[5,2]_' + template_name)
    gov_tableGvPgv_table_6_1: Var = vf.add_var('gov.tableGvPgv.table[6,1]_' + template_name)
    gov_tableGvPgv_table_6_2: Var = vf.add_var('gov.tableGvPgv.table[6,2]_' + template_name)
    gov_tableGvPgv_table_7_1: Var = vf.add_var('gov.tableGvPgv.table[7,1]_' + template_name)
    gov_tableGvPgv_table_7_2: Var = vf.add_var('gov.tableGvPgv.table[7,2]_' + template_name)
    gov_tableGvPgv_u_max: Var = vf.add_var('gov.tableGvPgv.u_max_' + template_name)
    gov_tableGvPgv_u_min: Var = vf.add_var('gov.tableGvPgv.u_min_' + template_name)
    gov_tableGvPgv_verboseExtrapolation: Var = vf.add_var('gov.tableGvPgv.verboseExtrapolation_' + template_name)
    gov_tableGvPgv_verboseRead: Var = vf.add_var('gov.tableGvPgv.verboseRead_' + template_name)
    gov_tfRTemp_T: Var = vf.add_var('gov.tfRTemp.T_' + template_name)
    gov_tfRTemp_initType: Var = vf.add_var('gov.tfRTemp.initType_' + template_name)
    gov_tfRTemp_k: Var = vf.add_var('gov.tfRTemp.k_' + template_name)
    gov_tfRTemp_x_start: Var = vf.add_var('gov.tfRTemp.x_start_' + template_name)
    gov_tfRTemp_y_start: Var = vf.add_var('gov.tfRTemp.y_start_' + template_name)
    gov_tfRTemp_zeroGain: Var = vf.add_var('gov.tfRTemp.zeroGain_' + template_name)
    # Declare the state variables used by the template.
    gov_intLimG_y: Var = vf.add_var('gov.intLimG.y_' + template_name)
    gov_intTw_y: Var = vf.add_var('gov.intTw.y_' + template_name)
    gov_lagTp_y: Var = vf.add_var('gov.lagTp.y_' + template_name)
    gov_tfRTemp_x: Var = vf.add_var('gov.tfRTemp.x_' + template_name)
    # Declare the algebraic/shared variables used by the template.
    PRE_gov_dbPower_aux: Var = vf.add_var('$PRE.gov.dbPower.aux_' + template_name)
    PRE_gov_dbPower_h: Var = vf.add_var('$PRE.gov.dbPower.h_' + template_name)
    START_gov_dbPower_aux: Var = vf.add_var('$START.gov.dbPower.aux_' + template_name)
    START_gov_dbPower_h: Var = vf.add_var('$START.gov.dbPower.h_' + template_name)
    whenCondition1: Var = vf.add_var('$whenCondition1_' + template_name)
    whenCondition2: Var = vf.add_var('$whenCondition2_' + template_name)
    gov_PRefPu: Var = vf.add_var('gov.PRefPu_' + template_name)
    gov_PmPu: Var = vf.add_var('gov.PmPu_' + template_name)
    gov_addDeltaP_y: Var = vf.add_var('gov.addDeltaP.y_' + template_name)
    gov_addFeedback_y: Var = vf.add_var('gov.addFeedback.y_' + template_name)
    gov_addHDam_y: Var = vf.add_var('gov.addHDam.y_' + template_name)
    gov_addQnl_y: Var = vf.add_var('gov.addQnl.y_' + template_name)
    gov_dbOmega_y: Var = vf.add_var('gov.dbOmega.y_' + template_name)
    gov_dbPower_aux: Var = vf.add_var('gov.dbPower.aux_' + template_name)
    gov_dbPower_h: Var = vf.add_var('gov.dbPower.h_' + template_name)
    gov_deltaomega_y: Var = vf.add_var('gov.deltaomega.y_' + template_name)
    gov_division_y: Var = vf.add_var('gov.division.y_' + template_name)
    gov_gainATurb_y: Var = vf.add_var('gov.gainATurb.y_' + template_name)
    gov_gainDTurb_y: Var = vf.add_var('gov.gainDTurb.y_' + template_name)
    gov_gainRPerm_y: Var = vf.add_var('gov.gainRPerm.y_' + template_name)
    gov_gainTg_y: Var = vf.add_var('gov.gainTg.y_' + template_name)
    gov_intLimG_local_reset: Var = vf.add_var('gov.intLimG.local_reset_' + template_name)
    gov_intLimG_local_set: Var = vf.add_var('gov.intLimG.local_set_' + template_name)
    gov_intTw_local_reset: Var = vf.add_var('gov.intTw.local_reset_' + template_name)
    gov_intTw_local_set: Var = vf.add_var('gov.intTw.local_set_' + template_name)
    gov_limitU_simplifiedExpr: Var = vf.add_var('gov.limitU.simplifiedExpr_' + template_name)
    gov_limitU_y: Var = vf.add_var('gov.limitU.y_' + template_name)
    gov_omegaPu: Var = vf.add_var('gov.omegaPu_' + template_name)
    gov_omegaRefPu: Var = vf.add_var('gov.omegaRefPu_' + template_name)
    gov_prodDTurb_y: Var = vf.add_var('gov.prodDTurb.y_' + template_name)
    gov_prodH_y: Var = vf.add_var('gov.prodH.y_' + template_name)
    gov_prodSquare_y: Var = vf.add_var('gov.prodSquare.y_' + template_name)
    gov_tableGvPgv_y_1: Var = vf.add_var('gov.tableGvPgv.y[1]_' + template_name)
    gov_tfRTemp_u: Var = vf.add_var('gov.tfRTemp.u_' + template_name)
    gov_tfRTemp_y: Var = vf.add_var('gov.tfRTemp.y_' + template_name)
    # Declare the differential variables used by the template.
    d_gov_intLimG_y: Var = vf.add_diff_var('d_gov.intLimG.y_' + template_name, base_var=gov_intLimG_y)
    d_gov_intTw_y: Var = vf.add_diff_var('d_gov.intTw.y_' + template_name, base_var=gov_intTw_y)
    d_gov_lagTp_y: Var = vf.add_diff_var('d_gov.lagTp.y_' + template_name, base_var=gov_lagTp_y)
    d_gov_tfRTemp_x: Var = vf.add_diff_var('d_gov.tfRTemp.x_' + template_name, base_var=gov_tfRTemp_x)

    # Build explicit typed collections so the symbolic surface is easy to inspect.
    state_equations: list[Expr] = list()
    state_equations.append((((sym.Const(1.0) - ((sym.Const(1.0) - ((sym.heaviside(((gov_intLimG_outMin - gov_intLimG_y) - sym.Const(1e-06))) * sym.heaviside(((gov_intLimG_outMin - gov_intLimG_y) - sym.Const(1e-06)))) * sym.heaviside(((sym.Const(0.0) - (gov_intLimG_k * gov_limitU_y)) - sym.Const(1e-06))))) * (sym.Const(1.0) - ((((((sym.heaviside(((gov_intLimG_outMin - gov_intLimG_y) - sym.Const(1e-06))) * sym.heaviside(((sym.Const(0.0) - (gov_intLimG_k * gov_limitU_y)) - sym.Const(1e-06)))) * sym.heaviside(((gov_intLimG_y - gov_intLimG_outMax) - sym.Const(1e-06)))) * sym.heaviside(((gov_intLimG_outMin - gov_intLimG_y) - sym.Const(1e-06)))) * sym.heaviside(((sym.Const(0.0) - (gov_intLimG_k * gov_limitU_y)) - sym.Const(1e-06)))) * sym.heaviside(((gov_intLimG_y - gov_intLimG_outMax) - sym.Const(1e-06)))) * sym.heaviside((((gov_intLimG_k * gov_limitU_y) - sym.Const(0.0)) - sym.Const(1e-06))))))) * sym.Const(0.0)) + ((sym.Const(1.0) - (sym.Const(1.0) - ((sym.Const(1.0) - ((sym.heaviside(((gov_intLimG_outMin - gov_intLimG_y) - sym.Const(1e-06))) * sym.heaviside(((gov_intLimG_outMin - gov_intLimG_y) - sym.Const(1e-06)))) * sym.heaviside(((sym.Const(0.0) - (gov_intLimG_k * gov_limitU_y)) - sym.Const(1e-06))))) * (sym.Const(1.0) - ((((((sym.heaviside(((gov_intLimG_outMin - gov_intLimG_y) - sym.Const(1e-06))) * sym.heaviside(((sym.Const(0.0) - (gov_intLimG_k * gov_limitU_y)) - sym.Const(1e-06)))) * sym.heaviside(((gov_intLimG_y - gov_intLimG_outMax) - sym.Const(1e-06)))) * sym.heaviside(((gov_intLimG_outMin - gov_intLimG_y) - sym.Const(1e-06)))) * sym.heaviside(((sym.Const(0.0) - (gov_intLimG_k * gov_limitU_y)) - sym.Const(1e-06)))) * sym.heaviside(((gov_intLimG_y - gov_intLimG_outMax) - sym.Const(1e-06)))) * sym.heaviside((((gov_intLimG_k * gov_limitU_y) - sym.Const(0.0)) - sym.Const(1e-06)))))))) * (gov_intLimG_k * gov_limitU_y))))
    state_equations.append((gov_intTw_k * gov_addHDam_y))
    state_equations.append(((gov_tfRTemp_zeroGain * sym.Const(0.0)) + ((sym.Const(1.0) - gov_tfRTemp_zeroGain) * ((gov_tfRTemp_u - gov_tfRTemp_x) / gov_tfRTemp_T))))
    state_equations.append((((gov_lagTp_k * gov_addDeltaP_y) - gov_lagTp_y) / gov_lagTp_T))
    state_variables: list[Var] = list()
    state_variables.append(gov_intLimG_y)
    state_variables.append(gov_intTw_y)
    state_variables.append(gov_tfRTemp_x)
    state_variables.append(gov_lagTp_y)
    algebraic_equations: list[Expr] = list()
    algebraic_equations.append((gov_dbOmega_y - ((sym.heaviside(((gov_deltaomega_y - gov_dbOmega_UMax) - sym.Const(1e-06))) * ((gov_deltaomega_y - gov_dbOmega_UMax) + gov_dbOmega_EpsMax)) + ((sym.Const(1.0) - sym.heaviside(((gov_deltaomega_y - gov_dbOmega_UMax) - sym.Const(1e-06)))) * ((sym.heaviside(((gov_dbOmega_UMin - gov_deltaomega_y) - sym.Const(1e-06))) * ((gov_deltaomega_y - gov_dbOmega_UMin) + gov_dbOmega_EpsMin)) + ((sym.Const(1.0) - sym.heaviside(((gov_dbOmega_UMin - gov_deltaomega_y) - sym.Const(1e-06)))) * sym.Const(0.0)))))))
    algebraic_equations.append((gov_gainTg_y - (gov_gainTg_k * gov_lagTp_y)))
    algebraic_equations.append((gov_limitU_y - ((sym.heaviside(((gov_gainTg_y - gov_limitU_uMax) - sym.Const(1e-06))) * gov_limitU_uMax) + ((sym.Const(1.0) - sym.heaviside(((gov_gainTg_y - gov_limitU_uMax) - sym.Const(1e-06)))) * ((sym.heaviside(((gov_limitU_uMin - gov_gainTg_y) - sym.Const(1e-06))) * gov_limitU_uMin) + ((sym.Const(1.0) - sym.heaviside(((gov_limitU_uMin - gov_gainTg_y) - sym.Const(1e-06)))) * gov_gainTg_y))))))
    algebraic_equations.append(((whenCondition2 - sym.heaviside((((-gov_dbPower_Tolerance) - d_gov_intLimG_y) - sym.Const(1e-06)))) - sym.heaviside(((gov_intLimG_y - gov_dbPower_UHigh) + sym.Const(1e-06)))))
    algebraic_equations.append(((whenCondition1 - sym.heaviside(((d_gov_intLimG_y - gov_dbPower_Tolerance) - sym.Const(1e-06)))) - sym.heaviside(((gov_dbPower_ULow - gov_intLimG_y) + sym.Const(1e-06)))))
    algebraic_equations.append((gov_tfRTemp_u - (((gov_dbPower_h * sym.heaviside((((gov_dbPower_aux - gov_dbPower_UHigh) - gov_intLimG_y) + sym.Const(1e-06)))) * (gov_intLimG_y - gov_dbPower_ULow)) + ((sym.Const(1.0) - (gov_dbPower_h * sym.heaviside((((gov_dbPower_aux - gov_dbPower_UHigh) - gov_intLimG_y) + sym.Const(1e-06))))) * ((((sym.Const(1.0) - gov_dbPower_h) * sym.heaviside(((gov_intLimG_y - (gov_dbPower_aux - gov_dbPower_ULow)) + sym.Const(1e-06)))) * (gov_intLimG_y - gov_dbPower_UHigh)) + ((sym.Const(1.0) - ((sym.Const(1.0) - gov_dbPower_h) * sym.heaviside(((gov_intLimG_y - (gov_dbPower_aux - gov_dbPower_ULow)) + sym.Const(1e-06))))) * gov_dbPower_aux))))))
    algebraic_equations.append((gov_tableGvPgv_y_1 - ((((((((sym.Const(0.0) * sym.heaviside(((sym.Const(0.1) - gov_tfRTemp_u) - sym.Const(1e-06)))) + ((((((sym.Const(0.42) - sym.Const(0.0)) / (sym.Const(0.4) - sym.Const(0.1))) * gov_tfRTemp_u) + (sym.Const(0.0) - (((sym.Const(0.42) - sym.Const(0.0)) / (sym.Const(0.4) - sym.Const(0.1))) * sym.Const(0.1)))) * sym.heaviside(((gov_tfRTemp_u - sym.Const(0.1)) + sym.Const(1e-06)))) * sym.heaviside(((sym.Const(0.4) - gov_tfRTemp_u) - sym.Const(1e-06))))) + ((((((sym.Const(0.56) - sym.Const(0.42)) / (sym.Const(0.5) - sym.Const(0.4))) * gov_tfRTemp_u) + (sym.Const(0.42) - (((sym.Const(0.56) - sym.Const(0.42)) / (sym.Const(0.5) - sym.Const(0.4))) * sym.Const(0.4)))) * sym.heaviside(((gov_tfRTemp_u - sym.Const(0.4)) + sym.Const(1e-06)))) * sym.heaviside(((sym.Const(0.5) - gov_tfRTemp_u) - sym.Const(1e-06))))) + ((((((sym.Const(0.8) - sym.Const(0.56)) / (sym.Const(0.7) - sym.Const(0.5))) * gov_tfRTemp_u) + (sym.Const(0.56) - (((sym.Const(0.8) - sym.Const(0.56)) / (sym.Const(0.7) - sym.Const(0.5))) * sym.Const(0.5)))) * sym.heaviside(((gov_tfRTemp_u - sym.Const(0.5)) + sym.Const(1e-06)))) * sym.heaviside(((sym.Const(0.7) - gov_tfRTemp_u) - sym.Const(1e-06))))) + ((((((sym.Const(0.9) - sym.Const(0.8)) / (sym.Const(0.8) - sym.Const(0.7))) * gov_tfRTemp_u) + (sym.Const(0.8) - (((sym.Const(0.9) - sym.Const(0.8)) / (sym.Const(0.8) - sym.Const(0.7))) * sym.Const(0.7)))) * sym.heaviside(((gov_tfRTemp_u - sym.Const(0.7)) + sym.Const(1e-06)))) * sym.heaviside(((sym.Const(0.8) - gov_tfRTemp_u) - sym.Const(1e-06))))) + ((((((sym.Const(0.97) - sym.Const(0.9)) / (sym.Const(0.9) - sym.Const(0.8))) * gov_tfRTemp_u) + (sym.Const(0.9) - (((sym.Const(0.97) - sym.Const(0.9)) / (sym.Const(0.9) - sym.Const(0.8))) * sym.Const(0.8)))) * sym.heaviside(((gov_tfRTemp_u - sym.Const(0.8)) + sym.Const(1e-06)))) * sym.heaviside(((sym.Const(0.9) - gov_tfRTemp_u) - sym.Const(1e-06))))) + ((((((sym.Const(1.0) - sym.Const(0.97)) / (sym.Const(1.0) - sym.Const(0.9))) * gov_tfRTemp_u) + (sym.Const(0.97) - (((sym.Const(1.0) - sym.Const(0.97)) / (sym.Const(1.0) - sym.Const(0.9))) * sym.Const(0.9)))) * sym.heaviside(((gov_tfRTemp_u - sym.Const(0.9)) + sym.Const(1e-06)))) * sym.heaviside(((sym.Const(1.0) - gov_tfRTemp_u) - sym.Const(1e-06))))) + (sym.Const(1.0) * sym.heaviside(((gov_tfRTemp_u - sym.Const(1.0)) + sym.Const(1e-06)))))))
    algebraic_equations.append((gov_division_y - (gov_intTw_y / gov_tableGvPgv_y_1)))
    algebraic_equations.append((gov_prodSquare_y - (gov_division_y ** sym.Const(2.0))))
    algebraic_equations.append((gov_addHDam_y - ((gov_addHDam_k1 * gov_prodSquare_y) + (gov_addHDam_k2 * gov_const_k))))
    algebraic_equations.append((gov_gainRPerm_y - (gov_gainRPerm_k * gov_tfRTemp_u)))
    algebraic_equations.append((gov_prodDTurb_y - (gov_deltaomega_y * gov_tfRTemp_u)))
    algebraic_equations.append((gov_gainDTurb_y - (gov_gainDTurb_k * gov_prodDTurb_y)))
    algebraic_equations.append((gov_tfRTemp_y - ((gov_tfRTemp_zeroGain * sym.Const(0.0)) + ((sym.Const(1.0) - gov_tfRTemp_zeroGain) * ((gov_tfRTemp_k / gov_tfRTemp_T) * (gov_tfRTemp_u - gov_tfRTemp_x))))))
    algebraic_equations.append((gov_addFeedback_y - ((gov_addFeedback_k1 * gov_tfRTemp_y) + (gov_addFeedback_k2 * gov_gainRPerm_y))))
    algebraic_equations.append((gov_addDeltaP_y - (((gov_addDeltaP_k1 * gov_PRefPu) + (gov_addDeltaP_k2 * gov_dbOmega_y)) + (gov_addDeltaP_k3 * gov_addFeedback_y))))
    algebraic_equations.append((gov_addQnl_y - ((gov_addQnl_k1 * gov_intTw_y) + (gov_addQnl_k2 * gov_constant1_k))))
    algebraic_equations.append((gov_prodH_y - (gov_prodSquare_y * gov_addQnl_y)))
    algebraic_equations.append((gov_gainATurb_y - (gov_gainATurb_k * gov_prodH_y)))
    algebraic_equations.append((gov_PmPu - ((gov_addPm_k1 * gov_gainDTurb_y) + (gov_addPm_k2 * gov_gainATurb_y))))
    algebraic_equations.append((gov_dbPower_aux - (gov_intLimG_y - gov_dbPower_ULow)))
    algebraic_equations.append((gov_dbPower_h - sym.Const(0.0)))
    algebraic_variables: list[Var] = list()
    algebraic_variables.append(gov_dbOmega_y)
    algebraic_variables.append(gov_gainTg_y)
    algebraic_variables.append(gov_limitU_y)
    algebraic_variables.append(whenCondition2)
    algebraic_variables.append(whenCondition1)
    algebraic_variables.append(gov_tfRTemp_u)
    algebraic_variables.append(gov_tableGvPgv_y_1)
    algebraic_variables.append(gov_division_y)
    algebraic_variables.append(gov_prodSquare_y)
    algebraic_variables.append(gov_addHDam_y)
    algebraic_variables.append(gov_gainRPerm_y)
    algebraic_variables.append(gov_prodDTurb_y)
    algebraic_variables.append(gov_gainDTurb_y)
    algebraic_variables.append(gov_tfRTemp_y)
    algebraic_variables.append(gov_addFeedback_y)
    algebraic_variables.append(gov_addDeltaP_y)
    algebraic_variables.append(gov_addQnl_y)
    algebraic_variables.append(gov_prodH_y)
    algebraic_variables.append(gov_gainATurb_y)
    algebraic_variables.append(gov_PmPu)
    algebraic_variables.append(gov_dbPower_aux)
    algebraic_variables.append(gov_dbPower_h)
    algebraic_variables.append(gov_deltaomega_y)
    algebraic_variables.append(gov_PRefPu)
    algebraic_variables.append(gov_omegaPu)
    algebraic_variables.append(gov_omegaRefPu)
    algebraic_variables.append(gov_intLimG_local_reset)
    algebraic_variables.append(gov_intLimG_local_set)
    algebraic_variables.append(gov_intTw_local_reset)
    algebraic_variables.append(gov_intTw_local_set)
    algebraic_variables.append(gov_limitU_simplifiedExpr)
    algebraic_variables.append(PRE_gov_dbPower_aux)
    algebraic_variables.append(START_gov_dbPower_aux)
    algebraic_variables.append(PRE_gov_dbPower_h)
    algebraic_variables.append(START_gov_dbPower_h)
    differential_variables: list[Var] = list()
    differential_variables.append(d_gov_intLimG_y)
    differential_variables.append(d_gov_intTw_y)
    differential_variables.append(d_gov_tfRTemp_x)
    differential_variables.append(d_gov_lagTp_y)
    input_variables: list[Var] = list()
    output_variables: list[Var] = list()
    event_parameters: dict[Var, Expr | Const] = dict()
    event_parameters[gov_ATurb] = vf.add_const(1.2, name='')
    event_parameters[gov_CustomTable_1_1] = vf.add_const(0.1, name='')
    event_parameters[gov_CustomTable_1_2] = vf.add_const(0.0, name='')
    event_parameters[gov_CustomTable_2_1] = vf.add_const(0.4, name='')
    event_parameters[gov_CustomTable_2_2] = vf.add_const(0.42, name='')
    event_parameters[gov_CustomTable_3_1] = vf.add_const(0.5, name='')
    event_parameters[gov_CustomTable_3_2] = vf.add_const(0.56, name='')
    event_parameters[gov_CustomTable_4_1] = vf.add_const(0.7, name='')
    event_parameters[gov_CustomTable_4_2] = vf.add_const(0.8, name='')
    event_parameters[gov_CustomTable_5_1] = vf.add_const(0.8, name='')
    event_parameters[gov_CustomTable_5_2] = vf.add_const(0.9, name='')
    event_parameters[gov_CustomTable_6_1] = vf.add_const(0.9, name='')
    event_parameters[gov_CustomTable_6_2] = vf.add_const(0.97, name='')
    event_parameters[gov_CustomTable_7_1] = vf.add_const(1.0, name='')
    event_parameters[gov_CustomTable_7_2] = vf.add_const(1.0, name='')
    event_parameters[gov_DTurb] = vf.add_const(1.1, name='')
    event_parameters[gov_DeltaOmegaDbPu] = vf.add_const(0.0, name='')
    event_parameters[gov_DeltaOmegaEpsPu] = vf.add_const(0.0, name='')
    event_parameters[gov_DeltaPDbPu] = vf.add_const(0.0, name='')
    event_parameters[gov_FrancisPeltonTable_1_1] = vf.add_const(0.1, name='')
    event_parameters[gov_FrancisPeltonTable_1_2] = vf.add_const(0.0, name='')
    event_parameters[gov_FrancisPeltonTable_2_1] = vf.add_const(0.4, name='')
    event_parameters[gov_FrancisPeltonTable_2_2] = vf.add_const(0.42, name='')
    event_parameters[gov_FrancisPeltonTable_3_1] = vf.add_const(0.5, name='')
    event_parameters[gov_FrancisPeltonTable_3_2] = vf.add_const(0.56, name='')
    event_parameters[gov_FrancisPeltonTable_4_1] = vf.add_const(0.7, name='')
    event_parameters[gov_FrancisPeltonTable_4_2] = vf.add_const(0.8, name='')
    event_parameters[gov_FrancisPeltonTable_5_1] = vf.add_const(0.8, name='')
    event_parameters[gov_FrancisPeltonTable_5_2] = vf.add_const(0.9, name='')
    event_parameters[gov_FrancisPeltonTable_6_1] = vf.add_const(0.9, name='')
    event_parameters[gov_FrancisPeltonTable_6_2] = vf.add_const(0.97, name='')
    event_parameters[gov_FrancisPeltonTable_7_1] = vf.add_const(1.0, name='')
    event_parameters[gov_FrancisPeltonTable_7_2] = vf.add_const(1.0, name='')
    event_parameters[gov_GMax] = vf.add_const(1.0, name='')
    event_parameters[gov_GMin] = vf.add_const(0.0, name='')
    event_parameters[gov_HDam] = vf.add_const(1.0, name='')
    event_parameters[gov_InitSet] = vf.add_const(0.5888888888888889, name='')
    event_parameters[gov_KaplanTable_1_1] = vf.add_const(0.1, name='')
    event_parameters[gov_KaplanTable_1_2] = vf.add_const(0.0, name='')
    event_parameters[gov_KaplanTable_2_1] = vf.add_const(0.4, name='')
    event_parameters[gov_KaplanTable_2_2] = vf.add_const(0.35, name='')
    event_parameters[gov_KaplanTable_3_1] = vf.add_const(0.5, name='')
    event_parameters[gov_KaplanTable_3_2] = vf.add_const(0.468, name='')
    event_parameters[gov_KaplanTable_4_1] = vf.add_const(0.7, name='')
    event_parameters[gov_KaplanTable_4_2] = vf.add_const(0.796, name='')
    event_parameters[gov_KaplanTable_5_1] = vf.add_const(0.8, name='')
    event_parameters[gov_KaplanTable_5_2] = vf.add_const(0.917, name='')
    event_parameters[gov_KaplanTable_6_1] = vf.add_const(0.9, name='')
    event_parameters[gov_KaplanTable_6_2] = vf.add_const(0.99, name='')
    event_parameters[gov_KaplanTable_7_1] = vf.add_const(1.0, name='')
    event_parameters[gov_KaplanTable_7_2] = vf.add_const(1.0, name='')
    event_parameters[gov_Lookuptab_1_1] = vf.add_const(0.1, name='')
    event_parameters[gov_Lookuptab_1_2] = vf.add_const(0.0, name='')
    event_parameters[gov_Lookuptab_2_1] = vf.add_const(0.4, name='')
    event_parameters[gov_Lookuptab_2_2] = vf.add_const(0.42, name='')
    event_parameters[gov_Lookuptab_3_1] = vf.add_const(0.5, name='')
    event_parameters[gov_Lookuptab_3_2] = vf.add_const(0.56, name='')
    event_parameters[gov_Lookuptab_4_1] = vf.add_const(0.7, name='')
    event_parameters[gov_Lookuptab_4_2] = vf.add_const(0.8, name='')
    event_parameters[gov_Lookuptab_5_1] = vf.add_const(0.8, name='')
    event_parameters[gov_Lookuptab_5_2] = vf.add_const(0.9, name='')
    event_parameters[gov_Lookuptab_6_1] = vf.add_const(0.9, name='')
    event_parameters[gov_Lookuptab_6_2] = vf.add_const(0.97, name='')
    event_parameters[gov_Lookuptab_7_1] = vf.add_const(1.0, name='')
    event_parameters[gov_Lookuptab_7_2] = vf.add_const(1.0, name='')
    event_parameters[gov_PRef0Pu] = (gov_InitSet * gov_RPerm)
    event_parameters[gov_Pm0Pu] = vf.add_const(0.8, name='')
    event_parameters[gov_QNl] = vf.add_const(0.0, name='')
    event_parameters[gov_RPerm] = vf.add_const(0.05, name='')
    event_parameters[gov_RTemp] = vf.add_const(0.3, name='')
    event_parameters[gov_SimpleTable_1_1] = vf.add_const(0.0, name='')
    event_parameters[gov_SimpleTable_1_2] = vf.add_const(0.0, name='')
    event_parameters[gov_SimpleTable_2_1] = vf.add_const(1.0, name='')
    event_parameters[gov_SimpleTable_2_2] = vf.add_const(1.0, name='')
    event_parameters[gov_UC] = vf.add_const(-0.2, name='')
    event_parameters[gov_UO] = vf.add_const(0.2, name='')
    event_parameters[gov_addDeltaOmega_k1] = vf.add_const(-1.0, name='')
    event_parameters[gov_addDeltaOmega_k2] = vf.add_const(1.0, name='')
    event_parameters[gov_addDeltaP_k1] = vf.add_const(1.0, name='')
    event_parameters[gov_addDeltaP_k2] = vf.add_const(-1.0, name='')
    event_parameters[gov_addDeltaP_k3] = vf.add_const(-1.0, name='')
    event_parameters[gov_addFeedback_k1] = vf.add_const(1.0, name='')
    event_parameters[gov_addFeedback_k2] = vf.add_const(1.0, name='')
    event_parameters[gov_addHDam_k1] = vf.add_const(-1.0, name='')
    event_parameters[gov_addHDam_k2] = vf.add_const(1.0, name='')
    event_parameters[gov_addPm_k1] = vf.add_const(-1.0, name='')
    event_parameters[gov_addPm_k2] = vf.add_const(1.0, name='')
    event_parameters[gov_addQnl_k1] = vf.add_const(1.0, name='')
    event_parameters[gov_addQnl_k2] = vf.add_const(-1.0, name='')
    event_parameters[gov_const_k] = gov_HDam
    event_parameters[gov_constant1_k] = gov_QNl
    event_parameters[gov_dbOmega_EpsMax] = gov_DeltaOmegaEpsPu
    event_parameters[gov_dbOmega_EpsMin] = (-gov_dbOmega_EpsMax)
    event_parameters[gov_dbOmega_UMax] = gov_DeltaOmegaDbPu
    event_parameters[gov_dbOmega_UMin] = (-gov_dbOmega_UMax)
    event_parameters[gov_dbPower_Aux0] = ((gov_dbPower_H0 * (((gov_dbPower_U0 - gov_dbPower_UHigh) * sym.heaviside(((gov_dbPower_U0 - gov_dbPower_UHigh) - sym.Const(0.0)))) + (sym.Const(0.0) * (sym.Const(1) - sym.heaviside(((gov_dbPower_U0 - gov_dbPower_UHigh) - sym.Const(0.0))))))) + ((sym.Const(1.0) - gov_dbPower_H0) * (((gov_dbPower_U0 - gov_dbPower_ULow) * sym.heaviside((sym.Const(0.0) - (gov_dbPower_U0 - gov_dbPower_ULow)))) + (sym.Const(0.0) * (sym.Const(1) - sym.heaviside((sym.Const(0.0) - (gov_dbPower_U0 - gov_dbPower_ULow))))))))
    event_parameters[gov_dbPower_Tolerance] = vf.add_const(1e-05, name='')
    event_parameters[gov_dbPower_U0] = gov_InitSet
    event_parameters[gov_dbPower_UHigh] = gov_DeltaPDbPu
    event_parameters[gov_dbPower_ULow] = (-gov_dbPower_UHigh)
    event_parameters[gov_gainATurb_k] = gov_ATurb
    event_parameters[gov_gainDTurb_k] = gov_DTurb
    event_parameters[gov_gainRPerm_k] = gov_RPerm
    event_parameters[gov_gainTg_k] = (sym.Const(1.0) / gov_tG)
    event_parameters[gov_intLimG_k] = vf.add_const(1.0, name='')
    event_parameters[gov_intLimG_outMax] = gov_GMax
    event_parameters[gov_intLimG_outMin] = gov_GMin
    event_parameters[gov_intLimG_y_start] = gov_InitSet
    event_parameters[gov_intTw_k] = (sym.Const(1.0) / gov_tW)
    event_parameters[gov_intTw_y_start] = ((gov_Pm0Pu / (gov_HDam * gov_ATurb)) + gov_QNl)
    event_parameters[gov_lagTp_T] = gov_tP
    event_parameters[gov_lagTp_k] = vf.add_const(1.0, name='')
    event_parameters[gov_lagTp_y_start] = vf.add_const(0.0, name='')
    event_parameters[gov_limitU_uMax] = gov_UO
    event_parameters[gov_limitU_uMin] = gov_UC
    event_parameters[gov_tG] = vf.add_const(0.5, name='')
    event_parameters[gov_tP] = vf.add_const(0.1, name='')
    event_parameters[gov_tR] = vf.add_const(5.0, name='')
    event_parameters[gov_tW] = vf.add_const(1.0, name='')
    event_parameters[gov_tableGvPgv_table_1_1] = vf.add_const(0.1, name='')
    event_parameters[gov_tableGvPgv_table_1_2] = vf.add_const(0.0, name='')
    event_parameters[gov_tableGvPgv_table_2_1] = vf.add_const(0.4, name='')
    event_parameters[gov_tableGvPgv_table_2_2] = vf.add_const(0.42, name='')
    event_parameters[gov_tableGvPgv_table_3_1] = vf.add_const(0.5, name='')
    event_parameters[gov_tableGvPgv_table_3_2] = vf.add_const(0.56, name='')
    event_parameters[gov_tableGvPgv_table_4_1] = vf.add_const(0.7, name='')
    event_parameters[gov_tableGvPgv_table_4_2] = vf.add_const(0.8, name='')
    event_parameters[gov_tableGvPgv_table_5_1] = vf.add_const(0.8, name='')
    event_parameters[gov_tableGvPgv_table_5_2] = vf.add_const(0.9, name='')
    event_parameters[gov_tableGvPgv_table_6_1] = vf.add_const(0.9, name='')
    event_parameters[gov_tableGvPgv_table_6_2] = vf.add_const(0.97, name='')
    event_parameters[gov_tableGvPgv_table_7_1] = vf.add_const(1.0, name='')
    event_parameters[gov_tableGvPgv_table_7_2] = vf.add_const(1.0, name='')
    event_parameters[gov_tableGvPgv_u_max] = vf.add_const(1.0, name='')
    event_parameters[gov_tableGvPgv_u_min] = vf.add_const(0.1, name='')
    event_parameters[gov_tfRTemp_T] = gov_tR
    event_parameters[gov_tfRTemp_k] = (gov_RTemp * gov_tR)
    event_parameters[gov_tfRTemp_x_start] = gov_InitSet
    event_parameters[gov_tfRTemp_y_start] = vf.add_const(0.0, name='')
    event_parameters[gov_ModelInt] = vf.add_const(1.0, name='')
    event_parameters[gov_intLimG_initType] = vf.add_const(3.0, name='')
    event_parameters[gov_intTw_initType] = vf.add_const(3.0, name='')
    event_parameters[gov_lagTp_initType] = vf.add_const(1.0, name='')
    event_parameters[gov_limitU_homotopyType] = vf.add_const(1.0, name='')
    event_parameters[gov_tableGvPgv_columns_1] = vf.add_const(2.0, name='')
    event_parameters[gov_tableGvPgv_extrapolation] = vf.add_const(2.0, name='')
    event_parameters[gov_tableGvPgv_nout] = vf.add_const(1.0, name='')
    event_parameters[gov_tableGvPgv_smoothness] = vf.add_const(1.0, name='')
    event_parameters[gov_tfRTemp_initType] = vf.add_const(3.0, name='')
    event_parameters[gov_Sel] = vf.add_const(0.0, name='')
    event_parameters[gov_dbPower_H0] = vf.add_const(0.0, name='')
    event_parameters[gov_intLimG_limitsAtInit] = vf.add_const(1.0, name='')
    event_parameters[gov_intLimG_strict] = vf.add_const(0.0, name='')
    event_parameters[gov_intLimG_use_reset] = vf.add_const(0.0, name='')
    event_parameters[gov_intLimG_use_set] = vf.add_const(0.0, name='')
    event_parameters[gov_intTw_use_reset] = vf.add_const(0.0, name='')
    event_parameters[gov_intTw_use_set] = vf.add_const(0.0, name='')
    event_parameters[gov_limitU_limitsAtInit] = vf.add_const(1.0, name='')
    event_parameters[gov_limitU_strict] = vf.add_const(0.0, name='')
    event_parameters[gov_tableGvPgv_tableOnFile] = vf.add_const(0.0, name='')
    event_parameters[gov_tableGvPgv_verboseExtrapolation] = vf.add_const(0.0, name='')
    event_parameters[gov_tableGvPgv_verboseRead] = vf.add_const(1.0, name='')
    event_parameters[gov_tfRTemp_zeroGain] = sym.heaviside(((sym.Const(2.220446049250313e-16) - sym.abs(gov_tfRTemp_k)) - sym.Const(1e-06)))
    event_parameters[gov_tableGvPgv_fileName] = vf.add_const(0.0, name='')
    event_parameters[gov_tableGvPgv_tableName] = vf.add_const(0.0, name='')
    event_parameters[gov_tableGvPgv_tableID] = vf.add_const(0.0, name='')
    mode_parameters: dict[Var, Expr | Const] = dict()
    initial_equations: dict[Var, Expr | Const] = dict()
    initial_equations[gov_intLimG_y] = gov_intLimG_y_start
    initial_equations[gov_intTw_y] = gov_intTw_y_start
    initial_equations[gov_lagTp_y] = gov_lagTp_y_start
    initial_equations[gov_tfRTemp_x] = gov_tfRTemp_x_start
    initial_equations[gov_PRefPu] = gov_PRef0Pu
    initial_equations[gov_PmPu] = vf.add_const(0.8, name='')
    initial_equations[gov_omegaPu] = vf.add_const(1.0, name='')
    initial_equations[gov_omegaRefPu] = vf.add_const(1.0, name='')
    initial_equations[gov_tfRTemp_y] = vf.add_const(0.0, name='')
    initial_equations[gov_dbPower_aux] = PRE_gov_dbPower_aux
    initial_equations[gov_dbPower_h] = PRE_gov_dbPower_h
    initial_equations[gov_intLimG_local_reset] = vf.add_const(0.0, name='')
    initial_equations[gov_intLimG_local_set] = vf.add_const(0.0, name='')
    initial_equations[gov_intTw_local_reset] = vf.add_const(0.0, name='')
    initial_equations[gov_intTw_local_set] = vf.add_const(0.0, name='')
    initial_equations[gov_limitU_simplifiedExpr] = vf.add_const(0.0, name='')
    initial_equations[PRE_gov_dbPower_aux] = START_gov_dbPower_aux
    initial_equations[PRE_gov_dbPower_h] = START_gov_dbPower_h
    initial_equations[gov_deltaomega_y] = (gov_addDeltaOmega_k1 + gov_addDeltaOmega_k2)
    initial_equations[gov_tfRTemp_u] = (((PRE_gov_dbPower_h * sym.heaviside((((PRE_gov_dbPower_aux - gov_dbPower_UHigh) - gov_intLimG_y) + sym.Const(1e-06)))) * (gov_intLimG_y - gov_dbPower_ULow)) + ((sym.Const(1.0) - (PRE_gov_dbPower_h * sym.heaviside((((PRE_gov_dbPower_aux - gov_dbPower_UHigh) - gov_intLimG_y) + sym.Const(1e-06))))) * ((((sym.Const(1.0) - PRE_gov_dbPower_h) * sym.heaviside(((gov_intLimG_y - (PRE_gov_dbPower_aux - gov_dbPower_ULow)) + sym.Const(1e-06)))) * (gov_intLimG_y - gov_dbPower_UHigh)) + ((sym.Const(1.0) - ((sym.Const(1.0) - PRE_gov_dbPower_h) * sym.heaviside(((gov_intLimG_y - (PRE_gov_dbPower_aux - gov_dbPower_ULow)) + sym.Const(1e-06))))) * PRE_gov_dbPower_aux))))
    initial_equations[whenCondition1] = (sym.heaviside(((d_gov_intLimG_y - gov_dbPower_Tolerance) - sym.Const(1e-06))) + sym.heaviside(((gov_dbPower_ULow - gov_intLimG_y) + sym.Const(1e-06))))
    initial_equations[whenCondition2] = (sym.heaviside((((-gov_dbPower_Tolerance) - d_gov_intLimG_y) - sym.Const(1e-06))) + sym.heaviside(((gov_intLimG_y - gov_dbPower_UHigh) + sym.Const(1e-06))))
    initial_equations[gov_addDeltaP_y] = (((gov_addDeltaP_k1 * gov_PRefPu) + (gov_addDeltaP_k2 * gov_dbOmega_y)) + (gov_addDeltaP_k3 * gov_addFeedback_y))
    differential_initial_equations: dict[Var, Expr | Const] = dict()
    procedural_logic_entries: list[object] = list()

    # Assemble the final block from the explicit typed collections above.
    template.block = Block(
        state_vars=state_variables,
        state_eqs=state_equations,
        algebraic_vars=algebraic_variables,
        algebraic_eqs=algebraic_equations,
        diff_vars=differential_variables,
        init_eqs=initial_equations,
        diff_init_eqs=differential_initial_equations,
        in_vars=input_variables,
        out_vars=output_variables,
        event_dict=event_parameters,
        mode_dict=mode_parameters,
        procedural_logic=procedural_logic_entries,
        name=template_name,
    )

    template.comment = 'Generator hydro governor GOVHYDRO4'
    return template
