# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
# SPDX-License-Identifier: MPL-2.0

"""
Maintainable international-standard module for 'REECB'.

This is the runtime implementation shipped by VeraGrid.
It exposes the imported public interface, explicit symbolic equations, and
"""

from __future__ import annotations

from VeraGridEngine.Devices.Dynamic.rms_template import RmsModelTemplate
from VeraGridEngine.Devices.Dynamic.var_factory import VarFactory
from VeraGridEngine.Utils.Symbolic.block import Block
import VeraGridEngine.Utils.Symbolic.symbolic as sym
from VeraGridEngine.enumerations import DeviceType
from VeraGridEngine.Utils.Symbolic.symbolic import Var
from VeraGridEngine.Utils.Symbolic.symbolic import Expr
from VeraGridEngine.Utils.Symbolic.symbolic import Const
from VeraGridEngine.Utils.Symbolic.symbolic import BinOp

def build_reecb_template(vf: VarFactory, name: str | None = None) -> RmsModelTemplate:
    """
    Materialize the international-standard EMT template.

    :param vf: Variable factory used to allocate the symbolic surface.
    :param name: Optional explicit runtime template name.
    :returns: Materialized EMT template.
    """
    template_name: str
    if name is None:
        template_name: str = 'REECB'
    else:
        template_name: str = name

    # Allocate the template container before building the symbolic surface.
    template: RmsModelTemplate = RmsModelTemplate()
    template.tpe = DeviceType.GeneratorDevice
    template.name = template_name

    # Declare every variable explicitly before the equations reference it.
    # Declare the runtime parameter variables used by the template.
    ctrl_DPMaxPu: Var = vf.add_var('ctrl.DPMaxPu_' + template_name)
    ctrl_DPMinPu: Var = vf.add_var('ctrl.DPMinPu_' + template_name)
    ctrl_Dbd1Pu: Var = vf.add_var('ctrl.Dbd1Pu_' + template_name)
    ctrl_Dbd2Pu: Var = vf.add_var('ctrl.Dbd2Pu_' + template_name)
    ctrl_IMaxPu: Var = vf.add_var('ctrl.IMaxPu_' + template_name)
    ctrl_Id0Pu: Var = vf.add_var('ctrl.Id0Pu_' + template_name)
    ctrl_Iq0Pu: Var = vf.add_var('ctrl.Iq0Pu_' + template_name)
    ctrl_Iqh1Pu: Var = vf.add_var('ctrl.Iqh1Pu_' + template_name)
    ctrl_Iql1Pu: Var = vf.add_var('ctrl.Iql1Pu_' + template_name)
    ctrl_Kqi: Var = vf.add_var('ctrl.Kqi_' + template_name)
    ctrl_Kqp: Var = vf.add_var('ctrl.Kqp_' + template_name)
    ctrl_Kqv: Var = vf.add_var('ctrl.Kqv_' + template_name)
    ctrl_Kvi: Var = vf.add_var('ctrl.Kvi_' + template_name)
    ctrl_Kvp: Var = vf.add_var('ctrl.Kvp_' + template_name)
    ctrl_PF0: Var = vf.add_var('ctrl.PF0_' + template_name)
    ctrl_PInj0Pu: Var = vf.add_var('ctrl.PInj0Pu_' + template_name)
    ctrl_PMaxPu: Var = vf.add_var('ctrl.PMaxPu_' + template_name)
    ctrl_PMinPu: Var = vf.add_var('ctrl.PMinPu_' + template_name)
    ctrl_PQFlag: Var = vf.add_var('ctrl.PQFlag_' + template_name)
    ctrl_PfFlag: Var = vf.add_var('ctrl.PfFlag_' + template_name)
    ctrl_PfFlag0_k: Var = vf.add_var('ctrl.PfFlag0.k_' + template_name)
    ctrl_QFlag: Var = vf.add_var('ctrl.QFlag_' + template_name)
    ctrl_QFlag0_k: Var = vf.add_var('ctrl.QFlag0.k_' + template_name)
    ctrl_QInj0Pu: Var = vf.add_var('ctrl.QInj0Pu_' + template_name)
    ctrl_QMaxPu: Var = vf.add_var('ctrl.QMaxPu_' + template_name)
    ctrl_QMinPu: Var = vf.add_var('ctrl.QMinPu_' + template_name)
    ctrl_UInj0Pu: Var = vf.add_var('ctrl.UInj0Pu_' + template_name)
    ctrl_VDipPu: Var = vf.add_var('ctrl.VDipPu_' + template_name)
    ctrl_VFlag: Var = vf.add_var('ctrl.VFlag_' + template_name)
    ctrl_VFlag0_k: Var = vf.add_var('ctrl.VFlag0.k_' + template_name)
    ctrl_VMaxPu: Var = vf.add_var('ctrl.VMaxPu_' + template_name)
    ctrl_VMinPu: Var = vf.add_var('ctrl.VMinPu_' + template_name)
    ctrl_VRef0Pu: Var = vf.add_var('ctrl.VRef0Pu_' + template_name)
    ctrl_VRef1Pu: Var = vf.add_var('ctrl.VRef1Pu_' + template_name)
    ctrl_VRefConst_k: Var = vf.add_var('ctrl.VRefConst.k_' + template_name)
    ctrl_VRefConst1_k: Var = vf.add_var('ctrl.VRefConst1.k_' + template_name)
    ctrl_VUpPu: Var = vf.add_var('ctrl.VUpPu_' + template_name)
    ctrl_add_k1: Var = vf.add_var('ctrl.add.k1_' + template_name)
    ctrl_add_k2: Var = vf.add_var('ctrl.add.k2_' + template_name)
    ctrl_add1_k1: Var = vf.add_var('ctrl.add1.k1_' + template_name)
    ctrl_add1_k2: Var = vf.add_var('ctrl.add1.k2_' + template_name)
    ctrl_add2_k1: Var = vf.add_var('ctrl.add2.k1_' + template_name)
    ctrl_add2_k2: Var = vf.add_var('ctrl.add2.k2_' + template_name)
    ctrl_constant2_k: Var = vf.add_var('ctrl.constant2.k_' + template_name)
    ctrl_currentLimitsCalculation1_IMaxPu: Var = vf.add_var('ctrl.currentLimitsCalculation1.IMaxPu_' + template_name)
    ctrl_currentLimitsCalculation1_PQFlag: Var = vf.add_var('ctrl.currentLimitsCalculation1.PQFlag_' + template_name)
    ctrl_deadZone_deadZoneAtInit: Var = vf.add_var('ctrl.deadZone.deadZoneAtInit_' + template_name)
    ctrl_deadZone_uMax: Var = vf.add_var('ctrl.deadZone.uMax_' + template_name)
    ctrl_deadZone_uMin: Var = vf.add_var('ctrl.deadZone.uMin_' + template_name)
    ctrl_firstOrder_T: Var = vf.add_var('ctrl.firstOrder.T_' + template_name)
    ctrl_firstOrder_initType: Var = vf.add_var('ctrl.firstOrder.initType_' + template_name)
    ctrl_firstOrder_k: Var = vf.add_var('ctrl.firstOrder.k_' + template_name)
    ctrl_firstOrder_y_start: Var = vf.add_var('ctrl.firstOrder.y_start_' + template_name)
    ctrl_firstOrder1_T: Var = vf.add_var('ctrl.firstOrder1.T_' + template_name)
    ctrl_firstOrder1_initType: Var = vf.add_var('ctrl.firstOrder1.initType_' + template_name)
    ctrl_firstOrder1_k: Var = vf.add_var('ctrl.firstOrder1.k_' + template_name)
    ctrl_firstOrder1_y_start: Var = vf.add_var('ctrl.firstOrder1.y_start_' + template_name)
    ctrl_firstOrder2_T: Var = vf.add_var('ctrl.firstOrder2.T_' + template_name)
    ctrl_firstOrder2_initType: Var = vf.add_var('ctrl.firstOrder2.initType_' + template_name)
    ctrl_firstOrder2_k: Var = vf.add_var('ctrl.firstOrder2.k_' + template_name)
    ctrl_firstOrder2_y_start: Var = vf.add_var('ctrl.firstOrder2.y_start_' + template_name)
    ctrl_firstOrder3_T: Var = vf.add_var('ctrl.firstOrder3.T_' + template_name)
    ctrl_firstOrder3_initType: Var = vf.add_var('ctrl.firstOrder3.initType_' + template_name)
    ctrl_firstOrder3_k: Var = vf.add_var('ctrl.firstOrder3.k_' + template_name)
    ctrl_firstOrder3_y_start: Var = vf.add_var('ctrl.firstOrder3.y_start_' + template_name)
    ctrl_gain_k: Var = vf.add_var('ctrl.gain.k_' + template_name)
    ctrl_limPIDFreeze_FFzero_k: Var = vf.add_var('ctrl.limPIDFreeze.FFzero.k_' + template_name)
    ctrl_limPIDFreeze_I_K: Var = vf.add_var('ctrl.limPIDFreeze.I.K_' + template_name)
    ctrl_limPIDFreeze_I_UseFreeze: Var = vf.add_var('ctrl.limPIDFreeze.I.UseFreeze_' + template_name)
    ctrl_limPIDFreeze_I_UseReset: Var = vf.add_var('ctrl.limPIDFreeze.I.UseReset_' + template_name)
    ctrl_limPIDFreeze_I_UseSet: Var = vf.add_var('ctrl.limPIDFreeze.I.UseSet_' + template_name)
    ctrl_limPIDFreeze_I_Y0: Var = vf.add_var('ctrl.limPIDFreeze.I.Y0_' + template_name)
    ctrl_limPIDFreeze_K: Var = vf.add_var('ctrl.limPIDFreeze.K_' + template_name)
    ctrl_limPIDFreeze_Kff: Var = vf.add_var('ctrl.limPIDFreeze.Kff_' + template_name)
    ctrl_limPIDFreeze_Ni: Var = vf.add_var('ctrl.limPIDFreeze.Ni_' + template_name)
    ctrl_limPIDFreeze_P_k: Var = vf.add_var('ctrl.limPIDFreeze.P.k_' + template_name)
    ctrl_limPIDFreeze_Strict: Var = vf.add_var('ctrl.limPIDFreeze.Strict_' + template_name)
    ctrl_limPIDFreeze_Ti: Var = vf.add_var('ctrl.limPIDFreeze.Ti_' + template_name)
    ctrl_limPIDFreeze_WithFeedForward: Var = vf.add_var('ctrl.limPIDFreeze.WithFeedForward_' + template_name)
    ctrl_limPIDFreeze_Wp: Var = vf.add_var('ctrl.limPIDFreeze.Wp_' + template_name)
    ctrl_limPIDFreeze_Xi0: Var = vf.add_var('ctrl.limPIDFreeze.Xi0_' + template_name)
    ctrl_limPIDFreeze_Y0: Var = vf.add_var('ctrl.limPIDFreeze.Y0_' + template_name)
    ctrl_limPIDFreeze_YMax: Var = vf.add_var('ctrl.limPIDFreeze.YMax_' + template_name)
    ctrl_limPIDFreeze_YMin: Var = vf.add_var('ctrl.limPIDFreeze.YMin_' + template_name)
    ctrl_limPIDFreeze_addFF_k1: Var = vf.add_var('ctrl.limPIDFreeze.addFF.k1_' + template_name)
    ctrl_limPIDFreeze_addFF_k2: Var = vf.add_var('ctrl.limPIDFreeze.addFF.k2_' + template_name)
    ctrl_limPIDFreeze_addI_k1: Var = vf.add_var('ctrl.limPIDFreeze.addI.k1_' + template_name)
    ctrl_limPIDFreeze_addI_k2: Var = vf.add_var('ctrl.limPIDFreeze.addI.k2_' + template_name)
    ctrl_limPIDFreeze_addI_k3: Var = vf.add_var('ctrl.limPIDFreeze.addI.k3_' + template_name)
    ctrl_limPIDFreeze_addP_k1: Var = vf.add_var('ctrl.limPIDFreeze.addP.k1_' + template_name)
    ctrl_limPIDFreeze_addP_k2: Var = vf.add_var('ctrl.limPIDFreeze.addP.k2_' + template_name)
    ctrl_limPIDFreeze_addPID_k1: Var = vf.add_var('ctrl.limPIDFreeze.addPID.k1_' + template_name)
    ctrl_limPIDFreeze_addPID_k2: Var = vf.add_var('ctrl.limPIDFreeze.addPID.k2_' + template_name)
    ctrl_limPIDFreeze_addSat_k1: Var = vf.add_var('ctrl.limPIDFreeze.addSat.k1_' + template_name)
    ctrl_limPIDFreeze_addSat_k2: Var = vf.add_var('ctrl.limPIDFreeze.addSat.k2_' + template_name)
    ctrl_limPIDFreeze_gainPID_k: Var = vf.add_var('ctrl.limPIDFreeze.gainPID.k_' + template_name)
    ctrl_limPIDFreeze_gainTrack_k: Var = vf.add_var('ctrl.limPIDFreeze.gainTrack.k_' + template_name)
    ctrl_limPIDFreeze_limiter_homotopyType: Var = vf.add_var('ctrl.limPIDFreeze.limiter.homotopyType_' + template_name)
    ctrl_limPIDFreeze_limiter_limitsAtInit: Var = vf.add_var('ctrl.limPIDFreeze.limiter.limitsAtInit_' + template_name)
    ctrl_limPIDFreeze_limiter_strict: Var = vf.add_var('ctrl.limPIDFreeze.limiter.strict_' + template_name)
    ctrl_limPIDFreeze_limiter_uMax: Var = vf.add_var('ctrl.limPIDFreeze.limiter.uMax_' + template_name)
    ctrl_limPIDFreeze_limiter_uMin: Var = vf.add_var('ctrl.limPIDFreeze.limiter.uMin_' + template_name)
    ctrl_limPIDFreeze_unitTime: Var = vf.add_var('ctrl.limPIDFreeze.unitTime_' + template_name)
    ctrl_limiter_homotopyType: Var = vf.add_var('ctrl.limiter.homotopyType_' + template_name)
    ctrl_limiter_limitsAtInit: Var = vf.add_var('ctrl.limiter.limitsAtInit_' + template_name)
    ctrl_limiter_strict: Var = vf.add_var('ctrl.limiter.strict_' + template_name)
    ctrl_limiter_uMax: Var = vf.add_var('ctrl.limiter.uMax_' + template_name)
    ctrl_limiter_uMin: Var = vf.add_var('ctrl.limiter.uMin_' + template_name)
    ctrl_limiter2_homotopyType: Var = vf.add_var('ctrl.limiter2.homotopyType_' + template_name)
    ctrl_limiter2_limitsAtInit: Var = vf.add_var('ctrl.limiter2.limitsAtInit_' + template_name)
    ctrl_limiter2_strict: Var = vf.add_var('ctrl.limiter2.strict_' + template_name)
    ctrl_limiter2_uMax: Var = vf.add_var('ctrl.limiter2.uMax_' + template_name)
    ctrl_limiter2_uMin: Var = vf.add_var('ctrl.limiter2.uMin_' + template_name)
    ctrl_limiter3_homotopyType: Var = vf.add_var('ctrl.limiter3.homotopyType_' + template_name)
    ctrl_limiter3_limitsAtInit: Var = vf.add_var('ctrl.limiter3.limitsAtInit_' + template_name)
    ctrl_limiter3_strict: Var = vf.add_var('ctrl.limiter3.strict_' + template_name)
    ctrl_limiter3_uMax: Var = vf.add_var('ctrl.limiter3.uMax_' + template_name)
    ctrl_limiter3_uMin: Var = vf.add_var('ctrl.limiter3.uMin_' + template_name)
    ctrl_rateLimFirstOrderFreeze_T: Var = vf.add_var('ctrl.rateLimFirstOrderFreeze.T_' + template_name)
    ctrl_rateLimFirstOrderFreeze_UseFreeze: Var = vf.add_var('ctrl.rateLimFirstOrderFreeze.UseFreeze_' + template_name)
    ctrl_rateLimFirstOrderFreeze_UseRateLim: Var = vf.add_var('ctrl.rateLimFirstOrderFreeze.UseRateLim_' + template_name)
    ctrl_rateLimFirstOrderFreeze_Y0: Var = vf.add_var('ctrl.rateLimFirstOrderFreeze.Y0_' + template_name)
    ctrl_rateLimFirstOrderFreeze_k: Var = vf.add_var('ctrl.rateLimFirstOrderFreeze.k_' + template_name)
    ctrl_rateLimFirstOrderFreeze1_T: Var = vf.add_var('ctrl.rateLimFirstOrderFreeze1.T_' + template_name)
    ctrl_rateLimFirstOrderFreeze1_UseFreeze: Var = vf.add_var('ctrl.rateLimFirstOrderFreeze1.UseFreeze_' + template_name)
    ctrl_rateLimFirstOrderFreeze1_UseRateLim: Var = vf.add_var('ctrl.rateLimFirstOrderFreeze1.UseRateLim_' + template_name)
    ctrl_rateLimFirstOrderFreeze1_Y0: Var = vf.add_var('ctrl.rateLimFirstOrderFreeze1.Y0_' + template_name)
    ctrl_rateLimFirstOrderFreeze1_k: Var = vf.add_var('ctrl.rateLimFirstOrderFreeze1.k_' + template_name)
    ctrl_slewRateLimiter_Falling: Var = vf.add_var('ctrl.slewRateLimiter.Falling_' + template_name)
    ctrl_slewRateLimiter_Rising: Var = vf.add_var('ctrl.slewRateLimiter.Rising_' + template_name)
    ctrl_slewRateLimiter_Td: Var = vf.add_var('ctrl.slewRateLimiter.Td_' + template_name)
    ctrl_slewRateLimiter_initType: Var = vf.add_var('ctrl.slewRateLimiter.initType_' + template_name)
    ctrl_slewRateLimiter_strict: Var = vf.add_var('ctrl.slewRateLimiter.strict_' + template_name)
    ctrl_slewRateLimiter_y_start: Var = vf.add_var('ctrl.slewRateLimiter.y_start_' + template_name)
    ctrl_tIq: Var = vf.add_var('ctrl.tIq_' + template_name)
    ctrl_tP: Var = vf.add_var('ctrl.tP_' + template_name)
    ctrl_tPord: Var = vf.add_var('ctrl.tPord_' + template_name)
    ctrl_tRv: Var = vf.add_var('ctrl.tRv_' + template_name)
    ctrl_varLimPIDFreeze_FFzero_k: Var = vf.add_var('ctrl.varLimPIDFreeze.FFzero.k_' + template_name)
    ctrl_varLimPIDFreeze_I_K: Var = vf.add_var('ctrl.varLimPIDFreeze.I.K_' + template_name)
    ctrl_varLimPIDFreeze_I_UseFreeze: Var = vf.add_var('ctrl.varLimPIDFreeze.I.UseFreeze_' + template_name)
    ctrl_varLimPIDFreeze_I_UseReset: Var = vf.add_var('ctrl.varLimPIDFreeze.I.UseReset_' + template_name)
    ctrl_varLimPIDFreeze_I_UseSet: Var = vf.add_var('ctrl.varLimPIDFreeze.I.UseSet_' + template_name)
    ctrl_varLimPIDFreeze_I_Y0: Var = vf.add_var('ctrl.varLimPIDFreeze.I.Y0_' + template_name)
    ctrl_varLimPIDFreeze_K: Var = vf.add_var('ctrl.varLimPIDFreeze.K_' + template_name)
    ctrl_varLimPIDFreeze_Kff: Var = vf.add_var('ctrl.varLimPIDFreeze.Kff_' + template_name)
    ctrl_varLimPIDFreeze_Ni: Var = vf.add_var('ctrl.varLimPIDFreeze.Ni_' + template_name)
    ctrl_varLimPIDFreeze_P_k: Var = vf.add_var('ctrl.varLimPIDFreeze.P.k_' + template_name)
    ctrl_varLimPIDFreeze_Strict: Var = vf.add_var('ctrl.varLimPIDFreeze.Strict_' + template_name)
    ctrl_varLimPIDFreeze_Ti: Var = vf.add_var('ctrl.varLimPIDFreeze.Ti_' + template_name)
    ctrl_varLimPIDFreeze_WithFeedForward: Var = vf.add_var('ctrl.varLimPIDFreeze.WithFeedForward_' + template_name)
    ctrl_varLimPIDFreeze_Wp: Var = vf.add_var('ctrl.varLimPIDFreeze.Wp_' + template_name)
    ctrl_varLimPIDFreeze_Xi0: Var = vf.add_var('ctrl.varLimPIDFreeze.Xi0_' + template_name)
    ctrl_varLimPIDFreeze_Y0: Var = vf.add_var('ctrl.varLimPIDFreeze.Y0_' + template_name)
    ctrl_varLimPIDFreeze_addFF_k1: Var = vf.add_var('ctrl.varLimPIDFreeze.addFF.k1_' + template_name)
    ctrl_varLimPIDFreeze_addFF_k2: Var = vf.add_var('ctrl.varLimPIDFreeze.addFF.k2_' + template_name)
    ctrl_varLimPIDFreeze_addI_k1: Var = vf.add_var('ctrl.varLimPIDFreeze.addI.k1_' + template_name)
    ctrl_varLimPIDFreeze_addI_k2: Var = vf.add_var('ctrl.varLimPIDFreeze.addI.k2_' + template_name)
    ctrl_varLimPIDFreeze_addI_k3: Var = vf.add_var('ctrl.varLimPIDFreeze.addI.k3_' + template_name)
    ctrl_varLimPIDFreeze_addP_k1: Var = vf.add_var('ctrl.varLimPIDFreeze.addP.k1_' + template_name)
    ctrl_varLimPIDFreeze_addP_k2: Var = vf.add_var('ctrl.varLimPIDFreeze.addP.k2_' + template_name)
    ctrl_varLimPIDFreeze_addPID_k1: Var = vf.add_var('ctrl.varLimPIDFreeze.addPID.k1_' + template_name)
    ctrl_varLimPIDFreeze_addPID_k2: Var = vf.add_var('ctrl.varLimPIDFreeze.addPID.k2_' + template_name)
    ctrl_varLimPIDFreeze_addSat_k1: Var = vf.add_var('ctrl.varLimPIDFreeze.addSat.k1_' + template_name)
    ctrl_varLimPIDFreeze_addSat_k2: Var = vf.add_var('ctrl.varLimPIDFreeze.addSat.k2_' + template_name)
    ctrl_varLimPIDFreeze_gainPID_k: Var = vf.add_var('ctrl.varLimPIDFreeze.gainPID.k_' + template_name)
    ctrl_varLimPIDFreeze_gainTrack_k: Var = vf.add_var('ctrl.varLimPIDFreeze.gainTrack.k_' + template_name)
    ctrl_varLimPIDFreeze_limiter_homotopyType: Var = vf.add_var('ctrl.varLimPIDFreeze.limiter.homotopyType_' + template_name)
    ctrl_varLimPIDFreeze_limiter_limitsAtInit: Var = vf.add_var('ctrl.varLimPIDFreeze.limiter.limitsAtInit_' + template_name)
    ctrl_varLimPIDFreeze_limiter_strict: Var = vf.add_var('ctrl.varLimPIDFreeze.limiter.strict_' + template_name)
    ctrl_varLimPIDFreeze_limiter_ySimplified: Var = vf.add_var('ctrl.varLimPIDFreeze.limiter.ySimplified_' + template_name)
    ctrl_varLimPIDFreeze_unitTime: Var = vf.add_var('ctrl.varLimPIDFreeze.unitTime_' + template_name)
    ctrl_variableLimiter_homotopyType: Var = vf.add_var('ctrl.variableLimiter.homotopyType_' + template_name)
    ctrl_variableLimiter_limitsAtInit: Var = vf.add_var('ctrl.variableLimiter.limitsAtInit_' + template_name)
    ctrl_variableLimiter_strict: Var = vf.add_var('ctrl.variableLimiter.strict_' + template_name)
    ctrl_variableLimiter_ySimplified: Var = vf.add_var('ctrl.variableLimiter.ySimplified_' + template_name)
    ctrl_variableLimiter1_homotopyType: Var = vf.add_var('ctrl.variableLimiter1.homotopyType_' + template_name)
    ctrl_variableLimiter1_limitsAtInit: Var = vf.add_var('ctrl.variableLimiter1.limitsAtInit_' + template_name)
    ctrl_variableLimiter1_strict: Var = vf.add_var('ctrl.variableLimiter1.strict_' + template_name)
    ctrl_variableLimiter1_ySimplified: Var = vf.add_var('ctrl.variableLimiter1.ySimplified_' + template_name)
    ctrl_voltageCheck_UMaxPu: Var = vf.add_var('ctrl.voltageCheck.UMaxPu_' + template_name)
    ctrl_voltageCheck_UMinPu: Var = vf.add_var('ctrl.voltageCheck.UMinPu_' + template_name)
    # Declare the state variables used by the template.
    ctrl_firstOrder_y: Var = vf.add_var('ctrl.firstOrder.y_' + template_name)
    ctrl_firstOrder1_y: Var = vf.add_var('ctrl.firstOrder1.y_' + template_name)
    ctrl_firstOrder2_y: Var = vf.add_var('ctrl.firstOrder2.y_' + template_name)
    ctrl_firstOrder3_y: Var = vf.add_var('ctrl.firstOrder3.y_' + template_name)
    ctrl_limPIDFreeze_I_y: Var = vf.add_var('ctrl.limPIDFreeze.I.y_' + template_name)
    ctrl_rateLimFirstOrderFreeze_y: Var = vf.add_var('ctrl.rateLimFirstOrderFreeze.y_' + template_name)
    ctrl_rateLimFirstOrderFreeze1_y: Var = vf.add_var('ctrl.rateLimFirstOrderFreeze1.y_' + template_name)
    ctrl_slewRateLimiter_y: Var = vf.add_var('ctrl.slewRateLimiter.y_' + template_name)
    ctrl_varLimPIDFreeze_I_y: Var = vf.add_var('ctrl.varLimPIDFreeze.I.y_' + template_name)
    # Declare the algebraic/shared variables used by the template.
    START_ctrl_firstOrder_y: Var = vf.add_var('$START.ctrl.firstOrder.y_' + template_name)
    START_ctrl_firstOrder1_y: Var = vf.add_var('$START.ctrl.firstOrder1.y_' + template_name)
    START_ctrl_firstOrder2_y: Var = vf.add_var('$START.ctrl.firstOrder2.y_' + template_name)
    START_ctrl_firstOrder3_y: Var = vf.add_var('$START.ctrl.firstOrder3.y_' + template_name)
    START_ctrl_limPIDFreeze_I_y: Var = vf.add_var('$START.ctrl.limPIDFreeze.I.y_' + template_name)
    START_ctrl_rateLimFirstOrderFreeze_y: Var = vf.add_var('$START.ctrl.rateLimFirstOrderFreeze.y_' + template_name)
    START_ctrl_rateLimFirstOrderFreeze1_y: Var = vf.add_var('$START.ctrl.rateLimFirstOrderFreeze1.y_' + template_name)
    START_ctrl_varLimPIDFreeze_I_y: Var = vf.add_var('$START.ctrl.varLimPIDFreeze.I.y_' + template_name)
    ctrl_IqMin_y: Var = vf.add_var('ctrl.IqMin.y_' + template_name)
    ctrl_PFaRef: Var = vf.add_var('ctrl.PFaRef_' + template_name)
    ctrl_PInjPu: Var = vf.add_var('ctrl.PInjPu_' + template_name)
    ctrl_PInjRefPu: Var = vf.add_var('ctrl.PInjRefPu_' + template_name)
    ctrl_QInjPu: Var = vf.add_var('ctrl.QInjPu_' + template_name)
    ctrl_QInjRefPu: Var = vf.add_var('ctrl.QInjRefPu_' + template_name)
    ctrl_UPu: Var = vf.add_var('ctrl.UPu_' + template_name)
    ctrl_add_y: Var = vf.add_var('ctrl.add.y_' + template_name)
    ctrl_add1_y: Var = vf.add_var('ctrl.add1.y_' + template_name)
    ctrl_add2_y: Var = vf.add_var('ctrl.add2.y_' + template_name)
    ctrl_currentLimitsCalculation1_ipMinPu: Var = vf.add_var('ctrl.currentLimitsCalculation1.ipMinPu_' + template_name)
    ctrl_deadZone_y: Var = vf.add_var('ctrl.deadZone.y_' + template_name)
    ctrl_division_y: Var = vf.add_var('ctrl.division.y_' + template_name)
    ctrl_division1_y: Var = vf.add_var('ctrl.division1.y_' + template_name)
    ctrl_frtOn: Var = vf.add_var('ctrl.frtOn_' + template_name)
    ctrl_gain_y: Var = vf.add_var('ctrl.gain.y_' + template_name)
    ctrl_idCmdPu: Var = vf.add_var('ctrl.idCmdPu_' + template_name)
    ctrl_iqCmdPu: Var = vf.add_var('ctrl.iqCmdPu_' + template_name)
    ctrl_limPIDFreeze_I_resetLocal: Var = vf.add_var('ctrl.limPIDFreeze.I.resetLocal_' + template_name)
    ctrl_limPIDFreeze_I_setLocal: Var = vf.add_var('ctrl.limPIDFreeze.I.setLocal_' + template_name)
    ctrl_limPIDFreeze_P_y: Var = vf.add_var('ctrl.limPIDFreeze.P.y_' + template_name)
    ctrl_limPIDFreeze_addFF_y: Var = vf.add_var('ctrl.limPIDFreeze.addFF.y_' + template_name)
    ctrl_limPIDFreeze_addI_y: Var = vf.add_var('ctrl.limPIDFreeze.addI.y_' + template_name)
    ctrl_limPIDFreeze_addP_y: Var = vf.add_var('ctrl.limPIDFreeze.addP.y_' + template_name)
    ctrl_limPIDFreeze_addPID_y: Var = vf.add_var('ctrl.limPIDFreeze.addPID.y_' + template_name)
    ctrl_limPIDFreeze_addSat_y: Var = vf.add_var('ctrl.limPIDFreeze.addSat.y_' + template_name)
    ctrl_limPIDFreeze_controlError: Var = vf.add_var('ctrl.limPIDFreeze.controlError_' + template_name)
    ctrl_limPIDFreeze_gainPID_y: Var = vf.add_var('ctrl.limPIDFreeze.gainPID.y_' + template_name)
    ctrl_limPIDFreeze_gainTrack_y: Var = vf.add_var('ctrl.limPIDFreeze.gainTrack.y_' + template_name)
    ctrl_limPIDFreeze_limiter_simplifiedExpr: Var = vf.add_var('ctrl.limPIDFreeze.limiter.simplifiedExpr_' + template_name)
    ctrl_limPIDFreeze_y: Var = vf.add_var('ctrl.limPIDFreeze.y_' + template_name)
    ctrl_limiter_simplifiedExpr: Var = vf.add_var('ctrl.limiter.simplifiedExpr_' + template_name)
    ctrl_limiter_y: Var = vf.add_var('ctrl.limiter.y_' + template_name)
    ctrl_limiter2_simplifiedExpr: Var = vf.add_var('ctrl.limiter2.simplifiedExpr_' + template_name)
    ctrl_limiter3_simplifiedExpr: Var = vf.add_var('ctrl.limiter3.simplifiedExpr_' + template_name)
    ctrl_limiter3_y: Var = vf.add_var('ctrl.limiter3.y_' + template_name)
    ctrl_max1_y: Var = vf.add_var('ctrl.max1.y_' + template_name)
    ctrl_product_y: Var = vf.add_var('ctrl.product.y_' + template_name)
    ctrl_rateLimFirstOrderFreeze_dyMaxLocal: Var = vf.add_var('ctrl.rateLimFirstOrderFreeze.dyMaxLocal_' + template_name)
    ctrl_rateLimFirstOrderFreeze_dyMinLocal: Var = vf.add_var('ctrl.rateLimFirstOrderFreeze.dyMinLocal_' + template_name)
    ctrl_rateLimFirstOrderFreeze1_dyMaxLocal: Var = vf.add_var('ctrl.rateLimFirstOrderFreeze1.dyMaxLocal_' + template_name)
    ctrl_rateLimFirstOrderFreeze1_dyMinLocal: Var = vf.add_var('ctrl.rateLimFirstOrderFreeze1.dyMinLocal_' + template_name)
    ctrl_slewRateLimiter_val: Var = vf.add_var('ctrl.slewRateLimiter.val_' + template_name)
    ctrl_switch_y: Var = vf.add_var('ctrl.switch.y_' + template_name)
    ctrl_switch1_y: Var = vf.add_var('ctrl.switch1.y_' + template_name)
    ctrl_switch2_y: Var = vf.add_var('ctrl.switch2.y_' + template_name)
    ctrl_tan_y: Var = vf.add_var('ctrl.tan.y_' + template_name)
    ctrl_varLimPIDFreeze_I_resetLocal: Var = vf.add_var('ctrl.varLimPIDFreeze.I.resetLocal_' + template_name)
    ctrl_varLimPIDFreeze_I_setLocal: Var = vf.add_var('ctrl.varLimPIDFreeze.I.setLocal_' + template_name)
    ctrl_varLimPIDFreeze_P_y: Var = vf.add_var('ctrl.varLimPIDFreeze.P.y_' + template_name)
    ctrl_varLimPIDFreeze_addFF_y: Var = vf.add_var('ctrl.varLimPIDFreeze.addFF.y_' + template_name)
    ctrl_varLimPIDFreeze_addI_y: Var = vf.add_var('ctrl.varLimPIDFreeze.addI.y_' + template_name)
    ctrl_varLimPIDFreeze_addP_y: Var = vf.add_var('ctrl.varLimPIDFreeze.addP.y_' + template_name)
    ctrl_varLimPIDFreeze_addPID_y: Var = vf.add_var('ctrl.varLimPIDFreeze.addPID.y_' + template_name)
    ctrl_varLimPIDFreeze_addSat_y: Var = vf.add_var('ctrl.varLimPIDFreeze.addSat.y_' + template_name)
    ctrl_varLimPIDFreeze_controlError: Var = vf.add_var('ctrl.varLimPIDFreeze.controlError_' + template_name)
    ctrl_varLimPIDFreeze_gainPID_y: Var = vf.add_var('ctrl.varLimPIDFreeze.gainPID.y_' + template_name)
    ctrl_varLimPIDFreeze_gainTrack_y: Var = vf.add_var('ctrl.varLimPIDFreeze.gainTrack.y_' + template_name)
    ctrl_varLimPIDFreeze_limiter_simplifiedExpr: Var = vf.add_var('ctrl.varLimPIDFreeze.limiter.simplifiedExpr_' + template_name)
    ctrl_varLimPIDFreeze_y: Var = vf.add_var('ctrl.varLimPIDFreeze.y_' + template_name)
    ctrl_variableLimiter_simplifiedExpr: Var = vf.add_var('ctrl.variableLimiter.simplifiedExpr_' + template_name)
    ctrl_variableLimiter1_simplifiedExpr: Var = vf.add_var('ctrl.variableLimiter1.simplifiedExpr_' + template_name)
    # Declare the differential variables used by the template.
    d_ctrl_firstOrder_y: Var = vf.add_diff_var('d_ctrl.firstOrder.y_' + template_name, base_var=ctrl_firstOrder_y)
    d_ctrl_firstOrder1_y: Var = vf.add_diff_var('d_ctrl.firstOrder1.y_' + template_name, base_var=ctrl_firstOrder1_y)
    d_ctrl_firstOrder2_y: Var = vf.add_diff_var('d_ctrl.firstOrder2.y_' + template_name, base_var=ctrl_firstOrder2_y)
    d_ctrl_firstOrder3_y: Var = vf.add_diff_var('d_ctrl.firstOrder3.y_' + template_name, base_var=ctrl_firstOrder3_y)
    d_ctrl_limPIDFreeze_I_y: Var = vf.add_diff_var('d_ctrl.limPIDFreeze.I.y_' + template_name, base_var=ctrl_limPIDFreeze_I_y)
    d_ctrl_rateLimFirstOrderFreeze_y: Var = vf.add_diff_var('d_ctrl.rateLimFirstOrderFreeze.y_' + template_name, base_var=ctrl_rateLimFirstOrderFreeze_y)
    d_ctrl_rateLimFirstOrderFreeze1_y: Var = vf.add_diff_var('d_ctrl.rateLimFirstOrderFreeze1.y_' + template_name, base_var=ctrl_rateLimFirstOrderFreeze1_y)
    d_ctrl_slewRateLimiter_y: Var = vf.add_diff_var('d_ctrl.slewRateLimiter.y_' + template_name, base_var=ctrl_slewRateLimiter_y)
    d_ctrl_varLimPIDFreeze_I_y: Var = vf.add_diff_var('d_ctrl.varLimPIDFreeze.I.y_' + template_name, base_var=ctrl_varLimPIDFreeze_I_y)

    # Build explicit typed collections so the symbolic surface is easy to inspect.
    state_equations: list[Expr] = list()
    state_equations.append(((ctrl_frtOn * sym.Const(0.0)) + ((sym.Const(1.0) - ctrl_frtOn) * sym.min(sym.max(((-ctrl_rateLimFirstOrderFreeze1_y) / ctrl_rateLimFirstOrderFreeze1_T), sym.Const(-9999.0)), sym.Const(9999.0)))))
    state_equations.append(((ctrl_firstOrder_k - ctrl_firstOrder_y) / ctrl_firstOrder_T))
    state_equations.append((((sym.Const(0.8) * ctrl_firstOrder1_k) - ctrl_firstOrder1_y) / ctrl_firstOrder1_T))
    state_equations.append(((ctrl_frtOn * sym.Const(0.0)) + ((sym.Const(1.0) - ctrl_frtOn) * (ctrl_limPIDFreeze_I_K * ctrl_limPIDFreeze_addI_y))))
    state_equations.append(((ctrl_frtOn * sym.Const(0.0)) + ((sym.Const(1.0) - ctrl_frtOn) * sym.min(sym.max((((ctrl_rateLimFirstOrderFreeze_k * ctrl_slewRateLimiter_y) - ctrl_rateLimFirstOrderFreeze_y) / ctrl_rateLimFirstOrderFreeze_T), sym.Const(-9999.0)), sym.Const(9999.0)))))
    state_equations.append(((ctrl_frtOn * sym.Const(0.0)) + ((sym.Const(1.0) - ctrl_frtOn) * (ctrl_varLimPIDFreeze_I_K * ctrl_varLimPIDFreeze_addI_y))))
    state_equations.append((((ctrl_firstOrder2_k * ctrl_iqCmdPu) - ctrl_firstOrder2_y) / ctrl_firstOrder2_T))
    state_equations.append(((sym.heaviside(((ctrl_slewRateLimiter_Falling - ctrl_slewRateLimiter_val) - sym.Const(1e-06))) * ctrl_slewRateLimiter_Falling) + ((sym.Const(1.0) - sym.heaviside(((ctrl_slewRateLimiter_Falling - ctrl_slewRateLimiter_val) - sym.Const(1e-06)))) * ((sym.heaviside(((ctrl_slewRateLimiter_val - ctrl_slewRateLimiter_Rising) - sym.Const(1e-06))) * ctrl_slewRateLimiter_Rising) + ((sym.Const(1.0) - sym.heaviside(((ctrl_slewRateLimiter_val - ctrl_slewRateLimiter_Rising) - sym.Const(1e-06)))) * ctrl_slewRateLimiter_val)))))
    state_equations.append((((ctrl_firstOrder3_k * ctrl_idCmdPu) - ctrl_firstOrder3_y) / ctrl_firstOrder3_T))
    state_variables: list[Var] = list()
    state_variables.append(ctrl_rateLimFirstOrderFreeze1_y)
    state_variables.append(ctrl_firstOrder_y)
    state_variables.append(ctrl_firstOrder1_y)
    state_variables.append(ctrl_limPIDFreeze_I_y)
    state_variables.append(ctrl_rateLimFirstOrderFreeze_y)
    state_variables.append(ctrl_varLimPIDFreeze_I_y)
    state_variables.append(ctrl_firstOrder2_y)
    state_variables.append(ctrl_slewRateLimiter_y)
    state_variables.append(ctrl_firstOrder3_y)
    algebraic_equations: list[Expr] = list()
    algebraic_equations.append((ctrl_switch1_y - sym.Const(0.0)))
    algebraic_equations.append((ctrl_limPIDFreeze_controlError - ((sym.heaviside(((sym.Const(0.0) - ctrl_limiter2_uMax) - sym.Const(1e-06))) * ctrl_limiter2_uMax) + ((sym.Const(1.0) - sym.heaviside(((sym.Const(0.0) - ctrl_limiter2_uMax) - sym.Const(1e-06)))) * ((sym.heaviside(((ctrl_limiter2_uMin - sym.Const(0.0)) - sym.Const(1e-06))) * ctrl_limiter2_uMin) + ((sym.Const(1.0) - sym.heaviside(((ctrl_limiter2_uMin - sym.Const(0.0)) - sym.Const(1e-06)))) * sym.Const(0.0)))))))
    algebraic_equations.append((ctrl_limPIDFreeze_addP_y - (ctrl_limPIDFreeze_addP_k1 * ctrl_limPIDFreeze_controlError)))
    algebraic_equations.append((ctrl_limPIDFreeze_P_y - (ctrl_limPIDFreeze_P_k * ctrl_limPIDFreeze_addP_y)))
    algebraic_equations.append((ctrl_add2_y - ((ctrl_add2_k1 * ctrl_VRef1Pu) + (ctrl_add2_k2 * ctrl_switch1_y))))
    algebraic_equations.append((ctrl_division_y - sym.Const(0.0)))
    algebraic_equations.append((ctrl_limPIDFreeze_addPID_y - ((ctrl_limPIDFreeze_addPID_k1 * ctrl_limPIDFreeze_P_y) + (ctrl_limPIDFreeze_addPID_k2 * ctrl_limPIDFreeze_I_y))))
    algebraic_equations.append((ctrl_limPIDFreeze_gainPID_y - (ctrl_limPIDFreeze_gainPID_k * ctrl_limPIDFreeze_addPID_y)))
    algebraic_equations.append((ctrl_limPIDFreeze_addFF_y - ((ctrl_limPIDFreeze_addFF_k1 * ctrl_limPIDFreeze_gainPID_y) + (ctrl_limPIDFreeze_addFF_k2 * ctrl_limPIDFreeze_FFzero_k))))
    algebraic_equations.append((ctrl_limPIDFreeze_y - ((sym.heaviside(((ctrl_limPIDFreeze_addFF_y - ctrl_limPIDFreeze_limiter_uMax) - sym.Const(1e-06))) * ctrl_limPIDFreeze_limiter_uMax) + ((sym.Const(1.0) - sym.heaviside(((ctrl_limPIDFreeze_addFF_y - ctrl_limPIDFreeze_limiter_uMax) - sym.Const(1e-06)))) * ((sym.heaviside(((ctrl_limPIDFreeze_limiter_uMin - ctrl_limPIDFreeze_addFF_y) - sym.Const(1e-06))) * ctrl_limPIDFreeze_limiter_uMin) + ((sym.Const(1.0) - sym.heaviside(((ctrl_limPIDFreeze_limiter_uMin - ctrl_limPIDFreeze_addFF_y) - sym.Const(1e-06)))) * ctrl_limPIDFreeze_addFF_y))))))
    algebraic_equations.append((ctrl_switch_y - ((ctrl_VFlag0_k * ctrl_limPIDFreeze_y) + ((sym.Const(1.0) - ctrl_VFlag0_k) * ctrl_add2_y))))
    algebraic_equations.append((ctrl_limiter_y - ((sym.heaviside(((ctrl_switch_y - ctrl_limiter_uMax) - sym.Const(1e-06))) * ctrl_limiter_uMax) + ((sym.Const(1.0) - sym.heaviside(((ctrl_switch_y - ctrl_limiter_uMax) - sym.Const(1e-06)))) * ((sym.heaviside(((ctrl_limiter_uMin - ctrl_switch_y) - sym.Const(1e-06))) * ctrl_limiter_uMin) + ((sym.Const(1.0) - sym.heaviside(((ctrl_limiter_uMin - ctrl_switch_y) - sym.Const(1e-06)))) * ctrl_switch_y))))))
    algebraic_equations.append((ctrl_varLimPIDFreeze_addP_y - ((ctrl_varLimPIDFreeze_addP_k1 * ctrl_limiter_y) + (ctrl_varLimPIDFreeze_addP_k2 * ctrl_firstOrder_y))))
    algebraic_equations.append((ctrl_varLimPIDFreeze_P_y - (ctrl_varLimPIDFreeze_P_k * ctrl_varLimPIDFreeze_addP_y)))
    algebraic_equations.append((ctrl_varLimPIDFreeze_addPID_y - ((ctrl_varLimPIDFreeze_addPID_k1 * ctrl_varLimPIDFreeze_P_y) + (ctrl_varLimPIDFreeze_addPID_k2 * ctrl_varLimPIDFreeze_I_y))))
    algebraic_equations.append((ctrl_varLimPIDFreeze_gainPID_y - (ctrl_varLimPIDFreeze_gainPID_k * ctrl_varLimPIDFreeze_addPID_y)))
    algebraic_equations.append((ctrl_varLimPIDFreeze_addFF_y - ((ctrl_varLimPIDFreeze_addFF_k1 * ctrl_varLimPIDFreeze_gainPID_y) + (ctrl_varLimPIDFreeze_addFF_k2 * ctrl_varLimPIDFreeze_FFzero_k))))
    algebraic_equations.append((ctrl_varLimPIDFreeze_controlError - (ctrl_limiter_y - ctrl_firstOrder_y)))
    algebraic_equations.append((ctrl_limPIDFreeze_addSat_y - ((ctrl_limPIDFreeze_addSat_k1 * ctrl_limPIDFreeze_y) + (ctrl_limPIDFreeze_addSat_k2 * ctrl_limPIDFreeze_addFF_y))))
    algebraic_equations.append((ctrl_limPIDFreeze_gainTrack_y - (ctrl_limPIDFreeze_gainTrack_k * ctrl_limPIDFreeze_addSat_y)))
    algebraic_equations.append((ctrl_limPIDFreeze_addI_y - ((ctrl_limPIDFreeze_addI_k1 * ctrl_limPIDFreeze_controlError) + (ctrl_limPIDFreeze_addI_k3 * ctrl_limPIDFreeze_gainTrack_y))))
    algebraic_equations.append((ctrl_limiter3_y - ((sym.heaviside(((ctrl_rateLimFirstOrderFreeze_y - ctrl_limiter3_uMax) - sym.Const(1e-06))) * ctrl_limiter3_uMax) + ((sym.Const(1.0) - sym.heaviside(((ctrl_rateLimFirstOrderFreeze_y - ctrl_limiter3_uMax) - sym.Const(1e-06)))) * ((sym.heaviside(((ctrl_limiter3_uMin - ctrl_rateLimFirstOrderFreeze_y) - sym.Const(1e-06))) * ctrl_limiter3_uMin) + ((sym.Const(1.0) - sym.heaviside(((ctrl_limiter3_uMin - ctrl_rateLimFirstOrderFreeze_y) - sym.Const(1e-06)))) * ctrl_rateLimFirstOrderFreeze_y))))))
    algebraic_equations.append((ctrl_add_y - ((ctrl_add_k1 * ctrl_firstOrder_y) + (ctrl_add_k2 * ctrl_VRefConst_k))))
    algebraic_equations.append((ctrl_deadZone_y - ((sym.heaviside(((ctrl_add_y - ctrl_deadZone_uMax) - sym.Const(1e-06))) * (ctrl_add_y - ctrl_deadZone_uMax)) + ((sym.Const(1.0) - sym.heaviside(((ctrl_add_y - ctrl_deadZone_uMax) - sym.Const(1e-06)))) * ((sym.heaviside(((ctrl_deadZone_uMin - ctrl_add_y) - sym.Const(1e-06))) * (ctrl_add_y - ctrl_deadZone_uMin)) + ((sym.Const(1.0) - sym.heaviside(((ctrl_deadZone_uMin - ctrl_add_y) - sym.Const(1e-06)))) * sym.Const(0.0)))))))
    algebraic_equations.append((ctrl_gain_y - (ctrl_gain_k * ctrl_deadZone_y)))
    algebraic_equations.append((ctrl_IqMin_y - ((sym.heaviside((((ctrl_currentLimitsCalculation1_IMaxPu ** sym.Const(2.0)) - (ctrl_firstOrder3_y ** sym.Const(2.0))) - sym.Const(1e-06))) * sym.sqrt(((ctrl_currentLimitsCalculation1_IMaxPu ** sym.Const(2.0)) - (ctrl_firstOrder3_y ** sym.Const(2.0))))) + ((sym.Const(1.0) - sym.heaviside((((ctrl_currentLimitsCalculation1_IMaxPu ** sym.Const(2.0)) - (ctrl_firstOrder3_y ** sym.Const(2.0))) - sym.Const(1e-06)))) * sym.Const(0.0)))))
    algebraic_equations.append((ctrl_varLimPIDFreeze_y - ((sym.heaviside(((ctrl_varLimPIDFreeze_addFF_y - (-ctrl_IqMin_y)) - sym.Const(1e-06))) * (-ctrl_IqMin_y)) + ((sym.Const(1.0) - sym.heaviside(((ctrl_varLimPIDFreeze_addFF_y - (-ctrl_IqMin_y)) - sym.Const(1e-06)))) * ((sym.heaviside(((ctrl_IqMin_y - ctrl_varLimPIDFreeze_addFF_y) - sym.Const(1e-06))) * ctrl_IqMin_y) + ((sym.Const(1.0) - sym.heaviside(((ctrl_IqMin_y - ctrl_varLimPIDFreeze_addFF_y) - sym.Const(1e-06)))) * ctrl_varLimPIDFreeze_addFF_y))))))
    algebraic_equations.append((ctrl_switch2_y - ((ctrl_QFlag0_k * ctrl_varLimPIDFreeze_y) + ((sym.Const(1.0) - ctrl_QFlag0_k) * ctrl_rateLimFirstOrderFreeze1_y))))
    algebraic_equations.append((ctrl_add1_y - ((ctrl_add1_k1 * ctrl_gain_y) + (ctrl_add1_k2 * ctrl_switch2_y))))
    algebraic_equations.append((ctrl_varLimPIDFreeze_addSat_y - ((ctrl_varLimPIDFreeze_addSat_k1 * ctrl_varLimPIDFreeze_y) + (ctrl_varLimPIDFreeze_addSat_k2 * ctrl_varLimPIDFreeze_addFF_y))))
    algebraic_equations.append((ctrl_varLimPIDFreeze_gainTrack_y - (ctrl_varLimPIDFreeze_gainTrack_k * ctrl_varLimPIDFreeze_addSat_y)))
    algebraic_equations.append((ctrl_varLimPIDFreeze_addI_y - ((ctrl_varLimPIDFreeze_addI_k1 * ctrl_limiter_y) + ((ctrl_varLimPIDFreeze_addI_k2 * ctrl_firstOrder_y) + (ctrl_varLimPIDFreeze_addI_k3 * ctrl_varLimPIDFreeze_gainTrack_y)))))
    algebraic_equations.append((ctrl_iqCmdPu - ((sym.heaviside(((ctrl_add1_y - (-ctrl_IqMin_y)) - sym.Const(1e-06))) * (-ctrl_IqMin_y)) + ((sym.Const(1.0) - sym.heaviside(((ctrl_add1_y - (-ctrl_IqMin_y)) - sym.Const(1e-06)))) * ((sym.heaviside(((ctrl_IqMin_y - ctrl_add1_y) - sym.Const(1e-06))) * ctrl_IqMin_y) + ((sym.Const(1.0) - sym.heaviside(((ctrl_IqMin_y - ctrl_add1_y) - sym.Const(1e-06)))) * ctrl_add1_y))))))
    algebraic_equations.append((ctrl_slewRateLimiter_val - ((ctrl_PInjRefPu - ctrl_slewRateLimiter_y) / ctrl_slewRateLimiter_Td)))
    algebraic_equations.append((ctrl_max1_y - sym.max(ctrl_firstOrder_y, ctrl_constant2_k)))
    algebraic_equations.append((ctrl_division1_y - (ctrl_limiter3_y / ctrl_max1_y)))
    algebraic_equations.append((ctrl_idCmdPu - ((sym.heaviside(((ctrl_division1_y - ctrl_currentLimitsCalculation1_IMaxPu) - sym.Const(1e-06))) * ctrl_currentLimitsCalculation1_IMaxPu) + ((sym.Const(1.0) - sym.heaviside(((ctrl_division1_y - ctrl_currentLimitsCalculation1_IMaxPu) - sym.Const(1e-06)))) * ((sym.heaviside(((sym.Const(0.0) - ctrl_division1_y) - sym.Const(1e-06))) * sym.Const(0.0)) + ((sym.Const(1.0) - sym.heaviside(((sym.Const(0.0) - ctrl_division1_y) - sym.Const(1e-06)))) * ctrl_division1_y))))))
    algebraic_variables: list[Var] = list()
    algebraic_variables.append(ctrl_switch1_y)
    algebraic_variables.append(ctrl_limPIDFreeze_controlError)
    algebraic_variables.append(ctrl_limPIDFreeze_addP_y)
    algebraic_variables.append(ctrl_limPIDFreeze_P_y)
    algebraic_variables.append(ctrl_add2_y)
    algebraic_variables.append(ctrl_division_y)
    algebraic_variables.append(ctrl_limPIDFreeze_addPID_y)
    algebraic_variables.append(ctrl_limPIDFreeze_gainPID_y)
    algebraic_variables.append(ctrl_limPIDFreeze_addFF_y)
    algebraic_variables.append(ctrl_limPIDFreeze_y)
    algebraic_variables.append(ctrl_switch_y)
    algebraic_variables.append(ctrl_limiter_y)
    algebraic_variables.append(ctrl_varLimPIDFreeze_addP_y)
    algebraic_variables.append(ctrl_varLimPIDFreeze_P_y)
    algebraic_variables.append(ctrl_varLimPIDFreeze_addPID_y)
    algebraic_variables.append(ctrl_varLimPIDFreeze_gainPID_y)
    algebraic_variables.append(ctrl_varLimPIDFreeze_addFF_y)
    algebraic_variables.append(ctrl_varLimPIDFreeze_controlError)
    algebraic_variables.append(ctrl_limPIDFreeze_addSat_y)
    algebraic_variables.append(ctrl_limPIDFreeze_gainTrack_y)
    algebraic_variables.append(ctrl_limPIDFreeze_addI_y)
    algebraic_variables.append(ctrl_limiter3_y)
    algebraic_variables.append(ctrl_add_y)
    algebraic_variables.append(ctrl_deadZone_y)
    algebraic_variables.append(ctrl_gain_y)
    algebraic_variables.append(ctrl_IqMin_y)
    algebraic_variables.append(ctrl_varLimPIDFreeze_y)
    algebraic_variables.append(ctrl_switch2_y)
    algebraic_variables.append(ctrl_add1_y)
    algebraic_variables.append(ctrl_varLimPIDFreeze_addSat_y)
    algebraic_variables.append(ctrl_varLimPIDFreeze_gainTrack_y)
    algebraic_variables.append(ctrl_varLimPIDFreeze_addI_y)
    algebraic_variables.append(ctrl_iqCmdPu)
    algebraic_variables.append(ctrl_slewRateLimiter_val)
    algebraic_variables.append(ctrl_max1_y)
    algebraic_variables.append(ctrl_division1_y)
    algebraic_variables.append(ctrl_idCmdPu)
    algebraic_variables.append(ctrl_frtOn)
    algebraic_variables.append(ctrl_PFaRef)
    algebraic_variables.append(ctrl_PInjPu)
    algebraic_variables.append(ctrl_PInjRefPu)
    algebraic_variables.append(ctrl_QInjPu)
    algebraic_variables.append(ctrl_QInjRefPu)
    algebraic_variables.append(ctrl_UPu)
    algebraic_variables.append(ctrl_limiter_simplifiedExpr)
    algebraic_variables.append(ctrl_limiter2_simplifiedExpr)
    algebraic_variables.append(ctrl_limPIDFreeze_limiter_simplifiedExpr)
    algebraic_variables.append(ctrl_limPIDFreeze_I_resetLocal)
    algebraic_variables.append(ctrl_limPIDFreeze_I_setLocal)
    algebraic_variables.append(ctrl_varLimPIDFreeze_limiter_simplifiedExpr)
    algebraic_variables.append(ctrl_varLimPIDFreeze_I_resetLocal)
    algebraic_variables.append(ctrl_varLimPIDFreeze_I_setLocal)
    algebraic_variables.append(ctrl_variableLimiter_simplifiedExpr)
    algebraic_variables.append(ctrl_variableLimiter1_simplifiedExpr)
    algebraic_variables.append(ctrl_limiter3_simplifiedExpr)
    algebraic_variables.append(ctrl_product_y)
    algebraic_variables.append(ctrl_tan_y)
    algebraic_variables.append(START_ctrl_firstOrder_y)
    algebraic_variables.append(START_ctrl_limPIDFreeze_I_y)
    algebraic_variables.append(START_ctrl_varLimPIDFreeze_I_y)
    algebraic_variables.append(START_ctrl_rateLimFirstOrderFreeze1_y)
    algebraic_variables.append(START_ctrl_rateLimFirstOrderFreeze_y)
    algebraic_variables.append(START_ctrl_firstOrder2_y)
    algebraic_variables.append(START_ctrl_firstOrder3_y)
    algebraic_variables.append(ctrl_rateLimFirstOrderFreeze1_dyMinLocal)
    algebraic_variables.append(ctrl_rateLimFirstOrderFreeze1_dyMaxLocal)
    algebraic_variables.append(ctrl_rateLimFirstOrderFreeze_dyMinLocal)
    algebraic_variables.append(ctrl_rateLimFirstOrderFreeze_dyMaxLocal)
    algebraic_variables.append(ctrl_currentLimitsCalculation1_ipMinPu)
    algebraic_variables.append(START_ctrl_firstOrder1_y)
    differential_variables: list[Var] = list()
    differential_variables.append(d_ctrl_rateLimFirstOrderFreeze1_y)
    differential_variables.append(d_ctrl_firstOrder_y)
    differential_variables.append(d_ctrl_firstOrder1_y)
    differential_variables.append(d_ctrl_limPIDFreeze_I_y)
    differential_variables.append(d_ctrl_rateLimFirstOrderFreeze_y)
    differential_variables.append(d_ctrl_varLimPIDFreeze_I_y)
    differential_variables.append(d_ctrl_firstOrder2_y)
    differential_variables.append(d_ctrl_slewRateLimiter_y)
    differential_variables.append(d_ctrl_firstOrder3_y)
    input_variables: list[Var] = list()
    output_variables: list[Var] = list()
    event_parameters: dict[Var, Expr | Const] = dict()
    event_parameters[ctrl_DPMaxPu] = vf.add_const(99.0, name='')
    event_parameters[ctrl_DPMinPu] = vf.add_const(-99.0, name='')
    event_parameters[ctrl_Dbd1Pu] = vf.add_const(-0.1, name='')
    event_parameters[ctrl_Dbd2Pu] = vf.add_const(0.1, name='')
    event_parameters[ctrl_IMaxPu] = vf.add_const(1.1, name='')
    event_parameters[ctrl_Id0Pu] = vf.add_const(0.8, name='')
    event_parameters[ctrl_Iq0Pu] = vf.add_const(0.0, name='')
    event_parameters[ctrl_Iqh1Pu] = vf.add_const(1.1, name='')
    event_parameters[ctrl_Iql1Pu] = vf.add_const(-1.1, name='')
    event_parameters[ctrl_Kqi] = vf.add_const(10.0, name='')
    event_parameters[ctrl_Kqp] = vf.add_const(1.0, name='')
    event_parameters[ctrl_Kqv] = vf.add_const(2.0, name='')
    event_parameters[ctrl_Kvi] = vf.add_const(10.0, name='')
    event_parameters[ctrl_Kvp] = vf.add_const(1.0, name='')
    event_parameters[ctrl_PF0] = vf.add_const(1.0, name='')
    event_parameters[ctrl_PInj0Pu] = vf.add_const(0.8, name='')
    event_parameters[ctrl_PMaxPu] = vf.add_const(1.0, name='')
    event_parameters[ctrl_PMinPu] = vf.add_const(0.0, name='')
    event_parameters[ctrl_QInj0Pu] = vf.add_const(0.0, name='')
    event_parameters[ctrl_QMaxPu] = vf.add_const(0.4, name='')
    event_parameters[ctrl_QMinPu] = vf.add_const(-0.4, name='')
    event_parameters[ctrl_UInj0Pu] = vf.add_const(1.0, name='')
    event_parameters[ctrl_VDipPu] = vf.add_const(0.9, name='')
    event_parameters[ctrl_VMaxPu] = vf.add_const(1.15, name='')
    event_parameters[ctrl_VMinPu] = vf.add_const(0.85, name='')
    event_parameters[ctrl_VRef0Pu] = vf.add_const(1.0, name='')
    event_parameters[ctrl_VRef1Pu] = vf.add_const(0.0, name='')
    event_parameters[ctrl_VRefConst_k] = ((sym.heaviside(((sym.Const(0.5) - ctrl_VRef0Pu) - sym.Const(1e-06))) * ctrl_UInj0Pu) + ((sym.Const(1.0) - sym.heaviside(((sym.Const(0.5) - ctrl_VRef0Pu) - sym.Const(1e-06)))) * ctrl_VRef0Pu))
    event_parameters[ctrl_VRefConst1_k] = ctrl_VRef1Pu
    event_parameters[ctrl_VUpPu] = vf.add_const(1.1, name='')
    event_parameters[ctrl_add_k1] = vf.add_const(-1.0, name='')
    event_parameters[ctrl_add_k2] = vf.add_const(1.0, name='')
    event_parameters[ctrl_add1_k1] = vf.add_const(1.0, name='')
    event_parameters[ctrl_add1_k2] = vf.add_const(1.0, name='')
    event_parameters[ctrl_add2_k1] = vf.add_const(1.0, name='')
    event_parameters[ctrl_add2_k2] = vf.add_const(1.0, name='')
    event_parameters[ctrl_constant2_k] = vf.add_const(0.01, name='')
    event_parameters[ctrl_currentLimitsCalculation1_IMaxPu] = ctrl_IMaxPu
    event_parameters[ctrl_deadZone_uMax] = ctrl_Dbd2Pu
    event_parameters[ctrl_deadZone_uMin] = ctrl_Dbd1Pu
    event_parameters[ctrl_firstOrder_T] = ctrl_tRv
    event_parameters[ctrl_firstOrder_k] = vf.add_const(1.0, name='')
    event_parameters[ctrl_firstOrder_y_start] = ctrl_UInj0Pu
    event_parameters[ctrl_firstOrder1_T] = ctrl_tP
    event_parameters[ctrl_firstOrder1_k] = vf.add_const(1.0, name='')
    event_parameters[ctrl_firstOrder1_y_start] = ctrl_PInj0Pu
    event_parameters[ctrl_firstOrder2_T] = vf.add_const(0.01, name='')
    event_parameters[ctrl_firstOrder2_k] = vf.add_const(1.0, name='')
    event_parameters[ctrl_firstOrder2_y_start] = ctrl_Iq0Pu
    event_parameters[ctrl_firstOrder3_T] = vf.add_const(0.01, name='')
    event_parameters[ctrl_firstOrder3_k] = vf.add_const(1.0, name='')
    event_parameters[ctrl_firstOrder3_y_start] = ctrl_Id0Pu
    event_parameters[ctrl_gain_k] = ctrl_Kqv
    event_parameters[ctrl_limPIDFreeze_FFzero_k] = vf.add_const(0.0, name='')
    event_parameters[ctrl_limPIDFreeze_I_K] = (sym.Const(1.0) / ctrl_limPIDFreeze_Ti)
    event_parameters[ctrl_limPIDFreeze_I_Y0] = ctrl_limPIDFreeze_Xi0
    event_parameters[ctrl_limPIDFreeze_K] = ctrl_Kqp
    event_parameters[ctrl_limPIDFreeze_Kff] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limPIDFreeze_Ni] = vf.add_const(0.9, name='')
    event_parameters[ctrl_limPIDFreeze_P_k] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limPIDFreeze_Ti] = (ctrl_Kqp / ctrl_Kqi)
    event_parameters[ctrl_limPIDFreeze_Wp] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limPIDFreeze_Xi0] = (ctrl_UInj0Pu / ctrl_Kqp)
    event_parameters[ctrl_limPIDFreeze_Y0] = ctrl_UInj0Pu
    event_parameters[ctrl_limPIDFreeze_YMax] = ctrl_VMaxPu
    event_parameters[ctrl_limPIDFreeze_YMin] = ctrl_VMinPu
    event_parameters[ctrl_limPIDFreeze_addFF_k1] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limPIDFreeze_addFF_k2] = ctrl_limPIDFreeze_Kff
    event_parameters[ctrl_limPIDFreeze_addI_k1] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limPIDFreeze_addI_k2] = vf.add_const(-1.0, name='')
    event_parameters[ctrl_limPIDFreeze_addI_k3] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limPIDFreeze_addP_k1] = ctrl_limPIDFreeze_Wp
    event_parameters[ctrl_limPIDFreeze_addP_k2] = vf.add_const(-1.0, name='')
    event_parameters[ctrl_limPIDFreeze_addPID_k1] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limPIDFreeze_addPID_k2] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limPIDFreeze_addSat_k1] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limPIDFreeze_addSat_k2] = vf.add_const(-1.0, name='')
    event_parameters[ctrl_limPIDFreeze_gainPID_k] = ctrl_limPIDFreeze_K
    event_parameters[ctrl_limPIDFreeze_gainTrack_k] = (sym.Const(1.0) / (ctrl_limPIDFreeze_Ni * ctrl_limPIDFreeze_K))
    event_parameters[ctrl_limPIDFreeze_limiter_uMax] = ctrl_limPIDFreeze_YMax
    event_parameters[ctrl_limPIDFreeze_limiter_uMin] = ctrl_limPIDFreeze_YMin
    event_parameters[ctrl_limiter_uMax] = ctrl_VMaxPu
    event_parameters[ctrl_limiter_uMin] = ctrl_VMinPu
    event_parameters[ctrl_limiter2_uMax] = ctrl_QMaxPu
    event_parameters[ctrl_limiter2_uMin] = ctrl_QMinPu
    event_parameters[ctrl_limiter3_uMax] = ctrl_PMaxPu
    event_parameters[ctrl_limiter3_uMin] = ctrl_PMinPu
    event_parameters[ctrl_rateLimFirstOrderFreeze_T] = ctrl_tPord
    event_parameters[ctrl_rateLimFirstOrderFreeze_Y0] = ctrl_PInj0Pu
    event_parameters[ctrl_rateLimFirstOrderFreeze_k] = vf.add_const(1.0, name='')
    event_parameters[ctrl_rateLimFirstOrderFreeze1_T] = ctrl_tIq
    event_parameters[ctrl_rateLimFirstOrderFreeze1_Y0] = (ctrl_QInj0Pu / ctrl_UInj0Pu)
    event_parameters[ctrl_rateLimFirstOrderFreeze1_k] = vf.add_const(1.0, name='')
    event_parameters[ctrl_slewRateLimiter_Falling] = ctrl_DPMinPu
    event_parameters[ctrl_slewRateLimiter_Rising] = ctrl_DPMaxPu
    event_parameters[ctrl_slewRateLimiter_Td] = vf.add_const(0.001, name='')
    event_parameters[ctrl_slewRateLimiter_y_start] = ctrl_PInj0Pu
    event_parameters[ctrl_tIq] = vf.add_const(0.02, name='')
    event_parameters[ctrl_tP] = vf.add_const(0.1, name='')
    event_parameters[ctrl_tPord] = vf.add_const(0.1, name='')
    event_parameters[ctrl_tRv] = vf.add_const(0.02, name='')
    event_parameters[ctrl_varLimPIDFreeze_FFzero_k] = vf.add_const(0.0, name='')
    event_parameters[ctrl_varLimPIDFreeze_I_K] = (sym.Const(1.0) / ctrl_varLimPIDFreeze_Ti)
    event_parameters[ctrl_varLimPIDFreeze_I_Y0] = ctrl_varLimPIDFreeze_Xi0
    event_parameters[ctrl_varLimPIDFreeze_K] = ctrl_Kvp
    event_parameters[ctrl_varLimPIDFreeze_Kff] = vf.add_const(1.0, name='')
    event_parameters[ctrl_varLimPIDFreeze_Ni] = vf.add_const(0.9, name='')
    event_parameters[ctrl_varLimPIDFreeze_P_k] = vf.add_const(1.0, name='')
    event_parameters[ctrl_varLimPIDFreeze_Ti] = (ctrl_Kvp / ctrl_Kvi)
    event_parameters[ctrl_varLimPIDFreeze_Wp] = vf.add_const(1.0, name='')
    event_parameters[ctrl_varLimPIDFreeze_Xi0] = (ctrl_QInj0Pu / (ctrl_Kqp * ctrl_UInj0Pu))
    event_parameters[ctrl_varLimPIDFreeze_Y0] = (ctrl_QInj0Pu / ctrl_UInj0Pu)
    event_parameters[ctrl_varLimPIDFreeze_addFF_k1] = vf.add_const(1.0, name='')
    event_parameters[ctrl_varLimPIDFreeze_addFF_k2] = ctrl_varLimPIDFreeze_Kff
    event_parameters[ctrl_varLimPIDFreeze_addI_k1] = vf.add_const(1.0, name='')
    event_parameters[ctrl_varLimPIDFreeze_addI_k2] = vf.add_const(-1.0, name='')
    event_parameters[ctrl_varLimPIDFreeze_addI_k3] = vf.add_const(1.0, name='')
    event_parameters[ctrl_varLimPIDFreeze_addP_k1] = ctrl_varLimPIDFreeze_Wp
    event_parameters[ctrl_varLimPIDFreeze_addP_k2] = vf.add_const(-1.0, name='')
    event_parameters[ctrl_varLimPIDFreeze_addPID_k1] = vf.add_const(1.0, name='')
    event_parameters[ctrl_varLimPIDFreeze_addPID_k2] = vf.add_const(1.0, name='')
    event_parameters[ctrl_varLimPIDFreeze_addSat_k1] = vf.add_const(1.0, name='')
    event_parameters[ctrl_varLimPIDFreeze_addSat_k2] = vf.add_const(-1.0, name='')
    event_parameters[ctrl_varLimPIDFreeze_gainPID_k] = ctrl_varLimPIDFreeze_K
    event_parameters[ctrl_varLimPIDFreeze_gainTrack_k] = (sym.Const(1.0) / (ctrl_varLimPIDFreeze_Ni * ctrl_varLimPIDFreeze_K))
    event_parameters[ctrl_varLimPIDFreeze_limiter_ySimplified] = vf.add_const(0.0, name='')
    event_parameters[ctrl_variableLimiter_ySimplified] = vf.add_const(0.0, name='')
    event_parameters[ctrl_variableLimiter1_ySimplified] = vf.add_const(0.0, name='')
    event_parameters[ctrl_voltageCheck_UMaxPu] = ctrl_VUpPu
    event_parameters[ctrl_voltageCheck_UMinPu] = ctrl_VDipPu
    event_parameters[ctrl_firstOrder_initType] = vf.add_const(1.0, name='')
    event_parameters[ctrl_firstOrder1_initType] = vf.add_const(1.0, name='')
    event_parameters[ctrl_firstOrder2_initType] = vf.add_const(1.0, name='')
    event_parameters[ctrl_firstOrder3_initType] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limPIDFreeze_limiter_homotopyType] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limiter_homotopyType] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limiter2_homotopyType] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limiter3_homotopyType] = vf.add_const(1.0, name='')
    event_parameters[ctrl_slewRateLimiter_initType] = vf.add_const(3.0, name='')
    event_parameters[ctrl_varLimPIDFreeze_limiter_homotopyType] = vf.add_const(1.0, name='')
    event_parameters[ctrl_variableLimiter_homotopyType] = vf.add_const(1.0, name='')
    event_parameters[ctrl_variableLimiter1_homotopyType] = vf.add_const(1.0, name='')
    event_parameters[ctrl_PQFlag] = vf.add_const(1.0, name='')
    event_parameters[ctrl_PfFlag] = vf.add_const(1.0, name='')
    event_parameters[ctrl_PfFlag0_k] = ctrl_PfFlag
    event_parameters[ctrl_QFlag] = vf.add_const(0.0, name='')
    event_parameters[ctrl_QFlag0_k] = ctrl_QFlag
    event_parameters[ctrl_VFlag] = vf.add_const(0.0, name='')
    event_parameters[ctrl_VFlag0_k] = ctrl_VFlag
    event_parameters[ctrl_currentLimitsCalculation1_PQFlag] = vf.add_const(1.0, name='')
    event_parameters[ctrl_deadZone_deadZoneAtInit] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limPIDFreeze_I_UseFreeze] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limPIDFreeze_I_UseReset] = vf.add_const(0.0, name='')
    event_parameters[ctrl_limPIDFreeze_I_UseSet] = vf.add_const(0.0, name='')
    event_parameters[ctrl_limPIDFreeze_Strict] = vf.add_const(0.0, name='')
    event_parameters[ctrl_limPIDFreeze_WithFeedForward] = vf.add_const(0.0, name='')
    event_parameters[ctrl_limPIDFreeze_limiter_limitsAtInit] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limPIDFreeze_limiter_strict] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limiter_limitsAtInit] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limiter_strict] = vf.add_const(0.0, name='')
    event_parameters[ctrl_limiter2_limitsAtInit] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limiter2_strict] = vf.add_const(0.0, name='')
    event_parameters[ctrl_limiter3_limitsAtInit] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limiter3_strict] = vf.add_const(0.0, name='')
    event_parameters[ctrl_rateLimFirstOrderFreeze_UseFreeze] = vf.add_const(1.0, name='')
    event_parameters[ctrl_rateLimFirstOrderFreeze_UseRateLim] = vf.add_const(0.0, name='')
    event_parameters[ctrl_rateLimFirstOrderFreeze1_UseFreeze] = vf.add_const(1.0, name='')
    event_parameters[ctrl_rateLimFirstOrderFreeze1_UseRateLim] = vf.add_const(0.0, name='')
    event_parameters[ctrl_slewRateLimiter_strict] = vf.add_const(0.0, name='')
    event_parameters[ctrl_varLimPIDFreeze_I_UseFreeze] = vf.add_const(1.0, name='')
    event_parameters[ctrl_varLimPIDFreeze_I_UseReset] = vf.add_const(0.0, name='')
    event_parameters[ctrl_varLimPIDFreeze_I_UseSet] = vf.add_const(0.0, name='')
    event_parameters[ctrl_varLimPIDFreeze_Strict] = vf.add_const(0.0, name='')
    event_parameters[ctrl_varLimPIDFreeze_WithFeedForward] = vf.add_const(0.0, name='')
    event_parameters[ctrl_varLimPIDFreeze_limiter_limitsAtInit] = vf.add_const(1.0, name='')
    event_parameters[ctrl_varLimPIDFreeze_limiter_strict] = vf.add_const(0.0, name='')
    event_parameters[ctrl_variableLimiter_limitsAtInit] = vf.add_const(1.0, name='')
    event_parameters[ctrl_variableLimiter_strict] = vf.add_const(0.0, name='')
    event_parameters[ctrl_variableLimiter1_limitsAtInit] = vf.add_const(1.0, name='')
    event_parameters[ctrl_variableLimiter1_strict] = vf.add_const(0.0, name='')
    event_parameters[ctrl_limPIDFreeze_unitTime] = vf.add_const(1.0, name='')
    event_parameters[ctrl_varLimPIDFreeze_unitTime] = vf.add_const(1.0, name='')
    mode_parameters: dict[Var, Expr | Const] = dict()
    initial_equations: dict[Var, Expr | Const] = dict()
    initial_equations[ctrl_firstOrder_y] = START_ctrl_firstOrder_y
    initial_equations[ctrl_firstOrder1_y] = START_ctrl_firstOrder1_y
    initial_equations[ctrl_firstOrder2_y] = START_ctrl_firstOrder2_y
    initial_equations[ctrl_firstOrder3_y] = START_ctrl_firstOrder3_y
    initial_equations[ctrl_limPIDFreeze_I_y] = START_ctrl_limPIDFreeze_I_y
    initial_equations[ctrl_rateLimFirstOrderFreeze_y] = START_ctrl_rateLimFirstOrderFreeze_y
    initial_equations[ctrl_rateLimFirstOrderFreeze1_y] = START_ctrl_rateLimFirstOrderFreeze1_y
    initial_equations[ctrl_slewRateLimiter_y] = ctrl_slewRateLimiter_y_start
    initial_equations[ctrl_varLimPIDFreeze_I_y] = START_ctrl_varLimPIDFreeze_I_y
    initial_equations[ctrl_PFaRef] = vf.add_const(0.0, name='')
    initial_equations[ctrl_PInjPu] = vf.add_const(0.8, name='')
    initial_equations[ctrl_PInjRefPu] = vf.add_const(0.8, name='')
    initial_equations[ctrl_QInjPu] = vf.add_const(0.0, name='')
    initial_equations[ctrl_QInjRefPu] = vf.add_const(0.0, name='')
    initial_equations[ctrl_UPu] = vf.add_const(1.0, name='')
    initial_equations[ctrl_add_y] = vf.add_const(0.0, name='')
    initial_equations[ctrl_add2_y] = ((ctrl_add2_k1 * ctrl_VRefConst1_k) + (ctrl_add2_k2 * ctrl_switch1_y))
    initial_equations[ctrl_division_y] = (ctrl_switch1_y / ctrl_max1_y)
    initial_equations[ctrl_idCmdPu] = vf.add_const(0.8, name='')
    initial_equations[ctrl_iqCmdPu] = vf.add_const(0.0, name='')
    initial_equations[ctrl_switch1_y] = vf.add_const(0.0, name='')
    initial_equations[ctrl_frtOn] = (sym.heaviside(((ctrl_voltageCheck_UMinPu - sym.Const(1.0)) - sym.Const(1e-06))) + sym.heaviside(((sym.Const(1.0) - ctrl_voltageCheck_UMaxPu) - sym.Const(1e-06))))
    initial_equations[ctrl_limiter_simplifiedExpr] = vf.add_const(0.0, name='')
    initial_equations[ctrl_limiter2_simplifiedExpr] = vf.add_const(0.0, name='')
    initial_equations[ctrl_limPIDFreeze_limiter_simplifiedExpr] = vf.add_const(0.0, name='')
    initial_equations[ctrl_limPIDFreeze_I_resetLocal] = vf.add_const(0.0, name='')
    initial_equations[ctrl_limPIDFreeze_I_setLocal] = vf.add_const(0.0, name='')
    initial_equations[ctrl_varLimPIDFreeze_limiter_simplifiedExpr] = vf.add_const(0.0, name='')
    initial_equations[ctrl_varLimPIDFreeze_I_resetLocal] = vf.add_const(0.0, name='')
    initial_equations[ctrl_varLimPIDFreeze_I_setLocal] = vf.add_const(0.0, name='')
    initial_equations[ctrl_variableLimiter_simplifiedExpr] = vf.add_const(0.0, name='')
    initial_equations[ctrl_variableLimiter1_simplifiedExpr] = vf.add_const(0.0, name='')
    initial_equations[ctrl_limiter3_simplifiedExpr] = vf.add_const(0.0, name='')
    initial_equations[ctrl_product_y] = vf.add_const(0.0, name='')
    initial_equations[ctrl_tan_y] = vf.add_const(0.0, name='')
    initial_equations[ctrl_limPIDFreeze_controlError] = ((sym.heaviside(((ctrl_switch1_y - ctrl_limiter2_uMax) - sym.Const(1e-06))) * ctrl_limiter2_uMax) + ((sym.Const(1.0) - sym.heaviside(((ctrl_switch1_y - ctrl_limiter2_uMax) - sym.Const(1e-06)))) * ((sym.heaviside(((ctrl_limiter2_uMin - ctrl_switch1_y) - sym.Const(1e-06))) * ctrl_limiter2_uMin) + ((sym.Const(1.0) - sym.heaviside(((ctrl_limiter2_uMin - ctrl_switch1_y) - sym.Const(1e-06)))) * ctrl_switch1_y))))
    initial_equations[ctrl_deadZone_y] = ((sym.heaviside(((ctrl_add_y - ctrl_deadZone_uMax) - sym.Const(1e-06))) * (ctrl_add_y - ctrl_deadZone_uMax)) + ((sym.Const(1.0) - sym.heaviside(((ctrl_add_y - ctrl_deadZone_uMax) - sym.Const(1e-06)))) * ((sym.heaviside(((ctrl_deadZone_uMin - ctrl_add_y) - sym.Const(1e-06))) * (ctrl_add_y - ctrl_deadZone_uMin)) + ((sym.Const(1.0) - sym.heaviside(((ctrl_deadZone_uMin - ctrl_add_y) - sym.Const(1e-06)))) * sym.Const(0.0)))))
    initial_equations[ctrl_rateLimFirstOrderFreeze1_dyMinLocal] = vf.add_const(-9999.0, name='')
    initial_equations[ctrl_rateLimFirstOrderFreeze1_dyMaxLocal] = vf.add_const(9999.0, name='')
    initial_equations[ctrl_rateLimFirstOrderFreeze_dyMinLocal] = vf.add_const(-9999.0, name='')
    initial_equations[ctrl_rateLimFirstOrderFreeze_dyMaxLocal] = vf.add_const(9999.0, name='')
    initial_equations[ctrl_currentLimitsCalculation1_ipMinPu] = vf.add_const(0.0, name='')
    differential_initial_equations: dict[Var, Expr | Const] = dict()
    differential_initial_equations[d_ctrl_rateLimFirstOrderFreeze1_y] = ((ctrl_frtOn * sym.Const(0.0)) + ((sym.Const(1.0) - ctrl_frtOn) * sym.min(sym.max((((ctrl_rateLimFirstOrderFreeze1_k * ctrl_division_y) - ctrl_rateLimFirstOrderFreeze1_y) / ctrl_rateLimFirstOrderFreeze1_T), sym.Const(-9999.0)), sym.Const(9999.0))))
    procedural_logic_entries: list[object] = list()

    # Assemble the final block from the explicit typed collections above.
    template.block = Block(
        state_vars=state_variables,
        state_eqs=state_equations,
        algebraic_vars=algebraic_variables,
        algebraic_eqs=algebraic_equations,
        diff_vars=differential_variables,
        init_eqs=initial_equations,
        diff_init_eqs=differential_initial_equations,
        in_vars=input_variables,
        out_vars=output_variables,
        event_dict=event_parameters,
        mode_dict=mode_parameters,
        procedural_logic=procedural_logic_entries,
        name=template_name,
    )

    template.block.state_eqs[0] = ((sym.Const(1.0) - ctrl_frtOn) * sym.min(sym.max((((ctrl_rateLimFirstOrderFreeze1_k * ctrl_division_y) - ctrl_rateLimFirstOrderFreeze1_y) / ctrl_rateLimFirstOrderFreeze1_T), sym.Const(-9999.0)), sym.Const(9999.0)))
    template.block.state_eqs[1] = (((ctrl_firstOrder_k * ctrl_UPu) - ctrl_firstOrder_y) / ctrl_firstOrder_T)
    template.block.state_eqs[2] = (((ctrl_firstOrder1_k * ctrl_PInjPu) - ctrl_firstOrder1_y) / ctrl_firstOrder1_T)
    template.block.init_eqs[ctrl_firstOrder_y] = ctrl_firstOrder_y_start
    template.block.init_eqs[ctrl_firstOrder1_y] = ctrl_firstOrder1_y_start
    template.block.init_eqs[ctrl_firstOrder2_y] = ctrl_firstOrder2_y_start
    template.block.init_eqs[ctrl_firstOrder3_y] = ctrl_firstOrder3_y_start
    template.block.init_eqs[ctrl_limPIDFreeze_I_y] = ctrl_limPIDFreeze_I_Y0
    template.block.init_eqs[ctrl_rateLimFirstOrderFreeze_y] = ctrl_rateLimFirstOrderFreeze_Y0
    template.block.init_eqs[ctrl_rateLimFirstOrderFreeze1_y] = ctrl_rateLimFirstOrderFreeze1_Y0
    template.block.init_eqs[ctrl_varLimPIDFreeze_I_y] = ctrl_varLimPIDFreeze_I_Y0

    template.comment = 'Generator WECC renewable electrical control REECB'
    return template
