# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
# SPDX-License-Identifier: MPL-2.0

"""
Maintainable international-standard module for 'REPCA'.

This is the runtime implementation shipped by VeraGrid.
It exposes the imported public interface, explicit symbolic equations, and
"""

from __future__ import annotations

from VeraGridEngine.Devices.Dynamic.rms_template import RmsModelTemplate
from VeraGridEngine.Devices.Dynamic.var_factory import VarFactory
from VeraGridEngine.Utils.Symbolic.block import Block
import VeraGridEngine.Utils.Symbolic.symbolic as sym
from VeraGridEngine.enumerations import DeviceType
from VeraGridEngine.Utils.Symbolic.symbolic import Var
from VeraGridEngine.Utils.Symbolic.symbolic import Expr
from VeraGridEngine.Utils.Symbolic.symbolic import Const
from VeraGridEngine.Utils.Symbolic.symbolic import BinOp

def build_repca_template(vf: VarFactory, name: str | None = None) -> RmsModelTemplate:
    """
    Materialize the international-standard EMT template.

    :param vf: Variable factory used to allocate the symbolic surface.
    :param name: Optional explicit runtime template name.
    :returns: Materialized EMT template.
    """
    template_name: str
    if name is None:
        template_name: str = 'REPCA'
    else:
        template_name: str = name

    # Allocate the template container before building the symbolic surface.
    template: RmsModelTemplate = RmsModelTemplate()
    template.tpe = DeviceType.GeneratorDevice
    template.name = template_name

    # Declare every variable explicitly before the equations reference it.
    # Declare the runtime parameter variables used by the template.
    ctrl_DDn: Var = vf.add_var('ctrl.DDn_' + template_name)
    ctrl_DUp: Var = vf.add_var('ctrl.DUp_' + template_name)
    ctrl_DbdPu: Var = vf.add_var('ctrl.DbdPu_' + template_name)
    ctrl_EMaxPu: Var = vf.add_var('ctrl.EMaxPu_' + template_name)
    ctrl_EMinPu: Var = vf.add_var('ctrl.EMinPu_' + template_name)
    ctrl_FDbd1Pu: Var = vf.add_var('ctrl.FDbd1Pu_' + template_name)
    ctrl_FDbd2Pu: Var = vf.add_var('ctrl.FDbd2Pu_' + template_name)
    ctrl_FEMaxPu: Var = vf.add_var('ctrl.FEMaxPu_' + template_name)
    ctrl_FEMinPu: Var = vf.add_var('ctrl.FEMinPu_' + template_name)
    ctrl_FreqFlag: Var = vf.add_var('ctrl.FreqFlag_' + template_name)
    ctrl_FreqFlag0_k: Var = vf.add_var('ctrl.FreqFlag0.k_' + template_name)
    ctrl_Kc: Var = vf.add_var('ctrl.Kc_' + template_name)
    ctrl_Ki: Var = vf.add_var('ctrl.Ki_' + template_name)
    ctrl_Kig: Var = vf.add_var('ctrl.Kig_' + template_name)
    ctrl_Kp: Var = vf.add_var('ctrl.Kp_' + template_name)
    ctrl_Kpg: Var = vf.add_var('ctrl.Kpg_' + template_name)
    ctrl_PGen0Pu: Var = vf.add_var('ctrl.PGen0Pu_' + template_name)
    ctrl_PInj0Pu: Var = vf.add_var('ctrl.PInj0Pu_' + template_name)
    ctrl_PMaxPu: Var = vf.add_var('ctrl.PMaxPu_' + template_name)
    ctrl_PMinPu: Var = vf.add_var('ctrl.PMinPu_' + template_name)
    ctrl_PRefLim_homotopyType: Var = vf.add_var('ctrl.PRefLim.homotopyType_' + template_name)
    ctrl_PRefLim_limitsAtInit: Var = vf.add_var('ctrl.PRefLim.limitsAtInit_' + template_name)
    ctrl_PRefLim_strict: Var = vf.add_var('ctrl.PRefLim.strict_' + template_name)
    ctrl_PRefLim_uMax: Var = vf.add_var('ctrl.PRefLim.uMax_' + template_name)
    ctrl_PRefLim_uMin: Var = vf.add_var('ctrl.PRefLim.uMin_' + template_name)
    ctrl_QCtrlErr_k1: Var = vf.add_var('ctrl.QCtrlErr.k1_' + template_name)
    ctrl_QCtrlErr_k2: Var = vf.add_var('ctrl.QCtrlErr.k2_' + template_name)
    ctrl_QGen0Pu: Var = vf.add_var('ctrl.QGen0Pu_' + template_name)
    ctrl_QInj0Pu: Var = vf.add_var('ctrl.QInj0Pu_' + template_name)
    ctrl_QMaxPu: Var = vf.add_var('ctrl.QMaxPu_' + template_name)
    ctrl_QMinPu: Var = vf.add_var('ctrl.QMinPu_' + template_name)
    ctrl_QVCtrlErr_k1: Var = vf.add_var('ctrl.QVCtrlErr.k1_' + template_name)
    ctrl_QVCtrlErr_k2: Var = vf.add_var('ctrl.QVCtrlErr.k2_' + template_name)
    ctrl_QVErrLim_homotopyType: Var = vf.add_var('ctrl.QVErrLim.homotopyType_' + template_name)
    ctrl_QVErrLim_limitsAtInit: Var = vf.add_var('ctrl.QVErrLim.limitsAtInit_' + template_name)
    ctrl_QVErrLim_strict: Var = vf.add_var('ctrl.QVErrLim.strict_' + template_name)
    ctrl_QVErrLim_uMax: Var = vf.add_var('ctrl.QVErrLim.uMax_' + template_name)
    ctrl_QVErrLim_uMin: Var = vf.add_var('ctrl.QVErrLim.uMin_' + template_name)
    ctrl_RcPu: Var = vf.add_var('ctrl.RcPu_' + template_name)
    ctrl_RefFlag: Var = vf.add_var('ctrl.RefFlag_' + template_name)
    ctrl_RefFlag0_k: Var = vf.add_var('ctrl.RefFlag0.k_' + template_name)
    ctrl_U0Pu: Var = vf.add_var('ctrl.U0Pu_' + template_name)
    ctrl_UCtrlErr_k1: Var = vf.add_var('ctrl.UCtrlErr.k1_' + template_name)
    ctrl_UCtrlErr_k2: Var = vf.add_var('ctrl.UCtrlErr.k2_' + template_name)
    ctrl_UInj0Pu: Var = vf.add_var('ctrl.UInj0Pu_' + template_name)
    ctrl_URef0Pu: Var = vf.add_var('ctrl.URef0Pu_' + template_name)
    ctrl_VCompFlag: Var = vf.add_var('ctrl.VCompFlag_' + template_name)
    ctrl_VCompFlag0_k: Var = vf.add_var('ctrl.VCompFlag0.k_' + template_name)
    ctrl_VFrz: Var = vf.add_var('ctrl.VFrz_' + template_name)
    ctrl_XcPu: Var = vf.add_var('ctrl.XcPu_' + template_name)
    ctrl_Zero_k: Var = vf.add_var('ctrl.Zero.k_' + template_name)
    ctrl_Zero1_k: Var = vf.add_var('ctrl.Zero1.k_' + template_name)
    ctrl_add3_k1: Var = vf.add_var('ctrl.add3.k1_' + template_name)
    ctrl_add3_k2: Var = vf.add_var('ctrl.add3.k2_' + template_name)
    ctrl_add3_k3: Var = vf.add_var('ctrl.add3.k3_' + template_name)
    ctrl_const_k: Var = vf.add_var('ctrl.const.k_' + template_name)
    ctrl_dPfreq_k1: Var = vf.add_var('ctrl.dPfreq.k1_' + template_name)
    ctrl_dPfreq_k2: Var = vf.add_var('ctrl.dPfreq.k2_' + template_name)
    ctrl_deadZone_deadZoneAtInit: Var = vf.add_var('ctrl.deadZone.deadZoneAtInit_' + template_name)
    ctrl_deadZone_uMax: Var = vf.add_var('ctrl.deadZone.uMax_' + template_name)
    ctrl_deadZone_uMin: Var = vf.add_var('ctrl.deadZone.uMin_' + template_name)
    ctrl_deadZone1_deadZoneAtInit: Var = vf.add_var('ctrl.deadZone1.deadZoneAtInit_' + template_name)
    ctrl_deadZone1_uMax: Var = vf.add_var('ctrl.deadZone1.uMax_' + template_name)
    ctrl_deadZone1_uMin: Var = vf.add_var('ctrl.deadZone1.uMin_' + template_name)
    ctrl_firstOrder_T: Var = vf.add_var('ctrl.firstOrder.T_' + template_name)
    ctrl_firstOrder_initType: Var = vf.add_var('ctrl.firstOrder.initType_' + template_name)
    ctrl_firstOrder_k: Var = vf.add_var('ctrl.firstOrder.k_' + template_name)
    ctrl_firstOrder_y_start: Var = vf.add_var('ctrl.firstOrder.y_start_' + template_name)
    ctrl_firstOrder1_T: Var = vf.add_var('ctrl.firstOrder1.T_' + template_name)
    ctrl_firstOrder1_initType: Var = vf.add_var('ctrl.firstOrder1.initType_' + template_name)
    ctrl_firstOrder1_k: Var = vf.add_var('ctrl.firstOrder1.k_' + template_name)
    ctrl_firstOrder1_y_start: Var = vf.add_var('ctrl.firstOrder1.y_start_' + template_name)
    ctrl_firstOrder2_T: Var = vf.add_var('ctrl.firstOrder2.T_' + template_name)
    ctrl_firstOrder2_initType: Var = vf.add_var('ctrl.firstOrder2.initType_' + template_name)
    ctrl_firstOrder2_k: Var = vf.add_var('ctrl.firstOrder2.k_' + template_name)
    ctrl_firstOrder2_y_start: Var = vf.add_var('ctrl.firstOrder2.y_start_' + template_name)
    ctrl_firstOrder3_T: Var = vf.add_var('ctrl.firstOrder3.T_' + template_name)
    ctrl_firstOrder3_initType: Var = vf.add_var('ctrl.firstOrder3.initType_' + template_name)
    ctrl_firstOrder3_k: Var = vf.add_var('ctrl.firstOrder3.k_' + template_name)
    ctrl_firstOrder3_y_start: Var = vf.add_var('ctrl.firstOrder3.y_start_' + template_name)
    ctrl_gain_k: Var = vf.add_var('ctrl.gain.k_' + template_name)
    ctrl_gain1_k: Var = vf.add_var('ctrl.gain1.k_' + template_name)
    ctrl_gain2_k: Var = vf.add_var('ctrl.gain2.k_' + template_name)
    ctrl_iInj0Pu_im: Var = vf.add_var('ctrl.iInj0Pu.im_' + template_name)
    ctrl_iInj0Pu_re: Var = vf.add_var('ctrl.iInj0Pu.re_' + template_name)
    ctrl_leadLag_a_1: Var = vf.add_var('ctrl.leadLag.a[1]_' + template_name)
    ctrl_leadLag_a_2: Var = vf.add_var('ctrl.leadLag.a[2]_' + template_name)
    ctrl_leadLag_a_end: Var = vf.add_var('ctrl.leadLag.a_end_' + template_name)
    ctrl_leadLag_b_1: Var = vf.add_var('ctrl.leadLag.b[1]_' + template_name)
    ctrl_leadLag_b_2: Var = vf.add_var('ctrl.leadLag.b[2]_' + template_name)
    ctrl_leadLag_bb_1: Var = vf.add_var('ctrl.leadLag.bb[1]_' + template_name)
    ctrl_leadLag_bb_2: Var = vf.add_var('ctrl.leadLag.bb[2]_' + template_name)
    ctrl_leadLag_d: Var = vf.add_var('ctrl.leadLag.d_' + template_name)
    ctrl_leadLag_na: Var = vf.add_var('ctrl.leadLag.na_' + template_name)
    ctrl_leadLag_nb: Var = vf.add_var('ctrl.leadLag.nb_' + template_name)
    ctrl_leadLag_nx: Var = vf.add_var('ctrl.leadLag.nx_' + template_name)
    ctrl_leadLag_x_start_1: Var = vf.add_var('ctrl.leadLag.x_start[1]_' + template_name)
    ctrl_leadLag_y_start: Var = vf.add_var('ctrl.leadLag.y_start_' + template_name)
    ctrl_limPID_Dzero_k: Var = vf.add_var('ctrl.limPID.Dzero.k_' + template_name)
    ctrl_limPID_FFzero_k: Var = vf.add_var('ctrl.limPID.FFzero.k_' + template_name)
    ctrl_limPID_I_initType: Var = vf.add_var('ctrl.limPID.I.initType_' + template_name)
    ctrl_limPID_I_k: Var = vf.add_var('ctrl.limPID.I.k_' + template_name)
    ctrl_limPID_I_use_reset: Var = vf.add_var('ctrl.limPID.I.use_reset_' + template_name)
    ctrl_limPID_I_use_set: Var = vf.add_var('ctrl.limPID.I.use_set_' + template_name)
    ctrl_limPID_I_y_start: Var = vf.add_var('ctrl.limPID.I.y_start_' + template_name)
    ctrl_limPID_Nd: Var = vf.add_var('ctrl.limPID.Nd_' + template_name)
    ctrl_limPID_Ni: Var = vf.add_var('ctrl.limPID.Ni_' + template_name)
    ctrl_limPID_P_k: Var = vf.add_var('ctrl.limPID.P.k_' + template_name)
    ctrl_limPID_Td: Var = vf.add_var('ctrl.limPID.Td_' + template_name)
    ctrl_limPID_Ti: Var = vf.add_var('ctrl.limPID.Ti_' + template_name)
    ctrl_limPID_addFF_k1: Var = vf.add_var('ctrl.limPID.addFF.k1_' + template_name)
    ctrl_limPID_addFF_k2: Var = vf.add_var('ctrl.limPID.addFF.k2_' + template_name)
    ctrl_limPID_addI_k1: Var = vf.add_var('ctrl.limPID.addI.k1_' + template_name)
    ctrl_limPID_addI_k2: Var = vf.add_var('ctrl.limPID.addI.k2_' + template_name)
    ctrl_limPID_addI_k3: Var = vf.add_var('ctrl.limPID.addI.k3_' + template_name)
    ctrl_limPID_addP_k1: Var = vf.add_var('ctrl.limPID.addP.k1_' + template_name)
    ctrl_limPID_addP_k2: Var = vf.add_var('ctrl.limPID.addP.k2_' + template_name)
    ctrl_limPID_addPID_k1: Var = vf.add_var('ctrl.limPID.addPID.k1_' + template_name)
    ctrl_limPID_addPID_k2: Var = vf.add_var('ctrl.limPID.addPID.k2_' + template_name)
    ctrl_limPID_addPID_k3: Var = vf.add_var('ctrl.limPID.addPID.k3_' + template_name)
    ctrl_limPID_addSat_k1: Var = vf.add_var('ctrl.limPID.addSat.k1_' + template_name)
    ctrl_limPID_addSat_k2: Var = vf.add_var('ctrl.limPID.addSat.k2_' + template_name)
    ctrl_limPID_controllerType: Var = vf.add_var('ctrl.limPID.controllerType_' + template_name)
    ctrl_limPID_gainPID_k: Var = vf.add_var('ctrl.limPID.gainPID.k_' + template_name)
    ctrl_limPID_gainTrack_k: Var = vf.add_var('ctrl.limPID.gainTrack.k_' + template_name)
    ctrl_limPID_homotopyType: Var = vf.add_var('ctrl.limPID.homotopyType_' + template_name)
    ctrl_limPID_initType: Var = vf.add_var('ctrl.limPID.initType_' + template_name)
    ctrl_limPID_k: Var = vf.add_var('ctrl.limPID.k_' + template_name)
    ctrl_limPID_kFF: Var = vf.add_var('ctrl.limPID.kFF_' + template_name)
    ctrl_limPID_limiter_homotopyType: Var = vf.add_var('ctrl.limPID.limiter.homotopyType_' + template_name)
    ctrl_limPID_limiter_limitsAtInit: Var = vf.add_var('ctrl.limPID.limiter.limitsAtInit_' + template_name)
    ctrl_limPID_limiter_strict: Var = vf.add_var('ctrl.limPID.limiter.strict_' + template_name)
    ctrl_limPID_limiter_uMax: Var = vf.add_var('ctrl.limPID.limiter.uMax_' + template_name)
    ctrl_limPID_limiter_uMin: Var = vf.add_var('ctrl.limPID.limiter.uMin_' + template_name)
    ctrl_limPID_limitsAtInit: Var = vf.add_var('ctrl.limPID.limitsAtInit_' + template_name)
    ctrl_limPID_strict: Var = vf.add_var('ctrl.limPID.strict_' + template_name)
    ctrl_limPID_unitTime: Var = vf.add_var('ctrl.limPID.unitTime_' + template_name)
    ctrl_limPID_wd: Var = vf.add_var('ctrl.limPID.wd_' + template_name)
    ctrl_limPID_withFeedForward: Var = vf.add_var('ctrl.limPID.withFeedForward_' + template_name)
    ctrl_limPID_with_D: Var = vf.add_var('ctrl.limPID.with_D_' + template_name)
    ctrl_limPID_with_I: Var = vf.add_var('ctrl.limPID.with_I_' + template_name)
    ctrl_limPID_wp: Var = vf.add_var('ctrl.limPID.wp_' + template_name)
    ctrl_limPID_xd_start: Var = vf.add_var('ctrl.limPID.xd_start_' + template_name)
    ctrl_limPID_xi_start: Var = vf.add_var('ctrl.limPID.xi_start_' + template_name)
    ctrl_limPID_yMax: Var = vf.add_var('ctrl.limPID.yMax_' + template_name)
    ctrl_limPID_yMin: Var = vf.add_var('ctrl.limPID.yMin_' + template_name)
    ctrl_limPID_y_start: Var = vf.add_var('ctrl.limPID.y_start_' + template_name)
    ctrl_limPIDFreeze_FFzero_k: Var = vf.add_var('ctrl.limPIDFreeze.FFzero.k_' + template_name)
    ctrl_limPIDFreeze_I_K: Var = vf.add_var('ctrl.limPIDFreeze.I.K_' + template_name)
    ctrl_limPIDFreeze_I_UseFreeze: Var = vf.add_var('ctrl.limPIDFreeze.I.UseFreeze_' + template_name)
    ctrl_limPIDFreeze_I_UseReset: Var = vf.add_var('ctrl.limPIDFreeze.I.UseReset_' + template_name)
    ctrl_limPIDFreeze_I_UseSet: Var = vf.add_var('ctrl.limPIDFreeze.I.UseSet_' + template_name)
    ctrl_limPIDFreeze_I_Y0: Var = vf.add_var('ctrl.limPIDFreeze.I.Y0_' + template_name)
    ctrl_limPIDFreeze_K: Var = vf.add_var('ctrl.limPIDFreeze.K_' + template_name)
    ctrl_limPIDFreeze_Kff: Var = vf.add_var('ctrl.limPIDFreeze.Kff_' + template_name)
    ctrl_limPIDFreeze_Ni: Var = vf.add_var('ctrl.limPIDFreeze.Ni_' + template_name)
    ctrl_limPIDFreeze_P_k: Var = vf.add_var('ctrl.limPIDFreeze.P.k_' + template_name)
    ctrl_limPIDFreeze_Strict: Var = vf.add_var('ctrl.limPIDFreeze.Strict_' + template_name)
    ctrl_limPIDFreeze_Ti: Var = vf.add_var('ctrl.limPIDFreeze.Ti_' + template_name)
    ctrl_limPIDFreeze_WithFeedForward: Var = vf.add_var('ctrl.limPIDFreeze.WithFeedForward_' + template_name)
    ctrl_limPIDFreeze_Wp: Var = vf.add_var('ctrl.limPIDFreeze.Wp_' + template_name)
    ctrl_limPIDFreeze_Xi0: Var = vf.add_var('ctrl.limPIDFreeze.Xi0_' + template_name)
    ctrl_limPIDFreeze_Y0: Var = vf.add_var('ctrl.limPIDFreeze.Y0_' + template_name)
    ctrl_limPIDFreeze_YMax: Var = vf.add_var('ctrl.limPIDFreeze.YMax_' + template_name)
    ctrl_limPIDFreeze_YMin: Var = vf.add_var('ctrl.limPIDFreeze.YMin_' + template_name)
    ctrl_limPIDFreeze_addFF_k1: Var = vf.add_var('ctrl.limPIDFreeze.addFF.k1_' + template_name)
    ctrl_limPIDFreeze_addFF_k2: Var = vf.add_var('ctrl.limPIDFreeze.addFF.k2_' + template_name)
    ctrl_limPIDFreeze_addI_k1: Var = vf.add_var('ctrl.limPIDFreeze.addI.k1_' + template_name)
    ctrl_limPIDFreeze_addI_k2: Var = vf.add_var('ctrl.limPIDFreeze.addI.k2_' + template_name)
    ctrl_limPIDFreeze_addI_k3: Var = vf.add_var('ctrl.limPIDFreeze.addI.k3_' + template_name)
    ctrl_limPIDFreeze_addP_k1: Var = vf.add_var('ctrl.limPIDFreeze.addP.k1_' + template_name)
    ctrl_limPIDFreeze_addP_k2: Var = vf.add_var('ctrl.limPIDFreeze.addP.k2_' + template_name)
    ctrl_limPIDFreeze_addPID_k1: Var = vf.add_var('ctrl.limPIDFreeze.addPID.k1_' + template_name)
    ctrl_limPIDFreeze_addPID_k2: Var = vf.add_var('ctrl.limPIDFreeze.addPID.k2_' + template_name)
    ctrl_limPIDFreeze_addSat_k1: Var = vf.add_var('ctrl.limPIDFreeze.addSat.k1_' + template_name)
    ctrl_limPIDFreeze_addSat_k2: Var = vf.add_var('ctrl.limPIDFreeze.addSat.k2_' + template_name)
    ctrl_limPIDFreeze_gainPID_k: Var = vf.add_var('ctrl.limPIDFreeze.gainPID.k_' + template_name)
    ctrl_limPIDFreeze_gainTrack_k: Var = vf.add_var('ctrl.limPIDFreeze.gainTrack.k_' + template_name)
    ctrl_limPIDFreeze_limiter_homotopyType: Var = vf.add_var('ctrl.limPIDFreeze.limiter.homotopyType_' + template_name)
    ctrl_limPIDFreeze_limiter_limitsAtInit: Var = vf.add_var('ctrl.limPIDFreeze.limiter.limitsAtInit_' + template_name)
    ctrl_limPIDFreeze_limiter_strict: Var = vf.add_var('ctrl.limPIDFreeze.limiter.strict_' + template_name)
    ctrl_limPIDFreeze_limiter_uMax: Var = vf.add_var('ctrl.limPIDFreeze.limiter.uMax_' + template_name)
    ctrl_limPIDFreeze_limiter_uMin: Var = vf.add_var('ctrl.limPIDFreeze.limiter.uMin_' + template_name)
    ctrl_limPIDFreeze_unitTime: Var = vf.add_var('ctrl.limPIDFreeze.unitTime_' + template_name)
    ctrl_limiter_homotopyType: Var = vf.add_var('ctrl.limiter.homotopyType_' + template_name)
    ctrl_limiter_limitsAtInit: Var = vf.add_var('ctrl.limiter.limitsAtInit_' + template_name)
    ctrl_limiter_strict: Var = vf.add_var('ctrl.limiter.strict_' + template_name)
    ctrl_limiter_uMax: Var = vf.add_var('ctrl.limiter.uMax_' + template_name)
    ctrl_limiter_uMin: Var = vf.add_var('ctrl.limiter.uMin_' + template_name)
    ctrl_limiter1_homotopyType: Var = vf.add_var('ctrl.limiter1.homotopyType_' + template_name)
    ctrl_limiter1_limitsAtInit: Var = vf.add_var('ctrl.limiter1.limitsAtInit_' + template_name)
    ctrl_limiter1_strict: Var = vf.add_var('ctrl.limiter1.strict_' + template_name)
    ctrl_limiter1_uMax: Var = vf.add_var('ctrl.limiter1.uMax_' + template_name)
    ctrl_limiter1_uMin: Var = vf.add_var('ctrl.limiter1.uMin_' + template_name)
    ctrl_lineDropCompensation1_RcPu: Var = vf.add_var('ctrl.lineDropCompensation1.RcPu_' + template_name)
    ctrl_lineDropCompensation1_XcPu: Var = vf.add_var('ctrl.lineDropCompensation1.XcPu_' + template_name)
    ctrl_tFilterPC: Var = vf.add_var('ctrl.tFilterPC_' + template_name)
    ctrl_tFt: Var = vf.add_var('ctrl.tFt_' + template_name)
    ctrl_tFv: Var = vf.add_var('ctrl.tFv_' + template_name)
    ctrl_tLag: Var = vf.add_var('ctrl.tLag_' + template_name)
    ctrl_tP: Var = vf.add_var('ctrl.tP_' + template_name)
    ctrl_u0Pu_im: Var = vf.add_var('ctrl.u0Pu.im_' + template_name)
    ctrl_u0Pu_re: Var = vf.add_var('ctrl.u0Pu.re_' + template_name)
    ctrl_voltageCheck_UMaxPu: Var = vf.add_var('ctrl.voltageCheck.UMaxPu_' + template_name)
    ctrl_voltageCheck_UMinPu: Var = vf.add_var('ctrl.voltageCheck.UMinPu_' + template_name)
    ctrl_wCtrlErr_k1: Var = vf.add_var('ctrl.wCtrlErr.k1_' + template_name)
    ctrl_wCtrlErr_k2: Var = vf.add_var('ctrl.wCtrlErr.k2_' + template_name)
    # Declare the state variables used by the template.
    ctrl_firstOrder_y: Var = vf.add_var('ctrl.firstOrder.y_' + template_name)
    ctrl_firstOrder1_y: Var = vf.add_var('ctrl.firstOrder1.y_' + template_name)
    ctrl_firstOrder2_y: Var = vf.add_var('ctrl.firstOrder2.y_' + template_name)
    ctrl_firstOrder3_y: Var = vf.add_var('ctrl.firstOrder3.y_' + template_name)
    ctrl_leadLag_x_scaled_1: Var = vf.add_var('ctrl.leadLag.x_scaled[1]_' + template_name)
    ctrl_limPID_I_y: Var = vf.add_var('ctrl.limPID.I.y_' + template_name)
    ctrl_limPIDFreeze_I_y: Var = vf.add_var('ctrl.limPIDFreeze.I.y_' + template_name)
    # Declare the algebraic/shared variables used by the template.
    START_ctrl_firstOrder_y: Var = vf.add_var('$START.ctrl.firstOrder.y_' + template_name)
    START_ctrl_firstOrder1_y: Var = vf.add_var('$START.ctrl.firstOrder1.y_' + template_name)
    START_ctrl_firstOrder2_y: Var = vf.add_var('$START.ctrl.firstOrder2.y_' + template_name)
    START_ctrl_firstOrder3_y: Var = vf.add_var('$START.ctrl.firstOrder3.y_' + template_name)
    START_ctrl_leadLag_x_scaled_1: Var = vf.add_var('$START.ctrl.leadLag.x_scaled[1]_' + template_name)
    START_ctrl_limPIDFreeze_I_y: Var = vf.add_var('$START.ctrl.limPIDFreeze.I.y_' + template_name)
    ctrl_PInjRefPu: Var = vf.add_var('ctrl.PInjRefPu_' + template_name)
    ctrl_PRefLim_simplifiedExpr: Var = vf.add_var('ctrl.PRefLim.simplifiedExpr_' + template_name)
    ctrl_PRefLim_y: Var = vf.add_var('ctrl.PRefLim.y_' + template_name)
    ctrl_PRefPu: Var = vf.add_var('ctrl.PRefPu_' + template_name)
    ctrl_PRegPu: Var = vf.add_var('ctrl.PRegPu_' + template_name)
    ctrl_QCtrlErr_y: Var = vf.add_var('ctrl.QCtrlErr.y_' + template_name)
    ctrl_QInjRefPu: Var = vf.add_var('ctrl.QInjRefPu_' + template_name)
    ctrl_QRefPu: Var = vf.add_var('ctrl.QRefPu_' + template_name)
    ctrl_QRegPu: Var = vf.add_var('ctrl.QRegPu_' + template_name)
    ctrl_QVErrLim_simplifiedExpr: Var = vf.add_var('ctrl.QVErrLim.simplifiedExpr_' + template_name)
    ctrl_QVErrLim_y: Var = vf.add_var('ctrl.QVErrLim.y_' + template_name)
    ctrl_UCtrlErr_y: Var = vf.add_var('ctrl.UCtrlErr.y_' + template_name)
    ctrl_URefPu: Var = vf.add_var('ctrl.URefPu_' + template_name)
    ctrl_add3_y: Var = vf.add_var('ctrl.add3.y_' + template_name)
    ctrl_dPfreq_y: Var = vf.add_var('ctrl.dPfreq.y_' + template_name)
    ctrl_deadZone_y: Var = vf.add_var('ctrl.deadZone.y_' + template_name)
    ctrl_deadZone1_y: Var = vf.add_var('ctrl.deadZone1.y_' + template_name)
    ctrl_freeze: Var = vf.add_var('ctrl.freeze_' + template_name)
    ctrl_gain_y: Var = vf.add_var('ctrl.gain.y_' + template_name)
    ctrl_gain1_y: Var = vf.add_var('ctrl.gain1.y_' + template_name)
    ctrl_gain2_y: Var = vf.add_var('ctrl.gain2.y_' + template_name)
    ctrl_iPu_im: Var = vf.add_var('ctrl.iPu.im_' + template_name)
    ctrl_iPu_re: Var = vf.add_var('ctrl.iPu.re_' + template_name)
    ctrl_leadLag_x_1: Var = vf.add_var('ctrl.leadLag.x[1]_' + template_name)
    ctrl_limPID_I_local_reset: Var = vf.add_var('ctrl.limPID.I.local_reset_' + template_name)
    ctrl_limPID_I_local_set: Var = vf.add_var('ctrl.limPID.I.local_set_' + template_name)
    ctrl_limPID_P_y: Var = vf.add_var('ctrl.limPID.P.y_' + template_name)
    ctrl_limPID_addI_y: Var = vf.add_var('ctrl.limPID.addI.y_' + template_name)
    ctrl_limPID_addP_y: Var = vf.add_var('ctrl.limPID.addP.y_' + template_name)
    ctrl_limPID_addPID_y: Var = vf.add_var('ctrl.limPID.addPID.y_' + template_name)
    ctrl_limPID_addSat_y: Var = vf.add_var('ctrl.limPID.addSat.y_' + template_name)
    ctrl_limPID_controlError: Var = vf.add_var('ctrl.limPID.controlError_' + template_name)
    ctrl_limPID_gainPID_y: Var = vf.add_var('ctrl.limPID.gainPID.y_' + template_name)
    ctrl_limPID_gainTrack_y: Var = vf.add_var('ctrl.limPID.gainTrack.y_' + template_name)
    ctrl_limPID_limiter_u: Var = vf.add_var('ctrl.limPID.limiter.u_' + template_name)
    ctrl_limPID_y: Var = vf.add_var('ctrl.limPID.y_' + template_name)
    ctrl_limPIDFreeze_I_resetLocal: Var = vf.add_var('ctrl.limPIDFreeze.I.resetLocal_' + template_name)
    ctrl_limPIDFreeze_I_setLocal: Var = vf.add_var('ctrl.limPIDFreeze.I.setLocal_' + template_name)
    ctrl_limPIDFreeze_P_y: Var = vf.add_var('ctrl.limPIDFreeze.P.y_' + template_name)
    ctrl_limPIDFreeze_addFF_y: Var = vf.add_var('ctrl.limPIDFreeze.addFF.y_' + template_name)
    ctrl_limPIDFreeze_addI_y: Var = vf.add_var('ctrl.limPIDFreeze.addI.y_' + template_name)
    ctrl_limPIDFreeze_addP_y: Var = vf.add_var('ctrl.limPIDFreeze.addP.y_' + template_name)
    ctrl_limPIDFreeze_addPID_y: Var = vf.add_var('ctrl.limPIDFreeze.addPID.y_' + template_name)
    ctrl_limPIDFreeze_addSat_y: Var = vf.add_var('ctrl.limPIDFreeze.addSat.y_' + template_name)
    ctrl_limPIDFreeze_controlError: Var = vf.add_var('ctrl.limPIDFreeze.controlError_' + template_name)
    ctrl_limPIDFreeze_gainPID_y: Var = vf.add_var('ctrl.limPIDFreeze.gainPID.y_' + template_name)
    ctrl_limPIDFreeze_gainTrack_y: Var = vf.add_var('ctrl.limPIDFreeze.gainTrack.y_' + template_name)
    ctrl_limPIDFreeze_limiter_simplifiedExpr: Var = vf.add_var('ctrl.limPIDFreeze.limiter.simplifiedExpr_' + template_name)
    ctrl_limPIDFreeze_y: Var = vf.add_var('ctrl.limPIDFreeze.y_' + template_name)
    ctrl_limiter_simplifiedExpr: Var = vf.add_var('ctrl.limiter.simplifiedExpr_' + template_name)
    ctrl_limiter_y: Var = vf.add_var('ctrl.limiter.y_' + template_name)
    ctrl_limiter1_simplifiedExpr: Var = vf.add_var('ctrl.limiter1.simplifiedExpr_' + template_name)
    ctrl_limiter1_y: Var = vf.add_var('ctrl.limiter1.y_' + template_name)
    ctrl_lineDropCompensation1_U1Pu: Var = vf.add_var('ctrl.lineDropCompensation1.U1Pu_' + template_name)
    ctrl_lineDropCompensation1_U2Pu: Var = vf.add_var('ctrl.lineDropCompensation1.U2Pu_' + template_name)
    ctrl_omegaPu: Var = vf.add_var('ctrl.omegaPu_' + template_name)
    ctrl_omegaRefPu: Var = vf.add_var('ctrl.omegaRefPu_' + template_name)
    ctrl_switch1_y: Var = vf.add_var('ctrl.switch1.y_' + template_name)
    ctrl_switch2_y: Var = vf.add_var('ctrl.switch2.y_' + template_name)
    ctrl_uPu_im: Var = vf.add_var('ctrl.uPu.im_' + template_name)
    ctrl_uPu_re: Var = vf.add_var('ctrl.uPu.re_' + template_name)
    ctrl_wCtrlErr_y: Var = vf.add_var('ctrl.wCtrlErr.y_' + template_name)
    # Declare the differential variables used by the template.
    d_ctrl_firstOrder_y: Var = vf.add_diff_var('d_ctrl.firstOrder.y_' + template_name, base_var=ctrl_firstOrder_y)
    d_ctrl_firstOrder1_y: Var = vf.add_diff_var('d_ctrl.firstOrder1.y_' + template_name, base_var=ctrl_firstOrder1_y)
    d_ctrl_firstOrder2_y: Var = vf.add_diff_var('d_ctrl.firstOrder2.y_' + template_name, base_var=ctrl_firstOrder2_y)
    d_ctrl_firstOrder3_y: Var = vf.add_diff_var('d_ctrl.firstOrder3.y_' + template_name, base_var=ctrl_firstOrder3_y)
    d_ctrl_leadLag_x_scaled_1: Var = vf.add_diff_var('d_ctrl.leadLag.x_scaled[1]_' + template_name, base_var=ctrl_leadLag_x_scaled_1)
    d_ctrl_limPID_I_y: Var = vf.add_diff_var('d_ctrl.limPID.I.y_' + template_name, base_var=ctrl_limPID_I_y)
    d_ctrl_limPIDFreeze_I_y: Var = vf.add_diff_var('d_ctrl.limPIDFreeze.I.y_' + template_name, base_var=ctrl_limPIDFreeze_I_y)

    # Build explicit typed collections so the symbolic surface is easy to inspect.
    state_equations: list[Expr] = list()
    state_equations.append((((ctrl_firstOrder_k * ctrl_limPID_y) - ctrl_firstOrder_y) / ctrl_firstOrder_T))
    state_equations.append((ctrl_limPID_I_k * ctrl_limPID_addI_y))
    state_equations.append((((sym.Const(0.8) * ctrl_firstOrder1_k) - ctrl_firstOrder1_y) / ctrl_firstOrder1_T))
    state_equations.append(((-ctrl_firstOrder2_y) / ctrl_firstOrder2_T))
    state_equations.append((((ctrl_leadLag_a_end * ctrl_limPIDFreeze_y) - (ctrl_leadLag_a_2 * ctrl_leadLag_x_scaled_1)) / ctrl_leadLag_a_1))
    state_equations.append(((ctrl_freeze * sym.Const(0.0)) + ((sym.Const(1.0) - ctrl_freeze) * (ctrl_limPIDFreeze_I_K * ctrl_limPIDFreeze_addI_y))))
    state_equations.append((((ctrl_firstOrder3_k * ctrl_switch2_y) - ctrl_firstOrder3_y) / ctrl_firstOrder3_T))
    state_variables: list[Var] = list()
    state_variables.append(ctrl_firstOrder_y)
    state_variables.append(ctrl_limPID_I_y)
    state_variables.append(ctrl_firstOrder1_y)
    state_variables.append(ctrl_firstOrder2_y)
    state_variables.append(ctrl_leadLag_x_scaled_1)
    state_variables.append(ctrl_limPIDFreeze_I_y)
    state_variables.append(ctrl_firstOrder3_y)
    algebraic_equations: list[Expr] = list()
    algebraic_equations.append((ctrl_deadZone1_y - ((sym.heaviside(((ctrl_wCtrlErr_y - ctrl_deadZone1_uMax) - sym.Const(1e-06))) * (ctrl_wCtrlErr_y - ctrl_deadZone1_uMax)) + ((sym.Const(1.0) - sym.heaviside(((ctrl_wCtrlErr_y - ctrl_deadZone1_uMax) - sym.Const(1e-06)))) * ((sym.heaviside(((ctrl_deadZone1_uMin - ctrl_wCtrlErr_y) - sym.Const(1e-06))) * (ctrl_wCtrlErr_y - ctrl_deadZone1_uMin)) + ((sym.Const(1.0) - sym.heaviside(((ctrl_deadZone1_uMin - ctrl_wCtrlErr_y) - sym.Const(1e-06)))) * sym.Const(0.0)))))))
    algebraic_equations.append((ctrl_gain1_y - (ctrl_gain1_k * ctrl_deadZone1_y)))
    algebraic_equations.append((ctrl_gain2_y - (ctrl_gain2_k * ctrl_deadZone1_y)))
    algebraic_equations.append((ctrl_limiter_y - ((sym.heaviside(((ctrl_gain1_y - ctrl_limiter_uMax) - sym.Const(1e-06))) * ctrl_limiter_uMax) + ((sym.Const(1.0) - sym.heaviside(((ctrl_gain1_y - ctrl_limiter_uMax) - sym.Const(1e-06)))) * ((sym.heaviside(((ctrl_limiter_uMin - ctrl_gain1_y) - sym.Const(1e-06))) * ctrl_limiter_uMin) + ((sym.Const(1.0) - sym.heaviside(((ctrl_limiter_uMin - ctrl_gain1_y) - sym.Const(1e-06)))) * ctrl_gain1_y))))))
    algebraic_equations.append((ctrl_limiter1_y - ((sym.heaviside(((ctrl_gain2_y - ctrl_limiter1_uMax) - sym.Const(1e-06))) * ctrl_limiter1_uMax) + ((sym.Const(1.0) - sym.heaviside(((ctrl_gain2_y - ctrl_limiter1_uMax) - sym.Const(1e-06)))) * ((sym.heaviside(((ctrl_limiter1_uMin - ctrl_gain2_y) - sym.Const(1e-06))) * ctrl_limiter1_uMin) + ((sym.Const(1.0) - sym.heaviside(((ctrl_limiter1_uMin - ctrl_gain2_y) - sym.Const(1e-06)))) * ctrl_gain2_y))))))
    algebraic_equations.append((ctrl_dPfreq_y - ((ctrl_dPfreq_k1 * ctrl_limiter_y) + (ctrl_dPfreq_k2 * ctrl_limiter1_y))))
    algebraic_equations.append((ctrl_switch2_y - ((ctrl_VCompFlag0_k * ctrl_lineDropCompensation1_U1Pu) + ((sym.Const(1.0) - ctrl_VCompFlag0_k) * ctrl_QVCtrlErr_k1))))
    algebraic_equations.append((ctrl_add3_y - ((sym.Const(0.8) * ctrl_add3_k1) + ((ctrl_add3_k2 * ctrl_firstOrder1_y) + (ctrl_add3_k3 * ctrl_dPfreq_y)))))
    algebraic_equations.append((ctrl_PRefLim_y - ((sym.heaviside(((ctrl_add3_y - ctrl_PRefLim_uMax) - sym.Const(1e-06))) * ctrl_PRefLim_uMax) + ((sym.Const(1.0) - sym.heaviside(((ctrl_add3_y - ctrl_PRefLim_uMax) - sym.Const(1e-06)))) * ((sym.heaviside(((ctrl_PRefLim_uMin - ctrl_add3_y) - sym.Const(1e-06))) * ctrl_PRefLim_uMin) + ((sym.Const(1.0) - sym.heaviside(((ctrl_PRefLim_uMin - ctrl_add3_y) - sym.Const(1e-06)))) * ctrl_add3_y))))))
    algebraic_equations.append((ctrl_limPID_addP_y - ((ctrl_limPID_addP_k1 * ctrl_PRefLim_y) + (ctrl_limPID_addP_k2 * ctrl_Zero_k))))
    algebraic_equations.append((ctrl_limPID_P_y - (ctrl_limPID_P_k * ctrl_limPID_addP_y)))
    algebraic_equations.append((ctrl_limPID_addPID_y - ((ctrl_limPID_addPID_k1 * ctrl_limPID_P_y) + ((ctrl_limPID_addPID_k2 * ctrl_limPID_Dzero_k) + (ctrl_limPID_addPID_k3 * ctrl_limPID_I_y)))))
    algebraic_equations.append((ctrl_limPID_gainPID_y - (ctrl_limPID_gainPID_k * ctrl_limPID_addPID_y)))
    algebraic_equations.append((ctrl_limPID_limiter_u - ((ctrl_limPID_addFF_k1 * ctrl_limPID_gainPID_y) + (ctrl_limPID_addFF_k2 * ctrl_limPID_FFzero_k))))
    algebraic_equations.append((ctrl_limPID_y - ((sym.heaviside(((ctrl_limPID_limiter_u - ctrl_limPID_limiter_uMax) - sym.Const(1e-06))) * ctrl_limPID_limiter_uMax) + ((sym.Const(1.0) - sym.heaviside(((ctrl_limPID_limiter_u - ctrl_limPID_limiter_uMax) - sym.Const(1e-06)))) * ((sym.heaviside(((ctrl_limPID_limiter_uMin - ctrl_limPID_limiter_u) - sym.Const(1e-06))) * ctrl_limPID_limiter_uMin) + ((sym.Const(1.0) - sym.heaviside(((ctrl_limPID_limiter_uMin - ctrl_limPID_limiter_u) - sym.Const(1e-06)))) * ctrl_limPID_limiter_u))))))
    algebraic_equations.append((ctrl_limPID_addSat_y - ((ctrl_limPID_addSat_k1 * ctrl_limPID_y) + (ctrl_limPID_addSat_k2 * ctrl_limPID_limiter_u))))
    algebraic_equations.append((ctrl_limPID_gainTrack_y - (ctrl_limPID_gainTrack_k * ctrl_limPID_addSat_y)))
    algebraic_equations.append((ctrl_limPID_addI_y - ((ctrl_limPID_addI_k1 * ctrl_PRefLim_y) + ((ctrl_limPID_addI_k2 * ctrl_Zero_k) + (ctrl_limPID_addI_k3 * ctrl_limPID_gainTrack_y)))))
    algebraic_equations.append((ctrl_limPID_controlError - (ctrl_PRefLim_y - ctrl_Zero_k)))
    algebraic_equations.append((ctrl_PInjRefPu - ((ctrl_FreqFlag0_k * ctrl_firstOrder_y) + ((sym.Const(1.0) - ctrl_FreqFlag0_k) * ctrl_const_k))))
    algebraic_equations.append((ctrl_QCtrlErr_y - ((ctrl_QCtrlErr_k1 * ctrl_firstOrder2_y) + (ctrl_QCtrlErr_k2 * ctrl_QRefPu))))
    algebraic_equations.append((ctrl_UCtrlErr_y - ((ctrl_UCtrlErr_k1 * ctrl_URefPu) + (ctrl_UCtrlErr_k2 * ctrl_firstOrder3_y))))
    algebraic_equations.append((ctrl_switch1_y - ((ctrl_RefFlag0_k * ctrl_UCtrlErr_y) + ((sym.Const(1.0) - ctrl_RefFlag0_k) * ctrl_QCtrlErr_y))))
    algebraic_equations.append((ctrl_deadZone_y - ((sym.heaviside(((ctrl_switch1_y - ctrl_deadZone_uMax) - sym.Const(1e-06))) * (ctrl_switch1_y - ctrl_deadZone_uMax)) + ((sym.Const(1.0) - sym.heaviside(((ctrl_switch1_y - ctrl_deadZone_uMax) - sym.Const(1e-06)))) * ((sym.heaviside(((ctrl_deadZone_uMin - ctrl_switch1_y) - sym.Const(1e-06))) * (ctrl_switch1_y - ctrl_deadZone_uMin)) + ((sym.Const(1.0) - sym.heaviside(((ctrl_deadZone_uMin - ctrl_switch1_y) - sym.Const(1e-06)))) * sym.Const(0.0)))))))
    algebraic_equations.append((ctrl_QVErrLim_y - ((sym.heaviside(((ctrl_deadZone_y - ctrl_QVErrLim_uMax) - sym.Const(1e-06))) * ctrl_QVErrLim_uMax) + ((sym.Const(1.0) - sym.heaviside(((ctrl_deadZone_y - ctrl_QVErrLim_uMax) - sym.Const(1e-06)))) * ((sym.heaviside(((ctrl_QVErrLim_uMin - ctrl_deadZone_y) - sym.Const(1e-06))) * ctrl_QVErrLim_uMin) + ((sym.Const(1.0) - sym.heaviside(((ctrl_QVErrLim_uMin - ctrl_deadZone_y) - sym.Const(1e-06)))) * ctrl_deadZone_y))))))
    algebraic_equations.append((ctrl_limPIDFreeze_addP_y - ((ctrl_limPIDFreeze_addP_k1 * ctrl_QVErrLim_y) + (ctrl_limPIDFreeze_addP_k2 * ctrl_Zero1_k))))
    algebraic_equations.append((ctrl_limPIDFreeze_P_y - (ctrl_limPIDFreeze_P_k * ctrl_limPIDFreeze_addP_y)))
    algebraic_equations.append((ctrl_limPIDFreeze_addPID_y - ((ctrl_limPIDFreeze_addPID_k1 * ctrl_limPIDFreeze_P_y) + (ctrl_limPIDFreeze_addPID_k2 * ctrl_limPIDFreeze_I_y))))
    algebraic_equations.append((ctrl_limPIDFreeze_gainPID_y - (ctrl_limPIDFreeze_gainPID_k * ctrl_limPIDFreeze_addPID_y)))
    algebraic_equations.append((ctrl_limPIDFreeze_addFF_y - ((ctrl_limPIDFreeze_addFF_k1 * ctrl_limPIDFreeze_gainPID_y) + (ctrl_limPIDFreeze_addFF_k2 * ctrl_limPIDFreeze_FFzero_k))))
    algebraic_equations.append((ctrl_limPIDFreeze_y - ((sym.heaviside(((ctrl_limPIDFreeze_addFF_y - ctrl_limPIDFreeze_limiter_uMax) - sym.Const(1e-06))) * ctrl_limPIDFreeze_limiter_uMax) + ((sym.Const(1.0) - sym.heaviside(((ctrl_limPIDFreeze_addFF_y - ctrl_limPIDFreeze_limiter_uMax) - sym.Const(1e-06)))) * ((sym.heaviside(((ctrl_limPIDFreeze_limiter_uMin - ctrl_limPIDFreeze_addFF_y) - sym.Const(1e-06))) * ctrl_limPIDFreeze_limiter_uMin) + ((sym.Const(1.0) - sym.heaviside(((ctrl_limPIDFreeze_limiter_uMin - ctrl_limPIDFreeze_addFF_y) - sym.Const(1e-06)))) * ctrl_limPIDFreeze_addFF_y))))))
    algebraic_equations.append((ctrl_limPIDFreeze_addSat_y - ((ctrl_limPIDFreeze_addSat_k1 * ctrl_limPIDFreeze_y) + (ctrl_limPIDFreeze_addSat_k2 * ctrl_limPIDFreeze_addFF_y))))
    algebraic_equations.append((ctrl_limPIDFreeze_gainTrack_y - (ctrl_limPIDFreeze_gainTrack_k * ctrl_limPIDFreeze_addSat_y)))
    algebraic_equations.append((ctrl_limPIDFreeze_addI_y - ((ctrl_limPIDFreeze_addI_k1 * ctrl_QVErrLim_y) + ((ctrl_limPIDFreeze_addI_k2 * ctrl_Zero1_k) + (ctrl_limPIDFreeze_addI_k3 * ctrl_limPIDFreeze_gainTrack_y)))))
    algebraic_equations.append((ctrl_limPIDFreeze_controlError - (ctrl_QVErrLim_y - ctrl_Zero1_k)))
    algebraic_equations.append((ctrl_leadLag_x_1 - (ctrl_leadLag_x_scaled_1 / ctrl_leadLag_a_end)))
    algebraic_equations.append((ctrl_QInjRefPu - (((ctrl_leadLag_bb_2 - (ctrl_leadLag_d * ctrl_leadLag_a_2)) * ctrl_leadLag_x_1) + (ctrl_leadLag_d * ctrl_limPIDFreeze_y))))
    algebraic_variables: list[Var] = list()
    algebraic_variables.append(ctrl_deadZone1_y)
    algebraic_variables.append(ctrl_gain1_y)
    algebraic_variables.append(ctrl_gain2_y)
    algebraic_variables.append(ctrl_limiter_y)
    algebraic_variables.append(ctrl_limiter1_y)
    algebraic_variables.append(ctrl_dPfreq_y)
    algebraic_variables.append(ctrl_switch2_y)
    algebraic_variables.append(ctrl_add3_y)
    algebraic_variables.append(ctrl_PRefLim_y)
    algebraic_variables.append(ctrl_limPID_addP_y)
    algebraic_variables.append(ctrl_limPID_P_y)
    algebraic_variables.append(ctrl_limPID_addPID_y)
    algebraic_variables.append(ctrl_limPID_gainPID_y)
    algebraic_variables.append(ctrl_limPID_limiter_u)
    algebraic_variables.append(ctrl_limPID_y)
    algebraic_variables.append(ctrl_limPID_addSat_y)
    algebraic_variables.append(ctrl_limPID_gainTrack_y)
    algebraic_variables.append(ctrl_limPID_addI_y)
    algebraic_variables.append(ctrl_limPID_controlError)
    algebraic_variables.append(ctrl_PInjRefPu)
    algebraic_variables.append(ctrl_QCtrlErr_y)
    algebraic_variables.append(ctrl_UCtrlErr_y)
    algebraic_variables.append(ctrl_switch1_y)
    algebraic_variables.append(ctrl_deadZone_y)
    algebraic_variables.append(ctrl_QVErrLim_y)
    algebraic_variables.append(ctrl_limPIDFreeze_addP_y)
    algebraic_variables.append(ctrl_limPIDFreeze_P_y)
    algebraic_variables.append(ctrl_limPIDFreeze_addPID_y)
    algebraic_variables.append(ctrl_limPIDFreeze_gainPID_y)
    algebraic_variables.append(ctrl_limPIDFreeze_addFF_y)
    algebraic_variables.append(ctrl_limPIDFreeze_y)
    algebraic_variables.append(ctrl_limPIDFreeze_addSat_y)
    algebraic_variables.append(ctrl_limPIDFreeze_gainTrack_y)
    algebraic_variables.append(ctrl_limPIDFreeze_addI_y)
    algebraic_variables.append(ctrl_limPIDFreeze_controlError)
    algebraic_variables.append(ctrl_leadLag_x_1)
    algebraic_variables.append(ctrl_QInjRefPu)
    algebraic_variables.append(ctrl_wCtrlErr_y)
    algebraic_variables.append(ctrl_lineDropCompensation1_U1Pu)
    algebraic_variables.append(ctrl_freeze)
    algebraic_variables.append(ctrl_PRefPu)
    algebraic_variables.append(ctrl_PRegPu)
    algebraic_variables.append(ctrl_QRefPu)
    algebraic_variables.append(ctrl_QRegPu)
    algebraic_variables.append(ctrl_URefPu)
    algebraic_variables.append(ctrl_iPu_im)
    algebraic_variables.append(ctrl_iPu_re)
    algebraic_variables.append(ctrl_omegaPu)
    algebraic_variables.append(ctrl_omegaRefPu)
    algebraic_variables.append(ctrl_uPu_im)
    algebraic_variables.append(ctrl_uPu_re)
    algebraic_variables.append(ctrl_PRefLim_simplifiedExpr)
    algebraic_variables.append(ctrl_limPID_I_local_reset)
    algebraic_variables.append(ctrl_limPID_I_local_set)
    algebraic_variables.append(ctrl_QVErrLim_simplifiedExpr)
    algebraic_variables.append(ctrl_limiter_simplifiedExpr)
    algebraic_variables.append(ctrl_limiter1_simplifiedExpr)
    algebraic_variables.append(ctrl_limPIDFreeze_limiter_simplifiedExpr)
    algebraic_variables.append(ctrl_limPIDFreeze_I_resetLocal)
    algebraic_variables.append(ctrl_limPIDFreeze_I_setLocal)
    algebraic_variables.append(START_ctrl_firstOrder_y)
    algebraic_variables.append(START_ctrl_firstOrder1_y)
    algebraic_variables.append(START_ctrl_firstOrder2_y)
    algebraic_variables.append(START_ctrl_firstOrder3_y)
    algebraic_variables.append(START_ctrl_limPIDFreeze_I_y)
    algebraic_variables.append(START_ctrl_leadLag_x_scaled_1)
    algebraic_variables.append(ctrl_gain_y)
    algebraic_variables.append(ctrl_lineDropCompensation1_U2Pu)
    differential_variables: list[Var] = list()
    differential_variables.append(d_ctrl_firstOrder_y)
    differential_variables.append(d_ctrl_limPID_I_y)
    differential_variables.append(d_ctrl_firstOrder1_y)
    differential_variables.append(d_ctrl_firstOrder2_y)
    differential_variables.append(d_ctrl_leadLag_x_scaled_1)
    differential_variables.append(d_ctrl_limPIDFreeze_I_y)
    differential_variables.append(d_ctrl_firstOrder3_y)
    input_variables: list[Var] = list()
    output_variables: list[Var] = list()
    event_parameters: dict[Var, Expr | Const] = dict()
    event_parameters[ctrl_DDn] = vf.add_const(20.0, name='')
    event_parameters[ctrl_DUp] = vf.add_const(0.0, name='')
    event_parameters[ctrl_DbdPu] = vf.add_const(0.0, name='')
    event_parameters[ctrl_EMaxPu] = vf.add_const(0.1, name='')
    event_parameters[ctrl_EMinPu] = vf.add_const(-0.1, name='')
    event_parameters[ctrl_FDbd1Pu] = vf.add_const(0.004, name='')
    event_parameters[ctrl_FDbd2Pu] = vf.add_const(0.004, name='')
    event_parameters[ctrl_FEMaxPu] = vf.add_const(0.1, name='')
    event_parameters[ctrl_FEMinPu] = vf.add_const(-0.1, name='')
    event_parameters[ctrl_Kc] = vf.add_const(0.0, name='')
    event_parameters[ctrl_Ki] = vf.add_const(10.0, name='')
    event_parameters[ctrl_Kig] = vf.add_const(10.0, name='')
    event_parameters[ctrl_Kp] = vf.add_const(1.0, name='')
    event_parameters[ctrl_Kpg] = vf.add_const(1.0, name='')
    event_parameters[ctrl_PGen0Pu] = vf.add_const(0.8, name='')
    event_parameters[ctrl_PInj0Pu] = vf.add_const(0.8, name='')
    event_parameters[ctrl_PMaxPu] = vf.add_const(1.0, name='')
    event_parameters[ctrl_PMinPu] = vf.add_const(0.0, name='')
    event_parameters[ctrl_PRefLim_uMax] = ctrl_FEMaxPu
    event_parameters[ctrl_PRefLim_uMin] = ctrl_FEMinPu
    event_parameters[ctrl_QCtrlErr_k1] = vf.add_const(-1.0, name='')
    event_parameters[ctrl_QCtrlErr_k2] = vf.add_const(1.0, name='')
    event_parameters[ctrl_QGen0Pu] = vf.add_const(0.0, name='')
    event_parameters[ctrl_QInj0Pu] = vf.add_const(0.0, name='')
    event_parameters[ctrl_QMaxPu] = vf.add_const(0.4, name='')
    event_parameters[ctrl_QMinPu] = vf.add_const(-0.4, name='')
    event_parameters[ctrl_QVCtrlErr_k1] = vf.add_const(1.0, name='')
    event_parameters[ctrl_QVCtrlErr_k2] = vf.add_const(1.0, name='')
    event_parameters[ctrl_QVErrLim_uMax] = ctrl_EMaxPu
    event_parameters[ctrl_QVErrLim_uMin] = ctrl_EMinPu
    event_parameters[ctrl_RcPu] = vf.add_const(0.0, name='')
    event_parameters[ctrl_U0Pu] = vf.add_const(1.0, name='')
    event_parameters[ctrl_UCtrlErr_k1] = vf.add_const(1.0, name='')
    event_parameters[ctrl_UCtrlErr_k2] = vf.add_const(-1.0, name='')
    event_parameters[ctrl_UInj0Pu] = vf.add_const(1.0, name='')
    event_parameters[ctrl_URef0Pu] = ((ctrl_VCompFlag * ctrl_UInj0Pu) + ((sym.Const(1.0) - ctrl_VCompFlag) * (ctrl_U0Pu + (ctrl_Kc * ctrl_QGen0Pu))))
    event_parameters[ctrl_VFrz] = vf.add_const(0.7, name='')
    event_parameters[ctrl_XcPu] = vf.add_const(0.0, name='')
    event_parameters[ctrl_Zero_k] = vf.add_const(0.0, name='')
    event_parameters[ctrl_Zero1_k] = vf.add_const(0.0, name='')
    event_parameters[ctrl_add3_k1] = vf.add_const(1.0, name='')
    event_parameters[ctrl_add3_k2] = vf.add_const(-1.0, name='')
    event_parameters[ctrl_add3_k3] = vf.add_const(1.0, name='')
    event_parameters[ctrl_const_k] = vf.add_const(0.8, name='')
    event_parameters[ctrl_dPfreq_k1] = vf.add_const(1.0, name='')
    event_parameters[ctrl_dPfreq_k2] = vf.add_const(1.0, name='')
    event_parameters[ctrl_deadZone_uMax] = ctrl_DbdPu
    event_parameters[ctrl_deadZone_uMin] = (-ctrl_DbdPu)
    event_parameters[ctrl_deadZone1_uMax] = ctrl_FDbd2Pu
    event_parameters[ctrl_deadZone1_uMin] = (-ctrl_FDbd1Pu)
    event_parameters[ctrl_firstOrder_T] = ctrl_tLag
    event_parameters[ctrl_firstOrder_k] = vf.add_const(1.0, name='')
    event_parameters[ctrl_firstOrder_y_start] = vf.add_const(0.8, name='')
    event_parameters[ctrl_firstOrder1_T] = ctrl_tP
    event_parameters[ctrl_firstOrder1_k] = vf.add_const(1.0, name='')
    event_parameters[ctrl_firstOrder1_y_start] = ctrl_PGen0Pu
    event_parameters[ctrl_firstOrder2_T] = ctrl_tFilterPC
    event_parameters[ctrl_firstOrder2_k] = vf.add_const(1.0, name='')
    event_parameters[ctrl_firstOrder2_y_start] = ctrl_QGen0Pu
    event_parameters[ctrl_firstOrder3_T] = ctrl_tFilterPC
    event_parameters[ctrl_firstOrder3_k] = vf.add_const(1.0, name='')
    event_parameters[ctrl_firstOrder3_y_start] = ((ctrl_VCompFlag * ctrl_UInj0Pu) + ((sym.Const(1.0) - ctrl_VCompFlag) * (ctrl_U0Pu + (ctrl_Kc * ctrl_QGen0Pu))))
    event_parameters[ctrl_gain_k] = ctrl_Kc
    event_parameters[ctrl_gain1_k] = ctrl_DDn
    event_parameters[ctrl_gain2_k] = ctrl_DUp
    event_parameters[ctrl_iInj0Pu_im] = vf.add_const(0.0, name='')
    event_parameters[ctrl_iInj0Pu_re] = vf.add_const(0.8, name='')
    event_parameters[ctrl_leadLag_a_1] = ctrl_tFv
    event_parameters[ctrl_leadLag_a_2] = vf.add_const(1.0, name='')
    event_parameters[ctrl_leadLag_a_end] = ((sym.heaviside(((ctrl_leadLag_a_2 - (sym.Const(2.220446049250313e-14) * sym.sqrt(((ctrl_leadLag_a_1 ** sym.Const(2.0)) + (ctrl_leadLag_a_2 ** sym.Const(2.0)))))) - sym.Const(1e-06))) * ctrl_leadLag_a_2) + ((sym.Const(1.0) - sym.heaviside(((ctrl_leadLag_a_2 - (sym.Const(2.220446049250313e-14) * sym.sqrt(((ctrl_leadLag_a_1 ** sym.Const(2.0)) + (ctrl_leadLag_a_2 ** sym.Const(2.0)))))) - sym.Const(1e-06)))) * sym.Const(1.0)))
    event_parameters[ctrl_leadLag_b_1] = ctrl_tFt
    event_parameters[ctrl_leadLag_b_2] = vf.add_const(1.0, name='')
    event_parameters[ctrl_leadLag_bb_1] = ctrl_leadLag_b_1
    event_parameters[ctrl_leadLag_bb_2] = ctrl_leadLag_b_2
    event_parameters[ctrl_leadLag_d] = (ctrl_leadLag_bb_1 / ctrl_leadLag_a_1)
    event_parameters[ctrl_leadLag_x_start_1] = ctrl_QInj0Pu
    event_parameters[ctrl_leadLag_y_start] = ctrl_QInj0Pu
    event_parameters[ctrl_limPID_Dzero_k] = vf.add_const(0.0, name='')
    event_parameters[ctrl_limPID_FFzero_k] = vf.add_const(0.0, name='')
    event_parameters[ctrl_limPID_I_k] = (sym.Const(1.0) / ctrl_limPID_Ti)
    event_parameters[ctrl_limPID_I_y_start] = ctrl_limPID_xi_start
    event_parameters[ctrl_limPID_Nd] = vf.add_const(10.0, name='')
    event_parameters[ctrl_limPID_Ni] = vf.add_const(0.9, name='')
    event_parameters[ctrl_limPID_P_k] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limPID_Td] = vf.add_const(0.1, name='')
    event_parameters[ctrl_limPID_Ti] = (ctrl_Kpg / ctrl_Kig)
    event_parameters[ctrl_limPID_addFF_k1] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limPID_addFF_k2] = ctrl_limPID_kFF
    event_parameters[ctrl_limPID_addI_k1] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limPID_addI_k2] = vf.add_const(-1.0, name='')
    event_parameters[ctrl_limPID_addI_k3] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limPID_addP_k1] = ctrl_limPID_wp
    event_parameters[ctrl_limPID_addP_k2] = vf.add_const(-1.0, name='')
    event_parameters[ctrl_limPID_addPID_k1] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limPID_addPID_k2] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limPID_addPID_k3] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limPID_addSat_k1] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limPID_addSat_k2] = vf.add_const(-1.0, name='')
    event_parameters[ctrl_limPID_gainPID_k] = ctrl_limPID_k
    event_parameters[ctrl_limPID_gainTrack_k] = (sym.Const(1.0) / (ctrl_limPID_Ni * ctrl_limPID_k))
    event_parameters[ctrl_limPID_k] = ctrl_Kpg
    event_parameters[ctrl_limPID_kFF] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limPID_limiter_uMax] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limPID_limiter_uMin] = vf.add_const(0.0, name='')
    event_parameters[ctrl_limPID_wd] = vf.add_const(0.0, name='')
    event_parameters[ctrl_limPID_wp] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limPID_xd_start] = vf.add_const(0.0, name='')
    event_parameters[ctrl_limPID_xi_start] = (sym.Const(0.8) / ctrl_Kpg)
    event_parameters[ctrl_limPID_yMax] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limPID_yMin] = vf.add_const(0.0, name='')
    event_parameters[ctrl_limPID_y_start] = vf.add_const(0.8, name='')
    event_parameters[ctrl_limPIDFreeze_FFzero_k] = vf.add_const(0.0, name='')
    event_parameters[ctrl_limPIDFreeze_I_K] = (sym.Const(1.0) / ctrl_limPIDFreeze_Ti)
    event_parameters[ctrl_limPIDFreeze_I_Y0] = ctrl_limPIDFreeze_Xi0
    event_parameters[ctrl_limPIDFreeze_K] = ctrl_Kp
    event_parameters[ctrl_limPIDFreeze_Kff] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limPIDFreeze_Ni] = vf.add_const(0.9, name='')
    event_parameters[ctrl_limPIDFreeze_P_k] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limPIDFreeze_Ti] = (ctrl_Kp / ctrl_Ki)
    event_parameters[ctrl_limPIDFreeze_Wp] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limPIDFreeze_Xi0] = (ctrl_QInj0Pu / ctrl_Kp)
    event_parameters[ctrl_limPIDFreeze_Y0] = ctrl_QInj0Pu
    event_parameters[ctrl_limPIDFreeze_YMax] = ctrl_QMaxPu
    event_parameters[ctrl_limPIDFreeze_YMin] = ctrl_QMinPu
    event_parameters[ctrl_limPIDFreeze_addFF_k1] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limPIDFreeze_addFF_k2] = ctrl_limPIDFreeze_Kff
    event_parameters[ctrl_limPIDFreeze_addI_k1] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limPIDFreeze_addI_k2] = vf.add_const(-1.0, name='')
    event_parameters[ctrl_limPIDFreeze_addI_k3] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limPIDFreeze_addP_k1] = ctrl_limPIDFreeze_Wp
    event_parameters[ctrl_limPIDFreeze_addP_k2] = vf.add_const(-1.0, name='')
    event_parameters[ctrl_limPIDFreeze_addPID_k1] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limPIDFreeze_addPID_k2] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limPIDFreeze_addSat_k1] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limPIDFreeze_addSat_k2] = vf.add_const(-1.0, name='')
    event_parameters[ctrl_limPIDFreeze_gainPID_k] = ctrl_limPIDFreeze_K
    event_parameters[ctrl_limPIDFreeze_gainTrack_k] = (sym.Const(1.0) / (ctrl_limPIDFreeze_Ni * ctrl_limPIDFreeze_K))
    event_parameters[ctrl_limPIDFreeze_limiter_uMax] = ctrl_limPIDFreeze_YMax
    event_parameters[ctrl_limPIDFreeze_limiter_uMin] = ctrl_limPIDFreeze_YMin
    event_parameters[ctrl_limiter_uMax] = vf.add_const(0.0, name='')
    event_parameters[ctrl_limiter_uMin] = vf.add_const(-999.0, name='')
    event_parameters[ctrl_limiter1_uMax] = vf.add_const(999.0, name='')
    event_parameters[ctrl_limiter1_uMin] = vf.add_const(0.0, name='')
    event_parameters[ctrl_lineDropCompensation1_RcPu] = ctrl_RcPu
    event_parameters[ctrl_lineDropCompensation1_XcPu] = ctrl_XcPu
    event_parameters[ctrl_tFilterPC] = vf.add_const(0.02, name='')
    event_parameters[ctrl_tFt] = vf.add_const(0.05, name='')
    event_parameters[ctrl_tFv] = vf.add_const(0.15, name='')
    event_parameters[ctrl_tLag] = vf.add_const(0.2, name='')
    event_parameters[ctrl_tP] = vf.add_const(0.02, name='')
    event_parameters[ctrl_u0Pu_im] = vf.add_const(0.0, name='')
    event_parameters[ctrl_u0Pu_re] = vf.add_const(1.0, name='')
    event_parameters[ctrl_voltageCheck_UMaxPu] = vf.add_const(999.0, name='')
    event_parameters[ctrl_voltageCheck_UMinPu] = ctrl_VFrz
    event_parameters[ctrl_wCtrlErr_k1] = vf.add_const(1.0, name='')
    event_parameters[ctrl_wCtrlErr_k2] = vf.add_const(-1.0, name='')
    event_parameters[ctrl_PRefLim_homotopyType] = vf.add_const(1.0, name='')
    event_parameters[ctrl_QVErrLim_homotopyType] = vf.add_const(1.0, name='')
    event_parameters[ctrl_firstOrder_initType] = vf.add_const(1.0, name='')
    event_parameters[ctrl_firstOrder1_initType] = vf.add_const(1.0, name='')
    event_parameters[ctrl_firstOrder2_initType] = vf.add_const(1.0, name='')
    event_parameters[ctrl_firstOrder3_initType] = vf.add_const(1.0, name='')
    event_parameters[ctrl_leadLag_na] = vf.add_const(2.0, name='')
    event_parameters[ctrl_leadLag_nb] = vf.add_const(2.0, name='')
    event_parameters[ctrl_leadLag_nx] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limPID_I_initType] = vf.add_const(3.0, name='')
    event_parameters[ctrl_limPID_controllerType] = vf.add_const(2.0, name='')
    event_parameters[ctrl_limPID_homotopyType] = vf.add_const(2.0, name='')
    event_parameters[ctrl_limPID_initType] = vf.add_const(5.0, name='')
    event_parameters[ctrl_limPID_limiter_homotopyType] = vf.add_const(2.0, name='')
    event_parameters[ctrl_limPIDFreeze_limiter_homotopyType] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limiter_homotopyType] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limiter1_homotopyType] = vf.add_const(1.0, name='')
    event_parameters[ctrl_FreqFlag] = vf.add_const(0.0, name='')
    event_parameters[ctrl_FreqFlag0_k] = ctrl_FreqFlag
    event_parameters[ctrl_PRefLim_limitsAtInit] = vf.add_const(1.0, name='')
    event_parameters[ctrl_PRefLim_strict] = vf.add_const(0.0, name='')
    event_parameters[ctrl_QVErrLim_limitsAtInit] = vf.add_const(1.0, name='')
    event_parameters[ctrl_QVErrLim_strict] = vf.add_const(0.0, name='')
    event_parameters[ctrl_RefFlag] = vf.add_const(0.0, name='')
    event_parameters[ctrl_RefFlag0_k] = ctrl_RefFlag
    event_parameters[ctrl_VCompFlag] = vf.add_const(0.0, name='')
    event_parameters[ctrl_VCompFlag0_k] = ctrl_VCompFlag
    event_parameters[ctrl_deadZone_deadZoneAtInit] = vf.add_const(1.0, name='')
    event_parameters[ctrl_deadZone1_deadZoneAtInit] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limPID_I_use_reset] = vf.add_const(0.0, name='')
    event_parameters[ctrl_limPID_I_use_set] = vf.add_const(0.0, name='')
    event_parameters[ctrl_limPID_limiter_limitsAtInit] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limPID_limiter_strict] = vf.add_const(0.0, name='')
    event_parameters[ctrl_limPID_limitsAtInit] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limPID_strict] = vf.add_const(0.0, name='')
    event_parameters[ctrl_limPID_withFeedForward] = vf.add_const(0.0, name='')
    event_parameters[ctrl_limPID_with_D] = vf.add_const(0.0, name='')
    event_parameters[ctrl_limPID_with_I] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limPIDFreeze_I_UseFreeze] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limPIDFreeze_I_UseReset] = vf.add_const(0.0, name='')
    event_parameters[ctrl_limPIDFreeze_I_UseSet] = vf.add_const(0.0, name='')
    event_parameters[ctrl_limPIDFreeze_Strict] = vf.add_const(0.0, name='')
    event_parameters[ctrl_limPIDFreeze_WithFeedForward] = vf.add_const(0.0, name='')
    event_parameters[ctrl_limPIDFreeze_limiter_limitsAtInit] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limPIDFreeze_limiter_strict] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limiter_limitsAtInit] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limiter_strict] = vf.add_const(0.0, name='')
    event_parameters[ctrl_limiter1_limitsAtInit] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limiter1_strict] = vf.add_const(0.0, name='')
    event_parameters[ctrl_limPID_unitTime] = vf.add_const(1.0, name='')
    event_parameters[ctrl_limPIDFreeze_unitTime] = vf.add_const(1.0, name='')
    mode_parameters: dict[Var, Expr | Const] = dict()
    initial_equations: dict[Var, Expr | Const] = dict()
    initial_equations[ctrl_firstOrder_y] = START_ctrl_firstOrder_y
    initial_equations[ctrl_firstOrder1_y] = START_ctrl_firstOrder1_y
    initial_equations[ctrl_firstOrder2_y] = START_ctrl_firstOrder2_y
    initial_equations[ctrl_firstOrder3_y] = START_ctrl_firstOrder3_y
    initial_equations[ctrl_leadLag_x_scaled_1] = START_ctrl_leadLag_x_scaled_1
    initial_equations[ctrl_limPID_I_y] = ctrl_limPID_I_y_start
    initial_equations[ctrl_limPIDFreeze_I_y] = START_ctrl_limPIDFreeze_I_y
    initial_equations[ctrl_PInjRefPu] = vf.add_const(0.8, name='')
    initial_equations[ctrl_PRefPu] = vf.add_const(0.8, name='')
    initial_equations[ctrl_PRegPu] = vf.add_const(0.8, name='')
    initial_equations[ctrl_QInjRefPu] = ctrl_leadLag_y_start
    initial_equations[ctrl_QRefPu] = vf.add_const(0.0, name='')
    initial_equations[ctrl_QRegPu] = vf.add_const(0.0, name='')
    initial_equations[ctrl_URefPu] = vf.add_const(1.0, name='')
    initial_equations[ctrl_gain2_y] = vf.add_const(0.0, name='')
    initial_equations[ctrl_iPu_im] = vf.add_const(0.0, name='')
    initial_equations[ctrl_iPu_re] = vf.add_const(0.8, name='')
    initial_equations[ctrl_leadLag_x_1] = ctrl_leadLag_x_start_1
    initial_equations[ctrl_omegaPu] = vf.add_const(1.0, name='')
    initial_equations[ctrl_omegaRefPu] = vf.add_const(1.0, name='')
    initial_equations[ctrl_switch2_y] = vf.add_const(1.0, name='')
    initial_equations[ctrl_uPu_im] = vf.add_const(0.0, name='')
    initial_equations[ctrl_uPu_re] = vf.add_const(1.0, name='')
    initial_equations[ctrl_freeze] = (sym.heaviside(((ctrl_voltageCheck_UMinPu - sym.Const(1.0)) - sym.Const(1e-06))) + sym.heaviside(((sym.Const(1.0) - ctrl_voltageCheck_UMaxPu) - sym.Const(1e-06))))
    initial_equations[ctrl_PRefLim_simplifiedExpr] = vf.add_const(0.0, name='')
    initial_equations[ctrl_limPID_I_local_reset] = vf.add_const(0.0, name='')
    initial_equations[ctrl_limPID_I_local_set] = vf.add_const(0.0, name='')
    initial_equations[ctrl_QVErrLim_simplifiedExpr] = vf.add_const(0.0, name='')
    initial_equations[ctrl_limiter_simplifiedExpr] = vf.add_const(0.0, name='')
    initial_equations[ctrl_limiter1_simplifiedExpr] = vf.add_const(0.0, name='')
    initial_equations[ctrl_limPIDFreeze_limiter_simplifiedExpr] = vf.add_const(0.0, name='')
    initial_equations[ctrl_limPIDFreeze_I_resetLocal] = vf.add_const(0.0, name='')
    initial_equations[ctrl_limPIDFreeze_I_setLocal] = vf.add_const(0.0, name='')
    initial_equations[ctrl_wCtrlErr_y] = (ctrl_wCtrlErr_k1 + ctrl_wCtrlErr_k2)
    initial_equations[ctrl_deadZone1_y] = ((sym.heaviside(((ctrl_wCtrlErr_y - ctrl_deadZone1_uMax) - sym.Const(1e-06))) * (ctrl_wCtrlErr_y - ctrl_deadZone1_uMax)) + ((sym.Const(1.0) - sym.heaviside(((ctrl_wCtrlErr_y - ctrl_deadZone1_uMax) - sym.Const(1e-06)))) * ((sym.heaviside(((ctrl_deadZone1_uMin - ctrl_wCtrlErr_y) - sym.Const(1e-06))) * (ctrl_wCtrlErr_y - ctrl_deadZone1_uMin)) + ((sym.Const(1.0) - sym.heaviside(((ctrl_deadZone1_uMin - ctrl_wCtrlErr_y) - sym.Const(1e-06)))) * sym.Const(0.0)))))
    initial_equations[ctrl_limPID_y] = ((sym.heaviside(((ctrl_limPID_limiter_u - ctrl_limPID_limiter_uMax) - sym.Const(1e-06))) * ctrl_limPID_limiter_uMax) + ((sym.Const(1.0) - sym.heaviside(((ctrl_limPID_limiter_u - ctrl_limPID_limiter_uMax) - sym.Const(1e-06)))) * ((sym.heaviside(((ctrl_limPID_limiter_uMin - ctrl_limPID_limiter_u) - sym.Const(1e-06))) * ctrl_limPID_limiter_uMin) + ((sym.Const(1.0) - sym.heaviside(((ctrl_limPID_limiter_uMin - ctrl_limPID_limiter_u) - sym.Const(1e-06)))) * ctrl_limPID_limiter_u))))
    initial_equations[ctrl_deadZone_y] = ((sym.heaviside(((ctrl_switch1_y - ctrl_deadZone_uMax) - sym.Const(1e-06))) * (ctrl_switch1_y - ctrl_deadZone_uMax)) + ((sym.Const(1.0) - sym.heaviside(((ctrl_switch1_y - ctrl_deadZone_uMax) - sym.Const(1e-06)))) * ((sym.heaviside(((ctrl_deadZone_uMin - ctrl_switch1_y) - sym.Const(1e-06))) * (ctrl_switch1_y - ctrl_deadZone_uMin)) + ((sym.Const(1.0) - sym.heaviside(((ctrl_deadZone_uMin - ctrl_switch1_y) - sym.Const(1e-06)))) * sym.Const(0.0)))))
    initial_equations[ctrl_lineDropCompensation1_U1Pu] = ((((sym.Const(1.0) + (sym.Const(0.8) * ctrl_lineDropCompensation1_RcPu)) ** sym.Const(2.0)) + ((sym.Const(0.8) * ctrl_lineDropCompensation1_XcPu) ** sym.Const(2.0))) ** sym.Const(0.5))
    initial_equations[ctrl_gain_y] = vf.add_const(0.0, name='')
    initial_equations[ctrl_lineDropCompensation1_U2Pu] = vf.add_const(1.0, name='')
    differential_initial_equations: dict[Var, Expr | Const] = dict()
    procedural_logic_entries: list[object] = list()

    # Assemble the final block from the explicit typed collections above.
    template.block = Block(
        state_vars=state_variables,
        state_eqs=state_equations,
        algebraic_vars=algebraic_variables,
        algebraic_eqs=algebraic_equations,
        diff_vars=differential_variables,
        init_eqs=initial_equations,
        diff_init_eqs=differential_initial_equations,
        in_vars=input_variables,
        out_vars=output_variables,
        event_dict=event_parameters,
        mode_dict=mode_parameters,
        procedural_logic=procedural_logic_entries,
        name=template_name,
    )

    template.comment = 'Generator WECC plant controller REPCA'
    return template
